**Swiggy Data Analysis**

**1) Business Objective**

To assess and improve the quality, consistency, and completeness of the grocery product listing data by identifying anomalies, inconsistencies, missing information, duplicates, and pricing irregularities across products, categories, stores, and locations, thereby ensuring accurate product information and enhancing the customer shopping experience.

**2) Import Libraries**

In [5]:
import pandas as pd        # For data manipulation
import numpy as np      # For numerical computations
import seaborn as sns  # For advanced visualization
import matplotlib.pyplot as plt # For plotting
import re # For regular expressions

**3) Import Dataset**

In [6]:
df = pd.read_csv("/home/user/Downloads/2026-07-09/swiggy_instamart_2026_07_09.csv")  #Reading Dataset from csv file

**4) Data Insights**

In [7]:
print("INFORMATION ABOUT DATASET")
print("--------------------------------")
df.info()

INFORMATION ABOUT DATASET
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1227023 entries, 0 to 1227022
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1227023 non-null  object
 1   platform_name            1227023 non-null  object
 2   store_id                 1227023 non-null  int64
 3   store_name_location      1227023 non-null  object
 4   city                     1227023 non-null  object
 5   pin_code                 1227023 non-null  int64
 6   unique_id                1227023 non-null  object
 7   product_id_upc_ean       1227023 non-null  object
 8   department               1227023 non-null  object
 9   category                 1227023 non-null  object
 10  sub_category             1227023 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1226875 non-null  object
 13  product_name             1227023 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         1227023 non-null  object
 16  package_type             0 non-null        float64
 17  net_quantity             0 non-null        float64
 18  variants                 1227023 non-null  object
 19  item_mrp                 1227023 non-null  int64
 20  item_selling_price       1227023 non-null  int64
 21  out_of_stock_flag        1227023 non-null  object
 22  discount_flag            1227023 non-null  object
 23  product_price            1227023 non-null  int64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1227023 non-null  object
 26  promo_offer_price        1227023 non-null  int64
 27  discount_in_percent      1227023 non-null  int64
 28  stock_count              1227023 non-null  int64
 29  product_url              1227023 non-null  object
 30  product_image_urls       1227023 non-null  object
dtypes: float64(5), int64(8), object(18)
memory usage: 290.2+ MB

In [4]:
print("\nDESCRIPTIVE STATISTICS OF DATASET")
print("--------------------------------")
df.describe().T.round(2)

DESCRIPTIVE STATISTICS OF DATASET
--------------------------------

,count,mean,std,min,25%,50%,75%,max
store_id,1227023.0,1.386428e+06,6.987470e+04,762551.0,1390224.0,1400602.0,1402465.0,1.404660e+06
pin_code,1227023.0,4.750532e+05,1.701215e+05,110005.0,400034.0,500075.0,572101.0,8.340050e+05
product_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
package_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
net_quantity,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
item_mrp,1227023.0,7.548554e+08,8.198889e+10,1.0,115.0,230.0,449.0,8.906005e+12
item_selling_price,1227023.0,7.548553e+08,8.198889e+10,1.0,95.0,191.0,369.0,8.906005e+12
product_price,1227023.0,7.548553e+08,8.198889e+10,1.0,95.0,191.0,369.0,8.906005e+12
unit_price,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_offer_price,1227023.0,7.548553e+08,8.198889e+10,1.0,95.0,191.0,369.0,8.906005e+12
discount_in_percent,1227023.0,1.543000e+01,1.524000e+01,0.0,2.0,11.0,24.0,9.200000e+01
stock_count,1227023.0,1.640000e+00,2.640000e+00,0.0,0.0,1.0,2.0,7.800000e+01

In [8]:
print("\nDATASET SHAPE")
print("--------------------------------")
print("The shape =", df.shape)
num_rows, num_cols = df.shape
num_features = num_cols - 1
num_data = num_rows * num_cols

# Print the information about the dataset
print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_cols}")
print(f"Number of Features: {num_features}")
print(f"Number of All Data: {num_data}")

DATASET SHAPE
--------------------------------
The shape = (1227023, 31)
Number of Rows: 1227023
Number of Columns: 31
Number of Features: 30
Number of All Data: 38037713

In [9]:
print("COLUMNWISE DATA PROFILING")
print("--------------------------------")
summary = []

for col in df.columns:
    null_count = df[col].isnull().sum()
    null_percent = round((null_count / len(df)) * 100, 2)
    distinct_count = df[col].nunique(dropna=True)
    
    # Check if all non-null values are unique
    is_unique = "Yes" if df[col].is_unique and null_count == 0 else "No"


    summary.append({
        'column_name': col,
        'null_count': null_count,
        #'null_percent': null_percent,
        'distinct_count': distinct_count,
        'is_unique': is_unique
    })

summary_df = pd.DataFrame(summary)

# Display the summary
print(summary_df)

COLUMNWISE DATA PROFILING
--------------------------------
                column_name  null_count  distinct_count is_unique
0       crawl_date_and_time           0            9521        No
1             platform_name           0               1        No
2                  store_id           0             119        No
3       store_name_location           0             100        No
4                      city           0              48        No
5                  pin_code           0              98        No
6                 unique_id           0          997125        No
7        product_id_upc_ean           0           32060        No
8                department           0               9        No
9                  category           0              16        No
10             sub_category           0             148        No
11             product_type     1227023               0        No
12               brand_name         148            2987        No
13             product_name           0           32499        No
14      product_description     1227023               0        No
15         product_grammage           0            2090        No
16             package_type     1227023               0        No
17             net_quantity     1227023               0        No
18                 variants           0            7928        No
19                 item_mrp           0            1745        No
20       item_selling_price           0            2168        No
21        out_of_stock_flag           0               2        No
22            discount_flag           0               2        No
23            product_price           0            2168        No
24               unit_price     1227023               0        No
25  promo_offer_description           0              90        No
26        promo_offer_price           0            2168        No
27      discount_in_percent           0              90        No
28              stock_count           0              53        No
29              product_url           0           32060        No
30       product_image_urls           0           35750        No

In [10]:
df.store_id.unique()
print(len(df.store_id.unique()))
print(len(df.store_name_location.unique()))

119
100

In [11]:
store_mapping = (
    df.groupby('store_name_location')['store_id']
      .nunique()
      .reset_index(name='unique_store_ids')
      .sort_values('unique_store_ids', ascending=False)
)

multi_store = store_mapping[store_mapping['unique_store_ids'] > 1]

print(multi_store)
print("\nNumber of store_name_location with multiple store_ids:", len(multi_store))

                                  store_name_location  unique_store_ids
50  Kurtosshhh - Hungarian Street Food (Kurtosh), ...                 2
24  Comfort Stay, Lohegaon, Pune, Maharashtra, 411...                 2
98  White Shadows Gymnastic And Silambam Academy, ...                 2
83  Spuddy Ahinsa Khand Badminton Academy, Society...                 2
81  Shikki's, HC-43, Waves Mall Road, Near Flavour...                 2
74  Sahaja Aharam Ware House, Hanuman Nagar, Tarna...                 2
73  SLV Tea Store, Electronics City Phase 1, Elect...                 2
57  Meridian Rooms And Service Apartments, New Kan...                 2
1   1252, Hennur Main Rd, RK Hegde Nagar, Stage 1,...                 2
49  Kohinoor Novelties, 10th Cross, Popular Colony...                 2
48  Kesava Towers, SY. No. 78, 3, Hafeezpet Rd, Bi...                 2
46  Jhandewalan Metro Station, Block E 2, Jhandewa...                 2
38  GoMechanic - Auto Tuners, Basavanna Nagar, Hoo...                 2
37  GM Infinite E City Phase 1 B Block, Block-F, G...                 2
34  Empire Restaurant- HSR Layout, 169/A/170, 9th ...                 2
27  Devdarshan, Mogul LN, New Dinkar Co Operative ...                 2
99  Wittmann Battenfeld India Pvt. Ltd, Wittmann B...                 2
8   948, R.K. Tewari, Saraswati Kunj, Sector 52A, ...                 2
7   8/225, Sector, 8, Malviya Nagar, Jaipur, Rajas...                 2
6   552, Outer Ring Rd, Opposite More Mega Store, ...                 2
11  Ambaji Niketan Bldg, Ambaji Niketan CoOperativ...                 2

Number of store_name_location with multiple store_ids: 21

***Insights :***
_______________
    * Shape of the dataset is 12,42,276 X 31
    * None of the columns is having unique values.
    * 'product_type', 'product_description', 'package_type', 'net_quantity', 'unit_price' are completely null columns.
    * 'brand_name' is a partialy null column with 170 null values.
    * Distinct store_id and store_name_location count are 125 and 100 respectively. While ivestigating, we found that 28 store_name_locations have exactly two store_ids each.

**5) Primary key Analysis**

As per the above informations, no column can be choose as primary key.

In [12]:
# Check if the combination is unique
is_unique = not df.duplicated(subset=['unique_id', 'store_id','product_id_upc_ean', 'product_name']).any()

print("Is (unique_id, store_id, product_id_upc_ean, product_name) combination unique?", is_unique)

Is (unique_id, store_id, product_id_upc_ean, product_name) combination unique? False

Checked several combinations, but couldn't fix a unique combination

**6) Duplicate Analysis**

In [13]:
print("EXACT DUPLICATE ROWS")
print("--------------------------------")
exact_duplicate_count = df.duplicated().sum()
print("Exact duplicate rows:", exact_duplicate_count)


print("\nDUPLICATE PRODUCTS IN THE SAME STORE")
print("--------------------------------")
product_duplicate_count = df.duplicated(
    subset=['store_id', 'product_name']
).sum()

print(f"\nNumber of duplicate products (store_id + product_name): {product_duplicate_count}")


print("\n========== DUPLICATE ANALYSIS SUMMARY ==========")
print(f"Total Rows                  : {len(df)}")
print(f"Exact Duplicate Rows        : {exact_duplicate_count}")
print(f"Product Duplicate Rows      : {product_duplicate_count}")
print("================================================")

EXACT DUPLICATE ROWS
--------------------------------
Exact duplicate rows: 0

DUPLICATE PRODUCTS IN THE SAME STORE
--------------------------------

Number of duplicate products (store_id + product_name): 292521

========== DUPLICATE ANALYSIS SUMMARY ==========
Total Rows                  : 1227023
Exact Duplicate Rows        : 0
Product Duplicate Rows      : 292521
================================================

In [14]:
# checking for duplicate combinations of store_name_location, product_name, product_grammage, item_selling_price and package_type
dup_products = (
    df.groupby([
        'store_name_location',
        'product_name',
        'product_grammage',
        'item_selling_price',
        'package_type'
    ])
    .size()
    .reset_index(name='count')
)

dup_products = dup_products[dup_products['count'] > 1]\
                    .sort_values('count', ascending=False)

print("Duplicate combinations:", len(dup_products))
print(dup_products.head(20))

Duplicate combinations: 0
Empty DataFrame
Columns: [store_name_location, product_name, product_grammage, item_selling_price, package_type, count]
Index: []

In [15]:
# Check for products mapped to multiple categories
product_category_check = (
    df.groupby(['store_name_location', 'product_name','product_grammage', 'product_url'])['category']
      .nunique()
      .reset_index(name='category_count')
)

# Products mapped to more than one category
inconsistent_products = product_category_check[
    product_category_check['category_count'] > 1
].sort_values('category_count', ascending=False)

print("Number of inconsistent products:",
      len(inconsistent_products))

print(inconsistent_products.head())
print("\nNumber of inconsistent products:", len(inconsistent_products))

Number of inconsistent products: 87022
                                      store_name_location  \
403740  Gokul Apartment, Ayodhya Chowk, Near Taruvar A...
97176   Aastha Riverview, Aastha River View Sector 18,...
287143  Dhandapani Exports Pvt Ltd, 42/24, Hastinapura...
500959  Kohinoor Novelties, 10th Cross, Popular Colony...
547825  M4 Ocean View, 28, D Koyande Rd, Ekta Nagar, M...

                                             product_name product_grammage  \
403740  Elicious Naturals Neem Leaf Powder For Hair, S...            200 g
97176   Elicious Naturals Neem Leaf Powder For Hair, S...            200 g
287143  Elicious Naturals Neem Leaf Powder For Hair, S...            200 g
500959  Elicious Naturals Neem Leaf Powder For Hair, S...            200 g
547825  Elicious Naturals Neem Leaf Powder For Hair, S...            200 g

                                             product_url  category_count
403740  https://www.swiggy.com/instamart/item/NJ8JG6Q1BC               4
97176   https://www.swiggy.com/instamart/item/NJ8JG6Q1BC               4
287143  https://www.swiggy.com/instamart/item/NJ8JG6Q1BC               4
500959  https://www.swiggy.com/instamart/item/NJ8JG6Q1BC               4
547825  https://www.swiggy.com/instamart/item/NJ8JG6Q1BC               4

Number of inconsistent products: 87022

In [18]:
# Check for products mapped to multiple sub_categories
product_category_check = (
    df.groupby(['store_name_location', 'product_name','product_grammage', 'product_url'])['sub_category']
      .nunique()
      .reset_index(name='sub_category_count')
)

# Products mapped to more than one category
inconsistent_products = product_category_check[
    product_category_check['sub_category_count'] > 1
].sort_values('sub_category_count', ascending=False)

print("Number of inconsistent products:",
      len(inconsistent_products))

print(inconsistent_products.head())
print("\nNumber of inconsistent products:", len(inconsistent_products))

Number of inconsistent products: 185830
                                      store_name_location  \
36444   2, Mumbai Cantral Rd, Dadal Estate, Bane Compo...
167225  Bali Residency CHS Ltd, Marve Rd, Malad, Kharo...
238603  Claw Play Colaba, Ground Floor Sidhwa House Co...
529528  Lohonostays Moira Villa 18, Bamordem Moira, Ki...
802363  Shifa Motor, Fatima Nagar, Satellite Colony, D...

                                             product_name product_grammage  \
36444   Cadbury Celebrations Premium Selections Assort...            155 g
167225  Cadbury Celebrations Premium Selections Assort...            155 g
238603  Cadbury Celebrations Premium Selections Assort...            155 g
529528  Cadbury Celebrations Premium Selections Assort...            155 g
802363  Cadbury Celebrations Premium Selections Assort...            155 g

                                             product_url  sub_category_count
36444   https://www.swiggy.com/instamart/item/A3RUP7TQI9                   5
167225  https://www.swiggy.com/instamart/item/A3RUP7TQI9                   5
238603  https://www.swiggy.com/instamart/item/A3RUP7TQI9                   5
529528  https://www.swiggy.com/instamart/item/A3RUP7TQI9                   5
802363  https://www.swiggy.com/instamart/item/A3RUP7TQI9                   5

Number of inconsistent products: 185830

In [21]:
# Count distinct product names for each unique_id
product_name_counts = (
    df.groupby("unique_id")["product_name"]
      .nunique(dropna=False)
)

# unique_id values having more than one product_name
duplicate_unique_ids = product_name_counts[product_name_counts > 1].index

print(f"Number of unique_id values with different product_name: {len(duplicate_unique_ids)}")
print(duplicate_unique_ids.tolist())

Number of unique_id values with different product_name: 0
[]

***Insights :***
___________________

    * No exact duplicate columns exists on the dataset, but products duplicates on same stores
    * While deeply investigating, these duplicate products differ by grammage, price or package_type.
    * Also confirmed no products duplicates on same store under different categories.
    * In overall, the dataset is not containing duplicate products visibly.

7) MISSING VALUE ANALYSIS

As mentioned some columns are completely null, that not need to be evaluated. brand_name column is partially null with 170 null values. Lets evaluate that.

In [23]:
# Missing summary by store
print("\nMISSING SUMMARY BY STORE")
print("--------------------------------")
missing_by_store = df.groupby('store_name_location')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_store)

MISSING SUMMARY BY STORE
--------------------------------
                                  store_name_location  brand_name
0   111/1C, Sarat Ghosh Garden Rd, Dhakuria, Sarat...    0.022452
1   1252, Hennur Main Rd, RK Hegde Nagar, Stage 1,...    0.007194
2   1980'S Military Hotel, 312, Sainikpuri Rd, Shi...    0.005263
3   2, Mumbai Cantral Rd, Dadal Estate, Bane Compo...    0.012003
4   248/30, Water Tank Rd, Kamarajar Nagar, Nagerc...    0.012060
..                                                ...         ...
95  Vignesh Group Of Companies - Logistics | 3PL |...    0.000000
96  Vilasi Delight, MG Rd, Behind Shree Krishna Th...    0.014886
97           Villa Serena, Siolim, Goa, 403517, India    0.000000
98  White Shadows Gymnastic And Silambam Academy, ...    0.007798
99  Wittmann Battenfeld India Pvt. Ltd, Wittmann B...    0.018700

[100 rows x 2 columns]

In [24]:
# Missing summary by category
print("\nMISSING SUMMARY BY CATEGORY")
print("--------------------------------")
missing_by_category = df.groupby('category')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_category)

MISSING SUMMARY BY CATEGORY
--------------------------------
                          category  brand_name
0               Atta, Rice and Dal    0.106281
1                        Baby Care    0.000000
2                    Bath and Body    0.001310
3               Biscuits and Cakes    0.000000
4            Cereals and Breakfast    0.000000
5               Chips and Namkeens    0.000000
6                       Chocolates    0.000983
7           Cold Drinks and Juices    0.000000
8            Dairy, Bread and Eggs    0.000000
9                 Feminine Hygiene    0.000000
10                       Hair Care    0.000000
11  Ice Creams and Frozen Desserts    0.039487
12                          Makeup    0.039041
13                     Paan Corner    0.000000
14                        Skincare    0.000000
15                    Sweet Corner    0.000000

In [25]:
print("\nMISSING SUMMARY BY CITY")
print("--------------------------------")

missing_by_city = df.groupby('city')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_city)

MISSING SUMMARY BY CITY
--------------------------------
              city  brand_name
0        Ahmedabad    0.004767
1            Ajmer    0.018445
2           Ambala    0.000000
3         Bambolim    0.000000
4        Bangalore    0.013147
5      Bhubaneswar    0.000000
6   Changanacherry    0.000000
7       Chengannur    0.000000
8          Chennai    0.013241
9       Coimbatore    0.008018
10           Delhi    0.021564
11       Ghaziabad    0.025952
12         Gurgaon    0.014425
13        Guwahati    0.000000
14     Harveypatti    0.010223
15       Hyderabad    0.024351
16          Jaipur    0.018179
17      Jamshedpur    0.000000
18         Khammam    0.008690
19           Kochi    0.005567
20         Kolazhy    0.010391
21        Kolhapur    0.000000
22         Kolkata    0.016672
23       Kozhikode    0.000000
24         Lucknow    0.018262
25        Ludhiana    0.000000
26          Meerut    0.009206
27          Mohali    0.012323
28           Moira    0.000000
29       Moradabad    0.010380
30          Mumbai    0.011271
31          Mysuru    0.014321
32       Nagercoil    0.012060
33          Nagpur    0.008233
34           Noida    0.006740
35          Panaji    0.025971
36            Pune    0.014774
37          Rajkot    0.000000
38          Ranchi    0.000000
39     S.A.S Nagar    0.011823
40    Secunderabad    0.032677
41          Siolim    0.000000
42           Thane    0.007297
43      Trivandrum    0.000000
44        Tumakuru    0.014886
45          Ujjain    0.010601
46        Varanasi    0.000000
47         Vellore    0.000000

***Insights :***
_______________

    * In store-wise, missing values are almost equally distributed.
    * In category-wise also mising percentage is below 0.2, which is negliglible.
    * In city-wise too, the missing percentage has no hike at any particular city.
    * So in overall missing% doesn't have any direct impact form store/category/city.

**8) Category Hierarchy Consistency**

In [26]:
print("\n DEPARTMENT - CATEGORY CONSISTENCY")
print("--------------------------------")

dept_category_map = df.groupby('department')['category'].unique()

for dept, cats in dept_category_map.items():
    print("\nDEPARTMENT:", dept)
    print(list(cats))

 DEPARTMENT - CATEGORY CONSISTENCY
--------------------------------

DEPARTMENT: Atta, Rice & Dal
['Atta, Rice and Dal']

DEPARTMENT: Baby Care
['Baby Care']

DEPARTMENT: Bakery & Biscuits
['Biscuits and Cakes']

DEPARTMENT: Beauty & Cosmetics
['Hair Care', 'Bath and Body', 'Makeup']

DEPARTMENT: Cold Drinks & Juices
['Cold Drinks and Juices']

DEPARTMENT: Dairy & Breakfast
['Cereals and Breakfast', 'Dairy, Bread and Eggs']

DEPARTMENT: Munchies
['Chips and Namkeens', 'Cereals and Breakfast']

DEPARTMENT: Personal Care
['Bath and Body', 'Skincare', 'Feminine Hygiene', 'Hair Care', 'Makeup']

DEPARTMENT: Sweet Tooth
['Ice Creams and Frozen Desserts', 'Sweet Corner', 'Chocolates', 'Paan Corner']

In [27]:
print("\n CATEGORY - SUBCATEGORY CONSISTENCY")
print("--------------------------------")

cat_subcat_map = df.groupby('category')['sub_category'].unique()

for cat, subcats in cat_subcat_map.items():
    print("\nCATEGORY:", cat)
    print(list(subcats))

 CATEGORY - SUBCATEGORY CONSISTENCY
--------------------------------

CATEGORY: Atta, Rice and Dal
['Toor, Moong and Urad', 'Poha & Puffed Rice', 'Rajma, Chola and Others', 'Atta', 'Besan, Sooji and Maida', 'Rice', 'Millets & Daliya', 'Other Flours']

CATEGORY: Baby Care
['Gifts & More', 'Baby Oral Care', 'Books and Toys', 'Baby Oil and Talc', 'Baby Cream & Lotions', 'Baby Wipes', 'Baby Bathing', 'Clothes & Accessories', 'Baby Diapers', 'Baby Food and Formula', 'Feeding and Teething Needs', 'Mom Care', 'Baby Pharma', 'Baby Hygiene', 'Travel Needs & Baby Gears']

CATEGORY: Bath and Body
['Lip care', 'Roll on', 'Womens Perfume', 'Face Care', 'Bath & Beauty gifts', 'Fragrance & Talc', 'Soaps', 'Bath Accessories', 'Handwash', 'Shower gel', 'Body Lotion & Oils', 'Oral care', 'Mens Perfume', 'Multi groomers']

CATEGORY: Biscuits and Cakes
['Cookies', 'Baking Ingredients', 'Cream Biscuits', 'Marie & Digestive', 'Gourmet collection', 'Healthy Snacking', 'Rusk', 'Salted & Plain', 'Wafers', 'Gift Boxes', 'Cakes & Pies', 'Fresh Bakery']

CATEGORY: Cereals and Breakfast
['Batters', 'Kids Cereals', 'Ready Mixes', 'Pancake Mixes', 'Seeds and trail Mixes', 'Energy Bars', 'Muesli & Granola', 'Peanut Butters', 'Flakes', 'Oats']

CATEGORY: Chips and Namkeens
['Bhujia and Namkeens', 'Chips and Crisps', 'Makhana & Dry Fruits', 'Popcorn', 'Gift Hampers', 'Nachos']

CATEGORY: Chocolates
['Milk Chocolates', 'Dark Chocolates', 'Premium', 'Candies & More', 'Shared Packs', 'Wafers', 'Gums & Mint', 'Kunafa Chocolate', 'Gift Boxes', 'Gourmet collection']

CATEGORY: Cold Drinks and Juices
['Fresh Juices', 'Soda and Mixers', 'Soft Drinks', 'Water and Ice Cubes', 'Mango Drinks', 'Energy Drinks', 'Juices and Fruit Drinks', 'Ice Tea & Kombucha', 'Milk Based Drinks', 'Cold Coffee', 'Coconut Water']

CATEGORY: Dairy, Bread and Eggs
['Curd and Yogurts', 'Bread and Buns', 'Milkshakes and More', 'Lassi and Buttermilk', 'Milk', 'Butter', 'Cheese', 'Eggs', 'Cream and Condensed Milk', 'Paneer and Tofu']

CATEGORY: Feminine Hygiene
['Sanitary Pads', 'Period Panties and Liners', 'Hair Removal', 'Disposal Bags and Cramp Relief', 'Menstrual Cups and Tampons', 'Intimate Wipes and Wash']

CATEGORY: Hair Care
['Hair Oils and Serums', 'Conditioners & Masks', 'Hair Colour', 'Hair Dryers and Stylers', 'Hair Styling Gels & Creams', 'Combs & Brushes', 'Hair Supplements', 'Premium Brands', 'Shampoo']

CATEGORY: Ice Creams and Frozen Desserts
['Tubs & Party Packs', 'Syrups', 'Cones', 'Regional Favorites', 'Sticks', 'Cups', 'Guiltfree', 'Real Fruit', 'Kulfi', 'Premium', 'Gourmet', 'Cakes & Sandwiches', 'Rare Finds']

CATEGORY: Makeup
['Eyes', 'Face', 'Lips', 'Nails', 'Eye lens', 'Tools & Brushes']

CATEGORY: Paan Corner
['Gum and Mint', 'Paan and Mouth Fresheners']

CATEGORY: Skincare
['Creams & Moisturizers', 'Masks & Cleansers', 'Face wash and scrubs', 'Serums, Toners', 'Sunscreen', 'Body Lotions', 'Beauty Supplements']

CATEGORY: Sweet Corner
['Rasgulla', 'Dry Fruit Sweets', 'Kaju Katli & Barfi', 'Chikki', 'Dessert Mixes', 'Rasmalai', 'Mysore Pak', 'Cream Biscuits', 'Ladoos', 'Chocofills', 'Pedhas', 'Gulab Jamun', 'Cakes and Pies', 'Gulkand & Paan']

***Insights :***
___________________

    * No specific inconsistencies noticed accross department-category or category-subcategory combinations

**9) Suspicious Value Checking**

In [28]:
def find_suspicious_values(df, column_name):
    suspicious_values = [
        'null', 'none', 'n/a', 'na', 'nil', 'not available',
        'not applicable', '-', '--', '0', ''
    ]
    
    mask = (
        df[column_name].isna() |
        df[column_name].astype(str).str.strip().str.lower().isin(suspicious_values) |
        df[column_name].str.fullmatch(r'\d+') |   # numeric only
        (df[column_name].str.len() < 3)    # too short
        )
    
    df_suspicious = df[mask]
    print(f"Number of suspicious values in '{column_name}': {len(df_suspicious)}")
    return df_suspicious[column_name].unique()

print(find_suspicious_values(df, 'product_name'))
print(find_suspicious_values(df, 'brand_name'))
print(find_suspicious_values(df, 'store_name_location'))
print(find_suspicious_values(df, 'department'))
print(find_suspicious_values(df, 'category'))
print(find_suspicious_values(df, 'sub_category'))

Number of suspicious values in 'product_name': 0
[]
Number of suspicious values in 'brand_name': 3430
[nan '921' 'P' 'Jo' 'Yu' 'RG' 'Go' 'He' 'C4' 'Lu' 'Ob' 'SS' 'SP']
Number of suspicious values in 'store_name_location': 0
[]
Number of suspicious values in 'department': 0
[]
Number of suspicious values in 'category': 0
[]
Number of suspicious values in 'sub_category': 0
[]

***Insights :***
____________

    * Suspicious values noticed on brand_name column.
    * Checked website to confirm whether these brand_names really exists or not.
    * Most of them really exists, but urls of some brands are not able to access.
    * Complete urls on brand_name 'RG' and 'C4' and some urls on other brands are not accessible, which is a critical issue.

**10) Price Anomalies**

In [29]:
def check_negative_and_zero(df, column):
    """
    Returns rows where the given column has:
    - negative values (< 0)
    - zero values (== 0)
    """

    # Ensure numeric (safe for real-world messy data)
    df[column] = pd.to_numeric(df[column], errors='coerce')

    negative_values = df[df[column] < 0]
    zero_values = df[df[column] == 0]

    return {
        "negative_values": negative_values[['unique_id', column]],
        "zero_values": zero_values[['unique_id', column]]
    }

print("\nItem MRP:")
print(check_negative_and_zero(df, 'item_mrp'))
print("\nItem Selling Price:")
print(check_negative_and_zero(df, 'item_selling_price'))
print("\nProduct Price:")
print(check_negative_and_zero(df, 'product_price'))
print("\nPromo Offer Price:")
print(check_negative_and_zero(df, 'promo_offer_price'))

Item MRP:
{'negative_values': Empty DataFrame
Columns: [unique_id, item_mrp]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, item_mrp]
Index: []}

Item Selling Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, item_selling_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, item_selling_price]
Index: []}

Product Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, product_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, product_price]
Index: []}

Promo Offer Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, promo_offer_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, promo_offer_price]
Index: []}

In [30]:
# check if item_selling_price is greater than item_mrp
df[df['item_selling_price'] > df['item_mrp']][['unique_id', 'item_selling_price', 'item_mrp']]

Empty DataFrame
Columns: [unique_id, item_selling_price, item_mrp]
Index: []

In [31]:
# check if discount_in_percent is greater than 0 and item_selling_price is greater than or equal to item_mrp
df[
    (df['discount_in_percent'] > 0) &
    (df['item_selling_price'] >= df['item_mrp'])
][['unique_id', 'item_selling_price', 'item_mrp', 'discount_in_percent']]

Empty DataFrame
Columns: [unique_id, item_selling_price, item_mrp, discount_in_percent]
Index: []

In [32]:
# check if promo_offer_description is not null and promo_offer_price is null
df[
    (df['promo_offer_description'].notnull()) &

    (df['promo_offer_price'].isnull())][['unique_id', 'promo_offer_description', 'promo_offer_price']]

Empty DataFrame
Columns: [unique_id, promo_offer_description, promo_offer_price]
Index: []

In [33]:
# check if promo_offer_price is not null and promo_offer_price is not equal to item_selling_price
df[
    (df['promo_offer_price'].notnull()) &
    (df['promo_offer_price'] != df['item_selling_price'])
][['unique_id', 'promo_offer_description', 'promo_offer_price', 'item_selling_price']]

Empty DataFrame
Columns: [unique_id, promo_offer_description, promo_offer_price, item_selling_price]
Index: []

In [34]:
# check if out_of_stock_flag is True and stock_count is greater than 0
df[
    (df['out_of_stock_flag'] == True) &
    (df['stock_count'] > 0)
][['unique_id', 'store_id', 'product_id_upc_ean']]

Empty DataFrame
Columns: [unique_id, store_id, product_id_upc_ean]
Index: []

***Insights :***
____________

    * No specific anomalies found on price related columns
    * All such columns are greater than 0.
    * selling price and mrp are equal.
    * selling price is always less than mrp if discount percentage exists.
    * if promo offer description exists, promo offer price also exists.
    * If out of stock flag true, stock count is zero.

**11) URL Checking**

In [35]:
total_records = len(df)
missing_urls = df['product_url'].isnull().sum()
unique_urls = df['product_url'].nunique(dropna=True)
duplicate_urls = df['product_url'].duplicated().sum()

print("URL ANALYSIS SUMMARY")
print("-" * 40)
print(f"Total records           : {total_records}")
print(f"Missing URLs            : {missing_urls}")
print(f"Unique URLs             : {unique_urls}")
print(f"Duplicate URLs          : {duplicate_urls}")
print(f"Uniqueness %            : {(unique_urls/total_records)*100:.2f}%")

URL ANALYSIS SUMMARY
----------------------------------------
Total records           : 1227023
Missing URLs            : 0
Unique URLs             : 32060
Duplicate URLs          : 1194963
Uniqueness %            : 2.61%

In [36]:
# Duplicate URL Records
# ----------------------------
duplicate_url_df = df[
    df['product_url'].duplicated(keep=False)
].sort_values('product_url')

print("\nDuplicate URL Records:")
print(duplicate_url_df[['unique_id', 'product_name', 'product_url']].head())

Duplicate URL Records:
          unique_id                                       product_name  \
724990   47C1F5SNSF  FACES CANADA Ultime Pro Splash Nail Enamel - P...
1215867  6CG9TM8YPX  FACES CANADA Ultime Pro Splash Nail Enamel - P...
151387   WOWK8Y5NJ0  FACES CANADA Ultime Pro Splash Nail Enamel - P...
216627   IH12854B9S  FACES CANADA Ultime Pro Splash Nail Enamel - P...
702891   J5HN2SMQXB  FACES CANADA Ultime Pro Splash Nail Enamel - P...

                                              product_url
724990   https://www.swiggy.com/instamart/item/0009OYBIMZ
1215867  https://www.swiggy.com/instamart/item/0009OYBIMZ
151387   https://www.swiggy.com/instamart/item/0009OYBIMZ
216627   https://www.swiggy.com/instamart/item/0009OYBIMZ
702891   https://www.swiggy.com/instamart/item/0009OYBIMZ

In [37]:
# ----------------------------
# URL Format Validation
# ----------------------------

# Regex for HTTP/HTTPS URLs
url_pattern = re.compile(
    r'^(https?://)'               # http:// or https://
    r'([\w.-]+)'                  # domain
    r'(\.[a-zA-Z]{2,})'           # TLD
    r'([/\w .?%&=+-]*)?$'         # path/query
)

invalid_urls = df[
    df['product_url'].notnull() &
    ~df['product_url'].astype(str).str.match(url_pattern)
]

print("\nInvalid URL Format Count:", len(invalid_urls))

print("\nSample Invalid URLs:")
print(
    invalid_urls[
        ['unique_id', 'product_name', 'product_url']
    ].head(10)
)

Invalid URL Format Count: 0

Sample Invalid URLs:
Empty DataFrame
Columns: [unique_id, product_name, product_url]
Index: []

In [38]:
# ----------------------------
# URLs without http/https
# ----------------------------
missing_protocol = df[
    df['product_url'].notnull() &
    ~df['product_url'].astype(str).str.startswith(('http://', 'https://'))
]

print("\nURLs missing protocol (http/https):", len(missing_protocol))

print(
    missing_protocol[
        ['unique_id', 'product_name', 'product_url']
    ].head()
)

URLs missing protocol (http/https): 0
Empty DataFrame
Columns: [unique_id, product_name, product_url]
Index: []

***Insights***
___________
* Format and pattern of urls are correct
* But 1210545 duplicate urls present on the dataset.
* However these duplcates have different store location and different price range.

**12) City, Store, Pincode Analysis**

In [39]:
# Missing percentage by city

missing_by_city = (
    df.groupby('city')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by city

df['out_of_stock_flag_num'] = (
    df['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_city = (
    df.groupby('city')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by city

discount_by_city = (
    df.groupby('city')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by city

products_by_city = (
    df.groupby('city')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
city_analysis = (
    missing_by_city
    .merge(stockout_by_city, on='city', how='outer')
    .merge(discount_by_city, on='city', how='outer')
    .merge(products_by_city, on='city', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nCITY ANALYSIS SUMMARY")
print("--------------------------------")
print(city_analysis)

/tmp/ipykernel_12416/439306221.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

CITY ANALYSIS SUMMARY
--------------------------------
              city  missing_perc  stockout_perc  avg_discount_perc  \
40    Secunderabad     16.130086      39.138959          15.035128
35          Panaji     16.129870      53.285288          15.353396
11       Ghaziabad     16.129869      39.948097          15.277163
15       Hyderabad     16.129818      40.904018          14.930002
10           Delhi     16.129728      41.553058          15.016915
1            Ajmer     16.129627      33.800609          16.634603
24         Lucknow     16.129621      37.280862          16.871622
16          Jaipur     16.129619      38.556626          16.452009
22         Kolkata     16.129570      49.064992          15.089194
44        Tumakuru     16.129512      54.566431          15.255527
36            Pune     16.129509      42.844743          15.589558
12         Gurgaon     16.129498      33.350162          15.821926
31          Mysuru     16.129494      41.135192          15.451117
8          Chennai     16.129459      38.588245          15.179442
4        Bangalore     16.129456      36.862125          14.979490
27          Mohali     16.129430      38.361060          15.876402
32       Nagercoil     16.129421      47.708635          15.636276
39     S.A.S Nagar     16.129414      34.830929          15.901159
30          Mumbai     16.129396      50.093335          14.872571
45          Ujjain     16.129374      28.760734          15.991519
20         Kolazhy     16.129367      38.352037          16.061201
29       Moradabad     16.129367      25.949761          15.955885
14     Harveypatti     16.129362      32.406461          16.116745
26          Meerut     16.129329      22.967873          16.232809
18         Khammam     16.129313      20.576990          16.332812
33          Nagpur     16.129298      30.026346          16.268648
9       Coimbatore     16.129291      47.296051          16.156144
42           Thane     16.129268      46.326158          14.835972
34           Noida     16.129250      27.495451          15.446991
19           Kochi     16.129212      51.299967          16.085375
0        Ahmedabad     16.129186      45.498534          16.066360
28           Moira     16.129032      24.275077          16.797372
6   Changanacherry     16.129032      46.503011          15.839972
46        Varanasi     16.129032      51.102135          17.200692
2           Ambala     16.129032      32.801519          15.809402
3         Bambolim     16.129032      32.934914          15.740458
43      Trivandrum     16.129032      57.104688          15.798640
5      Bhubaneswar     16.129032      59.758780          15.898430
41          Siolim     16.129032      33.539136          15.674567
7       Chengannur     16.129032      43.639475          15.844837
25        Ludhiana     16.129032      35.302307          16.858095
38          Ranchi     16.129032      38.931547          16.578827
37          Rajkot     16.129032      32.434180          16.054596
13        Guwahati     16.129032      41.732167          16.063547
17      Jamshedpur     16.129032      52.487947          15.949695
21        Kolhapur     16.129032      29.710517          15.756166
23       Kozhikode     16.129032      49.785671          14.959706
47         Vellore     16.129032      45.444425          15.561911

    product_count
40           9862
35          12794
11          18727
15          80140
10          33636
1            8893
24           8833
16           8907
22          29149
44          11147
36          44002
12          11261
31          16821
8           61317
4          181511
27           6488
32           6529
39           6739
30         115466
45           7497
20           7719
29           7623
14           7716
26           8782
18           9215
33           9974
9           20099
42          11058
34          24522
19          29189
0           34047
28           9157
6            6767
46           6853
2            8541
3            7968
43          10111
5           10805
41           8023
7            6911
25           8033
38           9945
37           8791
13          11244
17           8838
21           9592
23           6505
47           9378

In [40]:
# Missing percentage by store

missing_by_store = (
    df.groupby('store_name_location')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by store

df['out_of_stock_flag_num'] = (
    df['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_store = (
    df.groupby('store_name_location')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by store

discount_by_store = (
    df.groupby('store_name_location')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by store

products_by_store = (
    df.groupby('store_name_location')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
store_analysis = (
    missing_by_store
    .merge(stockout_by_store, on='store_name_location', how='outer')
    .merge(discount_by_store, on='store_name_location', how='outer')
    .merge(products_by_store, on='store_name_location', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nSTORE ANALYSIS SUMMARY")
print("--------------------------------")
print(store_analysis)

/tmp/ipykernel_12416/3222998141.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

STORE ANALYSIS SUMMARY
--------------------------------
                                  store_name_location  missing_perc  \
26  Delta Residency, 745, New Hafeezpet, Gopal Red...     15.626403
66  Pai International Electronics Ltd, Dno 2-2-58 ...     15.626393
48  Kesava Towers, SY. No. 78, 3, Hafeezpet Rd, Bi...     15.626264
94  Ultra Dry Cleaners, Railway Road, Jhilmil Indl...     15.626058
25  DTDC GK-1, 38, Basement, Zuari House, Near Gur...     15.626052
..                                                ...           ...
56  Matrix Pharmacy, Yas Complex Golf Link Road Op...     15.625000
15  Babu Kirana Store, Kondli, Greater Noida, Kond...     15.625000
59  More SuperMarket, Valuthadathil Complex, Groun...     15.625000
22  Champaran Meat House, Susuwahi Rd, Karmanveer,...     15.625000
62  Nijom Path, Jaya Nagar, Khanapara, Guwahati, A...     15.625000

    stockout_perc  avg_discount_perc  product_count
26      47.115600          14.340067           7149
66      49.632353          14.581439           7262
48      44.978166          14.954472           9967
94      44.739219          14.581960           7101
25      46.430976          14.639843           7165
..            ...                ...            ...
56      49.785671          14.959706           6505
15      30.284357          15.295141          13030
59      43.639475          15.844837           6911
22      51.102135          17.200692           6853
62      41.732167          16.063547          11244

[100 rows x 5 columns]

In [41]:
# Missing percentage by pincode

missing_by_pincode = (
    df.groupby('pin_code')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by pincode

df['out_of_stock_flag_num'] = (
    df['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_pincode = (
    df.groupby('pin_code')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by pincode

discount_by_pincode = (
    df.groupby('pin_code')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by pincode

products_by_pincode = (
    df.groupby('pin_code')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
pincode_analysis = (
    missing_by_pincode
    .merge(stockout_by_pincode, on='pin_code', how='outer')
    .merge(discount_by_pincode, on='pin_code', how='outer')
    .merge(products_by_pincode, on='pin_code', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nPINCODE ANALYSIS SUMMARY")
print("--------------------------------")
print(pincode_analysis)

/tmp/ipykernel_12416/3770454122.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

PINCODE ANALYSIS SUMMARY
--------------------------------
    pin_code  missing_perc  stockout_perc  avg_discount_perc  product_count
51    500084     15.626403      47.115600          14.340067           7149
47    500013     15.626393      49.632353          14.581439           7262
52    500085     15.626264      44.978166          14.954472           9967
3     110095     15.626058      44.739219          14.581960           7101
1     110048     15.626052      46.430976          14.639843           7165
..       ...           ...            ...                ...            ...
34    403507     15.625000      24.275077          16.797372           9157
80    632004     15.625000      45.444425          15.561911           9378
35    403517     15.625000      33.539136          15.674567           8023
42    416011     15.625000      29.710517          15.756166           9592
97    834005     15.625000      38.931547          16.578827           9945

[98 rows x 5 columns]

***Insights :***
__________________

    * missing percentage is almost equally distributed over all dimensions
    * stockout percentage and product count has significant hike based on some cities, stores, pincodes etc.
    * However discount_percentage is also have almost equal distribution over different dimensions

**13) High Price Variations**

In [42]:
# Price Variation Analysis
price_variation = (
    df.groupby('product_id_upc_ean')
      .agg(
          product_name=('product_name', 'first'),
          min_price=('item_selling_price', 'min'),
          max_price=('item_selling_price', 'max'),
          mean_price=('item_selling_price', 'mean'),
          num_locations=('city', 'nunique')
      )
      .reset_index()
)

# Calculate percentage variation
price_variation['price_variation_pct'] = (
    (price_variation['max_price'] - price_variation['min_price'])
    / price_variation['min_price'] * 100
).round(2)

# Flag products having >30% variation
high_variation = price_variation[
    price_variation['price_variation_pct'] > 30
].sort_values('price_variation_pct', ascending=False)

print(high_variation.head(20))

      product_id_upc_ean                                       product_name  \
29520         X1UP6TZ2CH   CLEAR Premium Drinking Water with Added Minerals
27920         V5U7GYM8HO       RENEE Pink False Stick On Nails (Pack of 24)
12758         DYU1NS9OBF                                 Nutella B ready T1
11472         CINZFGBCD4                       Liril Cooling Mint Body Wash
28057         VC5XDUUVU7                               Coca-Cola Party Pack
26139         T0AFRUK90Q                 Chupa Chups Rockat Sour Soft Candy
5667          63FRSPU0EC     NOICE Natural Coconut Water (No Preservatives)
13507         ESWAQTN109             Himalayan Natural Mineral Water Bottle
25104         RUR8E3DZ69                      Red Bull Energy Drink, 250 ml
15469         GY12SME90J  NOICE Coconut Water With Malai Chunks (No Pres...
11797         CWA1JGHGHP     Red Bull The Yellow Edition Energy Drink 250ml
25596         SFLPSVFYWS  NOICE Sweet Gavvalu Homestyle (No Palm Oil Nam...
20238         M9QXZYJMLV     Red Bull Energy Drink - The Red Edition 250 ml
15604         H3O2WU1A10                                   POLO Breath Mint
23173         PKGH8JLDJ3                   Red Bull Sugar Free Energy Drink
7851          8GC3ZT828N                          Cothas Cold Coffee- Mocha
13168         EEYTBO5A4D  Farmley Dark Choco Orange Date Bites Dessert |...
2781          30EEACLT1J        Himalayan Natural Mineral Water With pH 7-8
30837         YLK22GCO0C  NOICE Rajasthani Bhujia Sev (No Palm Oil Namke...
18431         K7LHIYJK8L  Peping Digestive Shot - Fennel, Coconut and Pr...

       min_price  max_price  mean_price  num_locations  price_variation_pct
29520          5        323   36.719512             33              6360.00
27920         11        615  589.833333             17              5490.91
12758          1         46   41.190909             12              4500.00
11472        154       5600  338.000000             35              3536.36
28057         22        792  273.969697             27              3500.00
26139         50       1600  177.631579             25              3100.00
5667          31        984  199.505155             47              3074.19
13507         18        480  369.517241             12              2566.67
25104        109       2784  661.444444             48              2454.13
15469         45       1080  237.405405             41              2300.00
11797        125       3000  802.323232             48              2300.00
25596         10        220   95.438596             30              2100.00
20238        125       2550  703.161616             48              1940.00
15604         10        200   48.550725             25              1900.00
23173        121       2400  540.818182             48              1883.47
7851          18        320  149.000000             25              1677.78
13168        229       3900  376.494949             47              1603.06
2781          44        701  241.278351             48              1493.18
30837         10        156   83.066667             31              1460.00
18431         30        450  217.894737              7              1400.00

In [43]:
# check if any product has more than one selling price with same grammage across different stores
price_variation = (
    df.groupby(['product_name', 'product_grammage'])['item_selling_price']
      .nunique()
      .reset_index(name='price_count')
)

# Keep only products having more than one selling price
price_variation = price_variation[
    price_variation['price_count'] > 1
]

print(price_variation)

                                            product_name product_grammage  \
3      100% Whole Wheat Bread 400GM & Pintola All Nat...          1 Combo
4                                      10X Classic Besan             1 kg
5                                      10X Classic Besan            500 g
6                          10X Classic Chakki Fresh Atta            10 kg
7                          10X Classic Chakki Fresh Atta             5 kg
...                                                  ...              ...
38640  plum coconut milk & peptides shampoo & conditi...          1 combo
38641  plum coconut milk & peptides strength & shine ...          1 combo
38642  plum green tea alcohol free toner and cleansin...          1 combo
38643  plum green tea oil free moisturiser and free t...          1 combo
38657                               uncle john Pistachio           450 ml

       price_count
3                4
4                5
5                4
6                8
7                4
...            ...
38640            3
38641            3
38642            2
38643            2
38657            2

[17796 rows x 3 columns]

In [45]:
# Group by product_name and product_grammage and find price varation statistics
price_analysis = (
    df.groupby(['product_name', 'product_grammage'])['item_selling_price']
      .agg(['count', 'min', 'max', 'mean', 'std'])
      .reset_index()
)

# Calculate price difference and percentage variation
price_analysis['price_diff'] = (
    price_analysis['max'] - price_analysis['min']
)

price_analysis['pct_variation'] = (
    (price_analysis['price_diff'] / price_analysis['mean']) * 100
).round(2)

# Flag products with >20% variation
high_variation = price_analysis[
    price_analysis['pct_variation'] > 20
].sort_values('pct_variation', ascending=False)

print(high_variation)

                                            product_name product_grammage  \
18704                       Liril Cooling Mint Body Wash       250 ml x 2
18708  Liril Lemon And Tea Tree Oil And Liril Cool Mi...          1 combo
5751    CLEAR Premium Drinking Water with Added Minerals       200 ml x 6
7118   Chupa Chups Sour Rockat Assorted Flavour Soft ...         99 g x 4
17848  Lacto Calamine Hyaluronic Acid Face Sheet Mask...           1 pack
...                                                  ...              ...
20152  Mamaearth Moisture Matte Longstay Lipstick wit...              2 g
17067                       Kitkat Premium Delights Rich             50 g
9864                          Dukes Waffy Vanilla Wafers         55 g x 2
34830  The Derma Co Triple Actives Anti-Dandruff Shampoo           200 ml
23519  NOICE Mango Kombucha (200ml) | NOICE Masala Pe...          1 Combo

       count  min   max        mean         std  price_diff  pct_variation
18704     58  280  5600  398.275862  695.016794        5320        1335.76
18708     66  293  2954  341.939394  326.537823        2661         778.21
5751      19   29   323   48.263158   66.590658         294         609.16
7118      23  200  1600  260.869565  291.920180        1400         536.67
17848    158   59   314   62.227848   28.598227         255         409.78
...      ...  ...   ...         ...         ...         ...            ...
20152     58  437   527  449.413793   28.049477          90          20.03
17067    284   77    95   89.926056    1.344334          18          20.02
9864      56   44    54   49.964286    2.303865          10          20.01
34830     19  359   434  374.789474   31.414043          75          20.01
23519     97  114   141  134.958763    4.643359          27          20.01

[4784 rows x 9 columns]

In [47]:
# check if any product has more than one selling price with same grammage on same store
price_variation = (
    df.groupby(['store_name_location', 'product_name', 'product_grammage'])['item_selling_price']
      .agg(['min', 'max', 'nunique', 'count'])
      .reset_index()
)

# Keep only products having more than one unique selling price
price_variation = price_variation[
    price_variation['nunique'] > 1
]

# Calculate price difference
price_variation['price_difference'] = (
    price_variation['max'] - price_variation['min']
)

print(price_variation.sort_values('price_difference', ascending=False))

                                      store_name_location  \
942761  Ultra Dry Cleaners, Railway Road, Jhilmil Indl...
734643  SLV Tea Store, Electronics City Phase 1, Elect...
721691  Rohit Wadewale, Hinjewadi - Kasarsai Rd, Phase...
209198  Casa Basalia, Palem, Tiswadi, North Goa, Goa, ...
445295  Hotel Sea Prince Suites, Opp. Rendezvous Hotel...
...                                                   ...
363537  Fabric Smile, Chikkanagamangala Rd, Silicon To...
364368  Fabric Smile, Chikkanagamangala Rd, Silicon To...
790230  Sarada Stationery Arts And Crafts/xerox, 20, W...
790148  Sarada Stationery Arts And Crafts/xerox, 20, W...
311806  Dogra Path Lab, #16, Model Town, Urban Estate,...

                                             product_name product_grammage  \
942761                         Lindt Napolitains Assorted            350 g
734643                         Mustela Mom'S Treasure Box           1 Pack
721691                         Lindt Napolitains Assorted            350 g
209198  Matrix Mega Smooth Anti-Frizz Combo with Shea ...          1 combo
445295  Matrix Mega Smooth Anti-Frizz Combo with Shea ...          1 combo
...                                                   ...              ...
363537  McVitie’s Digestive Vanilla Cream Sandwich Bis...            100 g
364368  NOICE Masala Coated Peanut (Homestyle Recipe) ...            100 g
790230  Pbl Plum Bodylovin' Hawaiian Rumba Deodorant R...          1 combo
790148  Park Avenue For Her - Luxury Perfume Gift Set ...            80 ml
311806  Parle Hide & Seek Black Bourbon Choco Sandwich...            100 g

         min   max  nunique  count  price_difference
942761  1390  2399        2      4              1009
734643   858  1787        2      2               929
721691  1679  2399        2      4               720
209198   706  1282        2      4               576
445295   706  1282        2      4               576
...      ...   ...      ...    ...               ...
363537    28    29        2      2                 1
364368    55    56        2      2                 1
790230  1036  1037        2      2                 1
790148   500   501        2      2                 1
311806    32    33        2      2                 1

[9684 rows x 8 columns]

***Insights :***
_________________

    * Found price anomalies with high variation of price for the same product with the same grammage unit.
    * Multiple products are there with the same product_name, grammage, store_name, and different offer price.
    * The product_url of such products are too same and not accessible.