**Swiggy Data Analysis**

**1) Business Objective**

To assess and improve the quality, consistency, and completeness of the grocery product listing data by identifying anomalies, inconsistencies, missing information, duplicates, and pricing irregularities across products, categories, stores, and locations, thereby ensuring accurate product information and enhancing the customer shopping experience.

**2) Import Libraries**

In [1]:
import pandas as pd        # For data manipulation
import numpy as np      # For numerical computations
import seaborn as sns  # For advanced visualization
import matplotlib.pyplot as plt # For plotting
import re # For regular expressions

pd.set_option('display.max_colwidth', None)

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

**3) Import Dataset**

In [2]:
df1 = pd.read_csv("/home/user/Downloads/2026-07-21/swiggy_instamart_2026_07_21.csv") 
df2 = pd.read_csv("/home/user/Downloads/2026-07-22/swiggy_instamart_2026_07_22.csv") 
 #Reading Dataset from csv file

**4) Data Insights**

In [3]:
print("INFORMATION ABOUT DATASET")
print("--------------------------------")
df1.info()

INFORMATION ABOUT DATASET
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1283173 entries, 0 to 1283172
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1283173 non-null  object
 1   platform_name            1283173 non-null  object
 2   store_id                 1283173 non-null  int64
 3   store_name_location      1283173 non-null  object
 4   city                     1283173 non-null  object
 5   pin_code                 1283173 non-null  int64
 6   unique_id                1283173 non-null  object
 7   product_id_upc_ean       1283173 non-null  object
 8   department               1283173 non-null  object
 9   category                 1283173 non-null  object
 10  sub_category             1283173 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1283033 non-null  object
 13  product_name             1283173 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         1283173 non-null  object
 16  package_type             0 non-null        float64
 17  net_quantity             0 non-null        float64
 18  variants                 1283173 non-null  object
 19  item_mrp                 1283173 non-null  int64
 20  item_selling_price       1283173 non-null  int64
 21  out_of_stock_flag        1283173 non-null  object
 22  discount_flag            1283173 non-null  object
 23  product_price            1283173 non-null  int64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1283173 non-null  object
 26  promo_offer_price        1283173 non-null  int64
 27  discount_in_percent      1283173 non-null  int64
 28  stock_count              1283173 non-null  int64
 29  product_url              1283173 non-null  object
 30  product_image_urls       1283173 non-null  object
dtypes: float64(5), int64(8), object(18)
memory usage: 303.5+ MB

In [ ]:
print("INFORMATION ABOUT DATASET 1")
print("--------------------------------")
df2.info()

INFORMATION ABOUT DATASET
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1117102 entries, 0 to 1117101
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1117102 non-null  object
 1   platform_name            1117102 non-null  object
 2   store_id                 1117102 non-null  int64
 3   store_name_location      1117102 non-null  object
 4   city                     1117102 non-null  object
 5   pin_code                 1117102 non-null  int64
 6   unique_id                1117102 non-null  object
 7   product_id_upc_ean       1117102 non-null  object
 8   department               1117102 non-null  object
 9   category                 1117102 non-null  object
 10  sub_category             1117102 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1116996 non-null  object
 13  product_name             1117102 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         1117102 non-null  object
 16  package_type             0 non-null        float64
 17  net_quantity             0 non-null        float64
 18  variants                 1117102 non-null  object
 19  item_mrp                 1117102 non-null  int64
 20  item_selling_price       1117102 non-null  int64
 21  out_of_stock_flag        1117102 non-null  object
 22  discount_flag            1117102 non-null  object
 23  product_price            1117102 non-null  int64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1117102 non-null  object
 26  promo_offer_price        1117102 non-null  int64
 27  discount_in_percent      1117102 non-null  int64
 28  stock_count              1117102 non-null  int64
 29  product_url              1117102 non-null  object
 30  product_image_urls       1117102 non-null  object
dtypes: float64(5), int64(8), object(18)
memory usage: 264.2+ MB

In [7]:
print("\nDESCRIPTIVE STATISTICS OF DATASET 2")
print("--------------------------------")
df2.describe().T.round(2)

DESCRIPTIVE STATISTICS OF DATASET 2
--------------------------------

,count,mean,std,min,25%,50%,75%,max
store_id,1117102.0,1.396296e+06,3.059455e+04,1167234.0,1401475.0,1403468.0,1404824.0,1.404890e+06
pin_code,1117102.0,5.223382e+05,1.688239e+05,110067.0,411033.0,560048.0,605009.0,8.420020e+05
product_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
package_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
net_quantity,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
item_mrp,1117102.0,7.494077e+08,8.169253e+10,1.0,109.0,225.0,435.0,8.906005e+12
item_selling_price,1117102.0,7.494076e+08,8.169253e+10,1.0,90.0,185.0,360.0,8.906005e+12
product_price,1117102.0,7.494076e+08,8.169253e+10,1.0,90.0,185.0,360.0,8.906005e+12
unit_price,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_offer_price,1117102.0,7.494076e+08,8.169253e+10,1.0,90.0,185.0,360.0,8.906005e+12
discount_in_percent,1117102.0,1.514000e+01,1.506000e+01,0.0,2.0,11.0,23.0,9.200000e+01
stock_count,1117102.0,1.660000e+00,2.590000e+00,0.0,0.0,1.0,2.0,7.800000e+01

In [8]:
print("\nDATASET1 SHAPE")
print("--------------------------------")
print("The shape =", df1.shape)
num_rows, num_cols = df1.shape
num_features = num_cols - 1
num_data = num_rows * num_cols

# Print the information about the dataset
print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_cols}")
print(f"Number of Features: {num_features}")
print(f"Number of All Data: {num_data}")

DATASET1 SHAPE
--------------------------------
The shape = (1283173, 31)
Number of Rows: 1283173
Number of Columns: 31
Number of Features: 30
Number of All Data: 39778363

In [9]:
print("\nDATASET 2 SHAPE")
print("--------------------------------")
print("The shape =", df2.shape)
num_rows, num_cols = df2.shape
num_features = num_cols - 1
num_data = num_rows * num_cols

# Print the information about the dataset
print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_cols}")
print(f"Number of Features: {num_features}")
print(f"Number of All Data: {num_data}")

DATASET 2 SHAPE
--------------------------------
The shape = (1117102, 31)
Number of Rows: 1117102
Number of Columns: 31
Number of Features: 30
Number of All Data: 34630162

In [10]:
print("COLUMNWISE DATA1 PROFILING")
print("--------------------------------")
summary = []

for col in df1.columns:
    null_count = df1[col].isnull().sum()
    null_percent = round((null_count / len(df1)) * 100, 2)
    distinct_count = df1[col].nunique(dropna=True)

    # Check if all non-null values are unique
    is_unique = "Yes" if df1[col].is_unique and null_count == 0 else "No"


    summary.append({
        'column_name': col,
        'null_count': null_count,
        #'null_percent': null_percent,
        'distinct_count': distinct_count,
        'is_unique': is_unique
    })

summary_df = pd.DataFrame(summary)

# Display the summary
print(summary_df)

COLUMNWISE DATA1 PROFILING
--------------------------------
                column_name  null_count  distinct_count is_unique
0       crawl_date_and_time           0            7961        No
1             platform_name           0               1        No
2                  store_id           0             115        No
3       store_name_location           0             100        No
4                      city           0              41        No
5                  pin_code           0              97        No
6                 unique_id           0         1047842        No
7        product_id_upc_ean           0           32163        No
8                department           0               9        No
9                  category           0              16        No
10             sub_category           0             148        No
11             product_type     1283173               0        No
12               brand_name         140            3066        No
13             product_name           0           32654        No
14      product_description     1283173               0        No
15         product_grammage           0            2075        No
16             package_type     1283173               0        No
17             net_quantity     1283173               0        No
18                 variants           0            8098        No
19                 item_mrp           0            1737        No
20       item_selling_price           0            2151        No
21        out_of_stock_flag           0               2        No
22            discount_flag           0               2        No
23            product_price           0            2151        No
24               unit_price     1283173               0        No
25  promo_offer_description           0              92        No
26        promo_offer_price           0            2151        No
27      discount_in_percent           0              92        No
28              stock_count           0              59        No
29              product_url           0           32163        No
30       product_image_urls           0           35828        No

In [11]:
print("COLUMNWISE DATA2 PROFILING")
print("--------------------------------")
summary = []

for col in df2.columns:
    null_count = df2[col].isnull().sum()
    null_percent = round((null_count / len(df2)) * 100, 2)
    distinct_count = df2[col].nunique(dropna=True)

    # Check if all non-null values are unique
    is_unique = "Yes" if df2[col].is_unique and null_count == 0 else "No"


    summary.append({
        'column_name': col,
        'null_count': null_count,
        #'null_percent': null_percent,
        'distinct_count': distinct_count,
        'is_unique': is_unique
    })

summary_df = pd.DataFrame(summary)

# Display the summary
print(summary_df)

COLUMNWISE DATA2 PROFILING
--------------------------------
                column_name  null_count  distinct_count is_unique
0       crawl_date_and_time           0            5669        No
1             platform_name           0               1        No
2                  store_id           0             116        No
3       store_name_location           0             100        No
4                      city           0              47        No
5                  pin_code           0              96        No
6                 unique_id           0          901907        No
7        product_id_upc_ean           0           30181        No
8                department           0               9        No
9                  category           0              16        No
10             sub_category           0             148        No
11             product_type     1117102               0        No
12               brand_name         106            2676        No
13             product_name           0           30744        No
14      product_description     1117102               0        No
15         product_grammage           0            2048        No
16             package_type     1117102               0        No
17             net_quantity     1117102               0        No
18                 variants           0            8128        No
19                 item_mrp           0            1720        No
20       item_selling_price           0            2111        No
21        out_of_stock_flag           0               2        No
22            discount_flag           0               2        No
23            product_price           0            2111        No
24               unit_price     1117102               0        No
25  promo_offer_description           0              90        No
26        promo_offer_price           0            2111        No
27      discount_in_percent           0              90        No
28              stock_count           0              56        No
29              product_url           0           30181        No
30       product_image_urls           0           33952        No

In [12]:
store_list1 = set(df1['store_id'].unique())
store_list2 = set(df2['store_id'].unique())

print("Stores in first list, not in second list:")
print(list(store_list1 - store_list2))
print(len(list(store_list1 - store_list2)))

print("\nStores in second list, not in first list:")
print(list(store_list2 - store_list1))
print(len(list(store_list2 - store_list1)))

print("\nStores common in both lists:")
print(list(store_list1 & store_list2))
print(len(list(store_list1 & store_list2)))

Stores in first list, not in second list:
[1395725, 1402619, 1402620, 1402623, 1396284, 1314370, 1314371, 1403466, 1388315, 1402449, 1404666, 1401469, 1401470, 1390227, 1404627, 1369819, 1404636, 1400545, 1404642, 1404643, 1404644, 1404645, 1404646, 1400546, 1400552, 1400551, 1404650, 1400550, 1402604, 1400557, 1400553, 1402605, 1404649, 1402607, 1402610, 1404659, 1404651, 1402613, 1400560, 1404660, 1400561, 1400566, 1402618, 1404662, 1404664, 1402621, 886521, 1404671, 1402624, 1404672, 1402626, 1404673, 1404674, 1404676, 1404677, 1404679, 1404680, 1404681, 1390351, 1394449, 1394452, 1394453, 1382165, 1382166, 1382167, 1386265, 1400602, 1349401, 1386267, 1388313, 1388314, 1400603, 1400604, 1400605, 1400606, 1386269, 1386268, 1386270, 1400609, 1400610, 1404707, 1392421, 1402670, 1396467, 1402682, 1397051, 737088, 1404745, 1404748, 1404750, 1404753, 1404754, 1404757, 1404758, 1404759, 1404760, 1404764, 1404765, 1404766, 1388385, 1388386, 1404771, 1404772, 1388388, 1404774, 1388390, 1388387, 1404773, 1385836, 1397630, 1402257, 1401258]
112

Stores in second list, not in first list:
[1399810, 1395729, 1402445, 1400930, 1401475, 1390216, 1403021, 1402070, 1391901, 1403723, 1388389, 1404781, 1382254, 1404783, 1382255, 1404784, 1401714, 1382258, 1404785, 1404786, 1404788, 1404791, 1404787, 1404792, 1404789, 1404795, 1404794, 1404790, 1404796, 1404797, 1404800, 1404798, 1167234, 1404802, 1169284, 1404804, 1404799, 1404808, 1404809, 1404811, 1404816, 1392529, 1386385, 1392531, 1386386, 1402771, 1382290, 1402770, 1402774, 1402775, 1402773, 1402778, 1402780, 1402781, 1402782, 1404824, 1402784, 1404830, 1402786, 1402787, 1402788, 1402789, 1402790, 1404834, 1404835, 1388452, 1388451, 1404838, 1402796, 1404843, 1404841, 1404844, 1402801, 1402802, 1402803, 1396660, 1404849, 1402805, 1402806, 1388453, 1402807, 1402808, 1404850, 1404855, 1404856, 1404858, 1404859, 1404860, 1404864, 1404866, 1404867, 1404868, 1404869, 1404875, 1404876, 1404877, 1404878, 1382349, 1382352, 1382353, 1404881, 1382350, 1386448, 1382351, 1404884, 1386449, 1404886, 1382354, 1404888, 1386450, 1404890, 1394684, 1399806]
113

Stores common in both lists:
[1397057, 1403468, 1396293]
3

In [38]:
df.store_id.unique()
print(len(df.store_id.unique()))
print(len(df.store_name_location.unique()))

122
100

In [13]:
store_mapping = (
    df2.groupby('store_name_location')['store_id']
      .nunique()
      .reset_index(name='unique_store_ids')
      .sort_values('unique_store_ids', ascending=False)
)

multi_store = store_mapping[store_mapping['unique_store_ids'] > 1]

print(multi_store)
print("\nNumber of store_name_location with multiple store_ids:", len(multi_store))

                                                                                                                                                                             store_name_location  \
50                                                                                                                     Mayura Bakery, Bangalore South, Bengaluru Urban, Karnataka, 560076, India
27                                                               Desun (home), 85, Biplabi Ullas Kar Dutta Rd, Baghajatin Place, Birnagar, Baghajatin Colony, Kolkata, West Bengal 700086, India
95                                 Wittmann Battenfeld India Pvt. Ltd, Wittmann Battenfeld 600116, India Pvt. Ltd, 1 & 2 Arumugam Nagar, Chinna Porur, Lakshmi Nagar, Porur, Chennai, Tamil Nadu
93                                Vetic Pet Clinic Manikonda, Plot No. 201 & 210, GF, Near Puppalaguda - Manikonda, Secretariat Colony, Sri Ram Nagar Colony, Hyderabad, Telangana 500089, India
88  Sudarshan Industries, 59, 1st Main Road, Petechannappa Indl Area, 1st Cross Rd, Govindaraja Nagar Ward, Pete Channappa Industrial Estate, Kamakshipalya, Bengaluru, Karnataka, 560079, India
86                               Studio Chhavi, Bellandur, Studio Chhavi, B-1202, Mantri Espana, Near Sakra World Hospital, Kariyammana Agrahara, Bellandur, Bengaluru, Karnataka, 560103, India
71                                                                                       SK.Khan Car Service Point, Agrahara Layout, Yelahanka Taluku, Bengaluru Urban, Karnataka, 560064, India
70                                                                                                                                    SBI, Auto Nagar, Vijayawada, Andhra Pradesh, 520007, India
55                                                     Navin Infra Solution Private Limited, Plot No.444, Scheme No. 78, Part I, Scheme 78 Part 1 Phase 2, Indore, Madhya Pradesh, 453771, India
53                                                                                                                    Mr Plaza, Phase-II, Kanan Vihar, Patia, Bhubaneswar, Odisha, 751031, India
47                              Lakshman Ortho Care - Centre For Ilizarov And Limb Reconstruction, Gowdiyamatam Road, 1st LN, Gunturvari Thota, Kothapeta, Guntur, Andhra Pradesh, 522001, India
38                       Hellokids, 3M-213, 3rd Floor, Govind Narayani Tower, East Of NGEF, Service Road, Outer Ring Rd, East Of NGEF Layout, Kasturi Nagar, Bengaluru, Karnataka, 560043, India
37                                                                                    Gyan Sagar RWA Lane, Gyan Sagar RWA LN, Gyan Khand 1, Indirapuram, Ghaziabad, Uttar Pradesh, 201014, India
34                                                                                                    Golden Sands Commercial Building, 29/7, NIBM Rd, Kondhwa, Pune, Maharashtra, 411048, India
99                                                         Zonah Mars, Sri Sai Apartment Block-B, Sri Sai Apartment, Plot 108, Vittal Rao Nagar, Hitec City, Hyderabad, Telangana, 500081, India
7                                  AISECT Office & Education Centre Hyderabad, Gayathri's Sri Sai Enclave, 3Floor, Musheerabad Main Rd, Musheerabad, Dayara, Hyderabad, Telangana, 500020, India
12                                                                          Artech Courtyard, Paruthippara Ambalamukku Rd, Samithy Nagar, Ambalamukku, Thiruvananthapuram, Kerala, 695005, India
13                                                                            Arul Apartments, Jagannathan St, Ponnangipuram, Tirumurthy Nagar, Nungambakkam, Chennai, Tamil Nadu, 600034, India

    unique_store_ids
50                 2
27                 2
95                 2
93                 2
88                 2
86                 2
71                 2
70                 2
55                 2
53                 2
47                 2
38                 2
37                 2
34                 2
99                 2
7                  2
12                 2
13                 2

Number of store_name_location with multiple store_ids: 18

***Insights :***
_______________
    * Shape of the dataset is 12,42,276 X 31
    * None of the columns is having unique values.
    * 'product_type', 'product_description', 'package_type', 'net_quantity', 'unit_price' are completely null columns.
    * 'brand_name' is a partialy null column with 170 null values.
    * Distinct store_id and store_name_location count are 125 and 100 respectively. While ivestigating, we found that 28 store_name_locations have exactly two store_ids each.

**5) Primary key Analysis**

As per the above informations, no column can be choose as primary key.

In [15]:
# Check if the combination is unique
is_unique = not df2.duplicated(subset=['unique_id', 'store_id','product_id_upc_ean', 'product_name']).any()

print("Is (unique_id, store_id, product_id_upc_ean, product_name) combination unique?", is_unique)

Is (unique_id, store_id, product_id_upc_ean, product_name) combination unique? False

Checked several combinations, but couldn't fix a unique combination

**6) Duplicate Analysis**

In [14]:
print("EXACT DUPLICATE ROWS")
print("--------------------------------")
exact_duplicate_count = df2.duplicated().sum()
print("Exact duplicate rows:", exact_duplicate_count)


print("\nDUPLICATE PRODUCTS IN THE SAME STORE")
print("--------------------------------")
product_duplicate_count = df2.duplicated(
    subset=['store_id', 'product_name']
).sum()

print(f"\nNumber of duplicate products (store_id + product_name): {product_duplicate_count}")


print("\n========== DUPLICATE ANALYSIS SUMMARY ==========")
print(f"Total Rows                  : {len(df2)}")
print(f"Exact Duplicate Rows        : {exact_duplicate_count}")
print(f"Product Duplicate Rows      : {product_duplicate_count}")
print("================================================")

EXACT DUPLICATE ROWS
--------------------------------
Exact duplicate rows: 0

DUPLICATE PRODUCTS IN THE SAME STORE
--------------------------------

Number of duplicate products (store_id + product_name): 272914

========== DUPLICATE ANALYSIS SUMMARY ==========
Total Rows                  : 1117102
Exact Duplicate Rows        : 0
Product Duplicate Rows      : 272914
================================================

In [17]:
# checking for duplicate combinations of store_name_location, product_name, product_grammage, item_selling_price and package_type
dup_products = (
    df2.groupby([
        'store_name_location',
        'product_name',
        'product_grammage',
        'item_selling_price',
        'package_type'
    ])
    .size()
    .reset_index(name='count')
)

dup_products = dup_products[dup_products['count'] > 1]\
                    .sort_values('count', ascending=False)

print("Duplicate combinations:", len(dup_products))
print(dup_products.head(20))

Duplicate combinations: 0
Empty DataFrame
Columns: [store_name_location, product_name, product_grammage, item_selling_price, package_type, count]
Index: []

In [18]:
# Check for products mapped to multiple categories
product_category_check = (
    df2.groupby(['store_name_location', 'product_name','product_grammage', 'product_url','package_type'])['category']
      .nunique()
      .reset_index(name='category_count')
)

# Products mapped to more than one category
inconsistent_products = product_category_check[
    product_category_check['category_count'] > 1
].sort_values('category_count', ascending=False)

print("Number of inconsistent products:",
      len(inconsistent_products))

print(inconsistent_products.head())
print("\nNumber of inconsistent products:", len(inconsistent_products))

Number of inconsistent products: 0
Empty DataFrame
Columns: [store_name_location, product_name, product_grammage, product_url, package_type, category_count]
Index: []

Number of inconsistent products: 0

In [19]:
# Check for products mapped to multiple sub_categories
product_category_check = (
    df2.groupby(['store_name_location', 'product_name','product_grammage', 'product_url','package_type'])['sub_category']
      .nunique()
      .reset_index(name='sub_category_count')
)

# Products mapped to more than one category
inconsistent_products = product_category_check[
    product_category_check['sub_category_count'] > 1
].sort_values('sub_category_count', ascending=False)

print("Number of inconsistent products:",
      len(inconsistent_products))

print(inconsistent_products.head())
print("\nNumber of inconsistent products:", len(inconsistent_products))

Number of inconsistent products: 0
Empty DataFrame
Columns: [store_name_location, product_name, product_grammage, product_url, package_type, sub_category_count]
Index: []

Number of inconsistent products: 0

In [20]:
# Count distinct product names for each unique_id
product_name_counts = (
    df2.groupby("unique_id")["product_name"]
      .nunique(dropna=False)
)

# unique_id values having more than one product_name
duplicate_unique_ids = product_name_counts[product_name_counts > 1].index

print(f"Number of unique_id values with different product_name: {len(duplicate_unique_ids)}")
print(duplicate_unique_ids.tolist())

Number of unique_id values with different product_name: 0
[]

***Insights :***
___________________

    * No exact duplicate columns exists on the dataset, but products duplicates on same stores
    * While deeply investigating, these duplicate products differ by grammage, price or package_type.
    * Also confirmed no products duplicates on same store under different categories.
    * In overall, the dataset is not containing duplicate products visibly.

7) MISSING VALUE ANALYSIS

As mentioned some columns are completely null, that not need to be evaluated. brand_name column is partially null with 170 null values. Lets evaluate that.

In [15]:
# Missing summary by store
print("\nMISSING SUMMARY BY STORE")
print("--------------------------------")
missing_by_store = df2.groupby('store_name_location')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_store)

MISSING SUMMARY BY STORE
--------------------------------
                                                                                                                                              store_name_location  \
0                                                                                1-12-50/14/A, Vinayak Nagar, Pragathi Nagar, Nizamabad, Telangana, 503001, India
1                                                                                            12, Mhalunge - Nande Rd, Mahalunge, Pune, Maharashtra, 411045, India
2                                                        4, Jangal Mangal Rd, Bhandup, Gadhav Naka, Anand Nagar, Bhandup West, Mumbai, Maharashtra, 400078, India
3                                                                        5-13, 5-13-1, Sri Sai Vihar Nagar Colony, Lenin Nagar, Meerpet, Telangana, 500097, India
4                                                                                                 74, Sadananda Rd, Kalighat, Kolkata, West Bengal, 700026, India
..                                                                                                                                                            ...
95  Wittmann Battenfeld India Pvt. Ltd, Wittmann Battenfeld 600116, India Pvt. Ltd, 1 & 2 Arumugam Nagar, Chinna Porur, Lakshmi Nagar, Porur, Chennai, Tamil Nadu
96                                                                You Think, Arni Main Road, Opp: DK Paints, RV Nagar, Virupakshipuram, Tamil Nadu, 632002, India
97                                                                       Zepto Dark Store, Ambika Kundu LN, Baruipara, Ichapur, Howrah, West Bengal 711104, India
98                                         Zepto Store Vijaynagar 1st Stage, 1008, Manchegowdana Koppalu, 1st Stage, Vijayanagar, Mysuru, Karnataka 570030, India
99                          Zonah Mars, Sri Sai Apartment Block-B, Sri Sai Apartment, Plot 108, Vittal Rao Nagar, Hitec City, Hyderabad, Telangana, 500081, India

    brand_name
0     0.000000
1     0.019621
2     0.000000
3     0.000000
4     0.011841
..         ...
95    0.007821
96    0.000000
97    0.000000
98    0.000000
99    0.022442

[100 rows x 2 columns]

In [16]:
# Missing summary by category
print("\nMISSING SUMMARY BY CATEGORY")
print("--------------------------------")
missing_by_category = df2.groupby('category')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_category)

MISSING SUMMARY BY CATEGORY
--------------------------------
                          category  brand_name
0               Atta, Rice and Dal    0.089288
1                        Baby Care    0.000000
2                    Bath and Body    0.001410
3               Biscuits and Cakes    0.000000
4            Cereals and Breakfast    0.000000
5               Chips and Namkeens    0.000000
6                       Chocolates    0.001084
7           Cold Drinks and Juices    0.000000
8            Dairy, Bread and Eggs    0.000000
9                 Feminine Hygiene    0.000000
10                       Hair Care    0.000000
11  Ice Creams and Frozen Desserts    0.018647
12                          Makeup    0.034200
13                     Paan Corner    0.000000
14                        Skincare    0.000000
15                    Sweet Corner    0.000000

In [17]:
print("\nMISSING SUMMARY BY CITY")
print("--------------------------------")

missing_by_city = df2.groupby('city')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_city)

MISSING SUMMARY BY CITY
--------------------------------
                       city  brand_name
0                 Ahmedabad    0.008647
1                     Ajmer    0.000000
2                  Amravati    0.026164
3                 Bangalore    0.013501
4               Bhubaneswar    0.000000
5                   Chennai    0.008552
6                Coimbatore    0.000000
7                   Danapur    0.000000
8                     Delhi    0.005129
9                 Faridabad    0.019238
10                Ghaziabad    0.006645
11                   Guntur    0.008212
12                  Gurgaon    0.022612
13                 Guwahati    0.009604
14                Hyderabad    0.006508
15                   Indore    0.023007
16                   Jaipur    0.032662
17                    Kochi    0.000000
18                  Kolkata    0.006361
19                   Kollam    0.000000
20                Kozhikode    0.013492
21                    Latur    0.009187
22                  Lucknow    0.010883
23                   Mapusa    0.000000
24                   Mumbai    0.015844
25              Muzaffarpur    0.000000
26                   Mysuru    0.000000
27  Nandivaram Guduvancheri    0.008003
28                   Nashik    0.011018
29                 New Town    0.009583
30                Nizamabad    0.000000
31                    Noida    0.002207
32                   Ongole    0.016080
33                    Patna    0.000000
34                 Porvorim    0.045863
35               Puducherry    0.000000
36                     Pune    0.019031
37                 Rudrapur    0.010669
38                  Silchar    0.009223
39                    Surat    0.017297
40               Trivandrum    0.005859
41                 Varanasi    0.000000
42              Vasai Virar    0.025230
43                  Vellore    0.000000
44               Vijayawada    0.000000
45             Vizianagaram    0.000000
46                 Warangal    0.000000

***Insights :***
_______________

    * In store-wise, missing values are almost equally distributed.
    * In category-wise also mising percentage is below 0.2, which is negliglible.
    * In city-wise too, the missing percentage has no hike at any particular city.
    * So in overall missing% doesn't have any direct impact form store/category/city.

**8) Category Hierarchy Consistency**

In [18]:
print("\n DEPARTMENT - CATEGORY CONSISTENCY")
print("--------------------------------")

dept_category_map = df2.groupby('department')['category'].unique()

for dept, cats in dept_category_map.items():
    print("\nDEPARTMENT:", dept)
    print(list(cats))

 DEPARTMENT - CATEGORY CONSISTENCY
--------------------------------

DEPARTMENT: Atta, Rice & Dal
['Atta, Rice and Dal']

DEPARTMENT: Baby Care
['Baby Care']

DEPARTMENT: Bakery & Biscuits
['Biscuits and Cakes']

DEPARTMENT: Beauty & Cosmetics
['Bath and Body', 'Makeup', 'Hair Care']

DEPARTMENT: Cold Drinks & Juices
['Cold Drinks and Juices']

DEPARTMENT: Dairy & Breakfast
['Cereals and Breakfast', 'Dairy, Bread and Eggs']

DEPARTMENT: Munchies
['Chips and Namkeens', 'Cereals and Breakfast']

DEPARTMENT: Personal Care
['Bath and Body', 'Skincare', 'Feminine Hygiene', 'Hair Care', 'Makeup']

DEPARTMENT: Sweet Tooth
['Sweet Corner', 'Chocolates', 'Ice Creams and Frozen Desserts', 'Paan Corner']

In [19]:
print("\n CATEGORY - SUBCATEGORY CONSISTENCY")
print("--------------------------------")

cat_subcat_map = df2.groupby('category')['sub_category'].unique()

for cat, subcats in cat_subcat_map.items():
    print("\nCATEGORY:", cat)
    print(list(subcats))

 CATEGORY - SUBCATEGORY CONSISTENCY
--------------------------------

CATEGORY: Atta, Rice and Dal
['Atta', 'Millets & Daliya', 'Poha & Puffed Rice', 'Toor, Moong and Urad', 'Rajma, Chola and Others', 'Other Flours', 'Rice', 'Besan, Sooji and Maida']

CATEGORY: Baby Care
['Baby Food and Formula', 'Travel Needs & Baby Gears', 'Clothes & Accessories', 'Gifts & More', 'Books and Toys', 'Baby Wipes', 'Baby Bathing', 'Baby Pharma', 'Baby Diapers', 'Feeding and Teething Needs', 'Baby Hygiene', 'Mom Care', 'Baby Oral Care', 'Baby Oil and Talc', 'Baby Cream & Lotions']

CATEGORY: Bath and Body
['Body Lotion & Oils', 'Face Care', 'Fragrance & Talc', 'Mens Perfume', 'Womens Perfume', 'Bath & Beauty gifts', 'Lip care', 'Soaps', 'Roll on', 'Shower gel', 'Bath Accessories', 'Multi groomers', 'Handwash', 'Oral care']

CATEGORY: Biscuits and Cakes
['Baking Ingredients', 'Cream Biscuits', 'Marie & Digestive', 'Cookies', 'Healthy Snacking', 'Rusk', 'Wafers', 'Salted & Plain', 'Gift Boxes', 'Cakes & Pies', 'Gourmet collection', 'Fresh Bakery']

CATEGORY: Cereals and Breakfast
['Batters', 'Ready Mixes', 'Pancake Mixes', 'Seeds and trail Mixes', 'Kids Cereals', 'Muesli & Granola', 'Oats', 'Peanut Butters', 'Energy Bars', 'Flakes']

CATEGORY: Chips and Namkeens
['Bhujia and Namkeens', 'Chips and Crisps', 'Makhana & Dry Fruits', 'Gift Hampers', 'Nachos', 'Popcorn']

CATEGORY: Chocolates
['Shared Packs', 'Milk Chocolates', 'Dark Chocolates', 'Gift Boxes', 'Premium', 'Wafers', 'Kunafa Chocolate', 'Gourmet collection', 'Candies & More', 'Gums & Mint']

CATEGORY: Cold Drinks and Juices
['Coconut Water', 'Cold Coffee', 'Milk Based Drinks', 'Ice Tea & Kombucha', 'Energy Drinks', 'Juices and Fruit Drinks', 'Mango Drinks', 'Fresh Juices', 'Soda and Mixers', 'Soft Drinks', 'Water and Ice Cubes']

CATEGORY: Dairy, Bread and Eggs
['Bread and Buns', 'Butter', 'Cheese', 'Cream and Condensed Milk', 'Curd and Yogurts', 'Milkshakes and More', 'Lassi and Buttermilk', 'Milk', 'Paneer and Tofu', 'Eggs']

CATEGORY: Feminine Hygiene
['Sanitary Pads', 'Period Panties and Liners', 'Hair Removal', 'Menstrual Cups and Tampons', 'Intimate Wipes and Wash', 'Disposal Bags and Cramp Relief']

CATEGORY: Hair Care
['Hair Styling Gels & Creams', 'Hair Oils and Serums', 'Conditioners & Masks', 'Hair Colour', 'Hair Dryers and Stylers', 'Shampoo', 'Premium Brands', 'Combs & Brushes', 'Hair Supplements']

CATEGORY: Ice Creams and Frozen Desserts
['Tubs & Party Packs', 'Cones', 'Sticks', 'Cups', 'Guiltfree', 'Real Fruit', 'Gourmet', 'Kulfi', 'Cakes & Sandwiches', 'Rare Finds', 'Premium', 'Syrups', 'Regional Favorites']

CATEGORY: Makeup
['Eyes', 'Face', 'Tools & Brushes', 'Lips', 'Nails', 'Eye lens']

CATEGORY: Paan Corner
['Gum and Mint', 'Paan and Mouth Fresheners']

CATEGORY: Skincare
['Creams & Moisturizers', 'Masks & Cleansers', 'Face wash and scrubs', 'Serums, Toners', 'Sunscreen', 'Body Lotions', 'Beauty Supplements']

CATEGORY: Sweet Corner
['Cakes and Pies', 'Ladoos', 'Rasgulla', 'Dry Fruit Sweets', 'Chikki', 'Rasmalai', 'Gulkand & Paan', 'Cream Biscuits', 'Gulab Jamun', 'Mysore Pak', 'Pedhas', 'Chocofills', 'Kaju Katli & Barfi', 'Dessert Mixes']

***Insights :***
___________________

    * No specific inconsistencies noticed accross department-category or category-subcategory combinations

**9) Suspicious Value Checking**

In [20]:
def find_suspicious_values(df, column_name):
    suspicious_values = [
        'null', 'none', 'n/a', 'na', 'nil', 'not available',
        'not applicable', '-', '--', '0', ''
    ]
    
    mask = (
        df2[column_name].isna() |
        df2[column_name].astype(str).str.strip().str.lower().isin(suspicious_values) |
        df2[column_name].str.fullmatch(r'\d+') |   # numeric only
        (df2[column_name].str.len() < 3)    # too short
        )
    
    df_suspicious = df2[mask]
    print(f"Number of suspicious values in '{column_name}': {len(df_suspicious)}")
    return df_suspicious[column_name].unique()

print(find_suspicious_values(df2, 'product_name'))
print(find_suspicious_values(df2, 'brand_name'))
print(find_suspicious_values(df2, 'store_name_location'))
print(find_suspicious_values(df2, 'department'))
print(find_suspicious_values(df2, 'category'))
print(find_suspicious_values(df2, 'sub_category'))

Number of suspicious values in 'product_name': 0
[]
Number of suspicious values in 'brand_name': 3073
['RG' '921' nan 'Yu' 'He' 'Go' 'SS' 'Jo' 'P']
Number of suspicious values in 'store_name_location': 0
[]
Number of suspicious values in 'department': 0
[]
Number of suspicious values in 'category': 0
[]
Number of suspicious values in 'sub_category': 0
[]

In [21]:
# Check for numeric columns that should not have negative values or zero

numeric_columns = ['store_id','pin_code','unique_id','product_grammage','net_quantity', 'item_mrp','item_selling_price', 'product_price','promo_offer_price','discount_in_percent','stock_count']

print("Checking price field separators (should use dot '.' not comma ','):\n")

for col in numeric_columns:
    if col in df2.columns:
        # Find rows with comma in price field
        comma_values = df2[df2[col].astype(str).str.contains(',', na=False)]
        invalid_values = df2[pd.to_numeric(df2[col], errors='coerce') <= 0]
        
        if len(comma_values) > 0:
            print(f"❌ {col}: Found {len(comma_values)} values with COMMA separator")
            print(f"   Sample: {comma_values[col].head(3).tolist()}")
        else:
            print(f"✓ {col}: All values use dot (.) or are numeric")
        if len(invalid_values) > 0:
            print(f"❌ {col}: Found {len(invalid_values)} values that are <= 0")
            print(f"   Sample: {invalid_values[col].head(3).tolist()}")
        else:
            print(f"✓ {col}: All values are greater than 0")
    else:
        print(f"⚠ {col}: Column not found in data")
    print()

Checking price field separators (should use dot '.' not comma ','):

✓ store_id: All values use dot (.) or are numeric
✓ store_id: All values are greater than 0

✓ pin_code: All values use dot (.) or are numeric
✓ pin_code: All values are greater than 0

✓ unique_id: All values use dot (.) or are numeric
✓ unique_id: All values are greater than 0

✓ product_grammage: All values use dot (.) or are numeric
✓ product_grammage: All values are greater than 0

✓ net_quantity: All values use dot (.) or are numeric
✓ net_quantity: All values are greater than 0

✓ item_mrp: All values use dot (.) or are numeric
✓ item_mrp: All values are greater than 0

✓ item_selling_price: All values use dot (.) or are numeric
✓ item_selling_price: All values are greater than 0

✓ product_price: All values use dot (.) or are numeric
✓ product_price: All values are greater than 0

✓ promo_offer_price: All values use dot (.) or are numeric
✓ promo_offer_price: All values are greater than 0

✓ discount_in_percent: All values use dot (.) or are numeric
❌ discount_in_percent: Found 244453 values that are <= 0
   Sample: [0, 0, 0]

✓ stock_count: All values use dot (.) or are numeric
❌ stock_count: Found 423226 values that are <= 0
   Sample: [0, 0, 0]

In [26]:
# check for stock_count and out_of_stock_flag consistency
# Convert stock_count to numeric if needed
df2['stock_count'] = pd.to_numeric(
    df2['stock_count'], errors='coerce'
)

# Find rows violating the rule
invalid_rows = df2[
    # (
    #     (df2['stock_count'] == 0) &
    #     (df2['out_of_stock_flag'].str.strip().str.lower() != 'yes')
    # )
    # |
    (
        (df2['stock_count'] > 0) &
        (df2['out_of_stock_flag'].str.strip().str.lower() != 'no')
    )
]

print(f"Number of violating rows: {len(invalid_rows)}")
print(invalid_rows)

Number of violating rows: 403
         crawl_date_and_time     platform_name  store_id  \
400608   2026-07-22 00:48:32  swiggy instamart   1402775
475002   2026-07-22 00:55:49  swiggy instamart   1404841
475003   2026-07-22 00:55:49  swiggy instamart   1404841
475010   2026-07-22 00:55:49  swiggy instamart   1404841
475014   2026-07-22 00:55:49  swiggy instamart   1404841
...                      ...               ...       ...
1041433  2026-07-22 01:44:19  swiggy instamart   1404855
1047989  2026-07-22 01:44:47  swiggy instamart   1404866
1047997  2026-07-22 01:44:47  swiggy instamart   1404866
1102149  2026-07-22 01:50:29  swiggy instamart   1382351
1102156  2026-07-22 01:50:29  swiggy instamart   1382351

                                                                                                                                                    store_name_location  \
400608                                                              Subham Internationals, 172, 4th Main Rd, KKR Garden, Madhavaram, Chennai, Tamil Nadu, 600060, India
475002                                                                                                Car Parking Pahadi Park, Munirka, New Delhi, Delhi, 110067, India
475003                                                                                                Car Parking Pahadi Park, Munirka, New Delhi, Delhi, 110067, India
475010                                                                                                Car Parking Pahadi Park, Munirka, New Delhi, Delhi, 110067, India
475014                                                                                                Car Parking Pahadi Park, Munirka, New Delhi, Delhi, 110067, India
...                                                                                                                                                                 ...
1041433                                                                        5-13, 5-13-1, Sri Sai Vihar Nagar Colony, Lenin Nagar, Meerpet, Telangana, 500097, India
1047989  Vetic Pet Clinic Manikonda, Plot No. 201 & 210, GF, Near Puppalaguda - Manikonda, Secretariat Colony, Sri Ram Nagar Colony, Hyderabad, Telangana 500089, India
1047997  Vetic Pet Clinic Manikonda, Plot No. 201 & 210, GF, Near Puppalaguda - Manikonda, Secretariat Colony, Sri Ram Nagar Colony, Hyderabad, Telangana 500089, India
1102149                 Punjab & Maharashtra CoOperative Bank ATM, Options Performance Shop, Nh66, Lima Vaddo, Socorro, Sangolda, Bardez, North Goa, Goa, 403501, India
1102156                 Punjab & Maharashtra CoOperative Bank ATM, Options Performance Shop, Nh66, Lima Vaddo, Socorro, Sangolda, Bardez, North Goa, Goa, 403501, India

              city  pin_code   unique_id product_id_upc_ean  \
400608     Chennai    600060  2KL314DSXO         W5XDO6XKQ6
475002       Delhi    110067  MJWA30SWQJ         W8GPY6QCBQ
475003       Delhi    110067  QK1X8W2WNT         WTNAC98E56
475010       Delhi    110067  4VX76PYYMV         UM51E8AJ3U
475014       Delhi    110067  N88XQZ0JYN         TX3LZ9OWGB
...            ...       ...         ...                ...
1041433  Hyderabad    500097  7F9NVYTPN7         FU5PS80MF6
1047989  Hyderabad    500089  HIZU2SOG4T         FU5PS80MF6
1047997  Hyderabad    500089  61KH0DWCGX         078GD47ETT
1102149   Porvorim    403501  1X7FYA0UDR         0YSSY1LH3L
1102156   Porvorim    403501  XDPMU2BKGN         0593Y4FHDV

                   department                        category  ...  \
400608            Sweet Tooth  Ice Creams and Frozen Desserts  ...
475002   Cold Drinks & Juices          Cold Drinks and Juices  ...
475003   Cold Drinks & Juices          Cold Drinks and Juices  ...
475010   Cold Drinks & Juices          Cold Drinks and Juices  ...
475014   Cold Drinks & Juices          Cold Drinks and Juices  ...
...                       ...                             ...  ...
1041433  Cold Drinks & Juices          Cold Drinks and Juices  ...
1047989  Cold Drinks & Juices          Cold Drinks and Juices  ...
1047997  Cold Drinks & Juices          Cold Drinks and Juices  ...
1102149     Dairy & Breakfast           Cereals and Breakfast  ...
1102156     Dairy & Breakfast           Cereals and Breakfast  ...

        out_of_stock_flag  discount_flag product_price unit_price  \
400608                Yes             No            60        NaN
475002                Yes            Yes            76        NaN
475003                Yes            Yes           137        NaN
475010                Yes            Yes            18        NaN
475014                Yes            Yes           196        NaN
...                   ...            ...           ...        ...
1041433               Yes            Yes           112        NaN
1047989               Yes            Yes           106        NaN
1047997               Yes            Yes            89        NaN
1102149               Yes            Yes           281        NaN
1102156               Yes            Yes           561        NaN

         promo_offer_description promo_offer_price  discount_in_percent  \
400608                  No offer                60                    0
475002                   45% OFF                76                   45
475003                   14% OFF               137                   14
475010                   10% OFF                18                   10
475014                    9% OFF               196                    9
...                          ...               ...                  ...
1041433                  37% OFF               112                   37
1047989                  36% OFF               106                   36
1047997                  47% OFF                89                   47
1102149                  11% OFF               281                   11
1102156                  12% OFF               561                   12

         stock_count                                       product_url  \
400608            20  https://www.swiggy.com/instamart/item/W5XDO6XKQ6
475002             2  https://www.swiggy.com/instamart/item/W8GPY6QCBQ
475003             3  https://www.swiggy.com/instamart/item/WTNAC98E56
475010             2  https://www.swiggy.com/instamart/item/UM51E8AJ3U
475014             1  https://www.swiggy.com/instamart/item/TX3LZ9OWGB
...              ...                                               ...
1041433            2  https://www.swiggy.com/instamart/item/FU5PS80MF6
1047989            3  https://www.swiggy.com/instamart/item/FU5PS80MF6
1047997            6  https://www.swiggy.com/instamart/item/078GD47ETT
1102149            1  https://www.swiggy.com/instamart/item/0YSSY1LH3L
1102156            1  https://www.swiggy.com/instamart/item/0593Y4FHDV

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         product_image_urls
400608                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/3/11/5932ba52-226f-49aa-9604-6d4462bc5771_7630_1.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/3/11/95fb11bd-5e85-4fa9-b7f6-daf60d32d3ee_7630_2.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/3/11/70299949-725c-4b38-b4d1-4bf6326bcdb7_7630_3.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/3/11/6f108f77-a9b1-4bcf-84d5-88e00ac5f1aa_7623_5.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/3/11/53d2baa9-ff45-466c-9d04-22dedbfa4c9a_7630_5.png
475002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2025/5/19/fce53fda-f5dd-4209-9ac9-4b3263c1351d_1425_1.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/f477b7ee06283028f913192d28f1afc4, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/14e0aa6f3df4bfd73ade39caa5c75957, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/db38ee279ab536241883497af60bda6e, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/4b00761fd9bb1d8858eaeead9edcf8be, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/dcb721890d927ecef0c8ba0fde852c2f
475003                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/1/20/36892646-0c7a-437b-abc1-3d14f1d1bd83_18629_1.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/1/20/16d77899-5a1b-490c-aaaa-c2cda1f6a696_18629_2.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/1/20/3aba281f-6494-4492-ae0e-2bb79d6ace23_18629_3.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/1/20/f9d1ca87-698c-4323-b663-68d9db700578_18629_4.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/1/20/f43e2ea6-46ca-4a5d-a819-d2d81055693e_18629_5.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/CIW/2026/1/20/9a31b364-750b-4f96-9a60-c886b3f14971_18629_6.png
475010                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/NI_CATALOG/IMAGES/ciw/2026/2/11/9e15a0d7-a672-49cd-8a6b-e030c62e9ad7_3H4A364GBA_MN_11022026.png, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/3198d3cfeb3c83ab04440db59bab8ade, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/b2995ffb7fdce054d979a38da10bbc52, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/a055271b6d7d16b7054f6ece6d1686fb, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/6ce546307c26916787913146c6ce4290, https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/bofrqotkav45lcitewrr

***Insights :***
____________

    * Suspicious values noticed on brand_name column.
    * Checked website to confirm whether these brand_names really exists or not.
    * Most of them really exists, but urls of some brands are not able to access.
    * Complete urls on brand_name 'RG' and 'C4' and some urls on other brands are not accessible, which is a critical issue.

**10) Price Anomalies**

In [27]:
def check_negative_and_zero(df, column):
    """
    Returns rows where the given column has:
    - negative values (< 0)
    - zero values (== 0)
    """

    # Ensure numeric (safe for real-world messy data)
    df2[column] = pd.to_numeric(df2[column], errors='coerce')

    negative_values = df2[df2[column] < 0]
    zero_values = df2[df2[column] == 0]

    return {
        "negative_values": negative_values[['unique_id', column]],
        "zero_values": zero_values[['unique_id', column]]
    }

print("\nItem MRP:")
print(check_negative_and_zero(df2, 'item_mrp'))
print("\nItem Selling Price:")
print(check_negative_and_zero(df2, 'item_selling_price'))
print("\nProduct Price:")
print(check_negative_and_zero(df2, 'product_price'))
print("\nPromo Offer Price:")
print(check_negative_and_zero(df2, 'promo_offer_price'))

Item MRP:
{'negative_values': Empty DataFrame
Columns: [unique_id, item_mrp]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, item_mrp]
Index: []}

Item Selling Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, item_selling_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, item_selling_price]
Index: []}

Product Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, product_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, product_price]
Index: []}

Promo Offer Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, promo_offer_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, promo_offer_price]
Index: []}

In [28]:
# check if item_selling_price is greater than item_mrp
df2[df2['item_selling_price'] > df2['item_mrp']][['unique_id', 'item_selling_price', 'item_mrp']]

         unique_id  item_selling_price  item_mrp
136478  OZT433P2SA                  37        30

In [29]:
# check if discount_in_percent is greater than 0 and item_selling_price is greater than or equal to item_mrp
df2[
    (df2['discount_in_percent'] > 0) &
    (df2['item_selling_price'] >= df2['item_mrp'])
][['unique_id', 'item_selling_price', 'item_mrp', 'discount_in_percent']]

         unique_id  item_selling_price  item_mrp  discount_in_percent
136478  OZT433P2SA                  37        30                    1

In [30]:
# check if promo_offer_description is not null and promo_offer_price is null
df2[
    (df2['promo_offer_description'].notnull()) &

    (df2['promo_offer_price'].isnull())][['unique_id', 'promo_offer_description', 'promo_offer_price']]

Empty DataFrame
Columns: [unique_id, promo_offer_description, promo_offer_price]
Index: []

In [31]:
# check if promo_offer_price is not null and promo_offer_price is not equal to item_selling_price
df2[
    (df2['promo_offer_price'].notnull()) &
    (df2['promo_offer_price'] != df2['item_selling_price'])
][['unique_id', 'promo_offer_description', 'promo_offer_price', 'item_selling_price']]

Empty DataFrame
Columns: [unique_id, promo_offer_description, promo_offer_price, item_selling_price]
Index: []

In [34]:
# check if out_of_stock_flag is True and stock_count is greater than 0
df2[
    (df2['out_of_stock_flag'] == True) &
    (df2['stock_count'] > 0)
][['unique_id', 'store_id', 'product_id_upc_ean']]

Empty DataFrame
Columns: [unique_id, store_id, product_id_upc_ean]
Index: []

***Insights :***
____________

    * No specific anomalies found on price related columns
    * All such columns are greater than 0.
    * selling price and mrp are equal.
    * selling price is always less than mrp if discount percentage exists.
    * if promo offer description exists, promo offer price also exists.
    * If out of stock flag true, stock count is zero.

**11) URL Checking**

In [35]:
total_records = len(df2)
missing_urls = df2['product_url'].isnull().sum()
unique_urls = df2['product_url'].nunique(dropna=True)
duplicate_urls = df2['product_url'].duplicated().sum()

print("URL ANALYSIS SUMMARY")
print("-" * 40)
print(f"Total records           : {total_records}")
print(f"Missing URLs            : {missing_urls}")
print(f"Unique URLs             : {unique_urls}")
print(f"Duplicate URLs          : {duplicate_urls}")
print(f"Uniqueness %            : {(unique_urls/total_records)*100:.2f}%")

URL ANALYSIS SUMMARY
----------------------------------------
Total records           : 1117102
Missing URLs            : 0
Unique URLs             : 30181
Duplicate URLs          : 1086921
Uniqueness %            : 2.70%

In [36]:
# Duplicate URL Records
# ----------------------------
duplicate_url_df = df2[
    df2['product_url'].duplicated(keep=False)
].sort_values('product_url')

print("\nDuplicate URL Records:")
print(duplicate_url_df[['unique_id', 'product_name', 'product_url']].head())

Duplicate URL Records:
         unique_id  \
712000  FK7LVHLHPB
259283  DYD371N5A1
316358  N4GIYDI3AX
758378  1BVWF2OJBV
537337  7DCXFZZONP

                                                                                  product_name  \
712000  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
259283  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
316358  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
758378  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
537337  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying

                                             product_url
712000  https://www.swiggy.com/instamart/item/0009OYBIMZ
259283  https://www.swiggy.com/instamart/item/0009OYBIMZ
316358  https://www.swiggy.com/instamart/item/0009OYBIMZ
758378  https://www.swiggy.com/instamart/item/0009OYBIMZ
537337  https://www.swiggy.com/instamart/item/0009OYBIMZ

In [37]:
# ----------------------------
# URL Format Validation
# ----------------------------

# Regex for HTTP/HTTPS URLs
url_pattern = re.compile(
    r'^(https?://)'               # http:// or https://
    r'([\w.-]+)'                  # domain
    r'(\.[a-zA-Z]{2,})'           # TLD
    r'([/\w .?%&=+-]*)?$'         # path/query
)

invalid_urls = df2[
    df2['product_url'].notnull() &
    ~df2['product_url'].astype(str).str.match(url_pattern)
]

print("\nInvalid URL Format Count:", len(invalid_urls))

print("\nSample Invalid URLs:")
print(
    invalid_urls[
        ['unique_id', 'product_name', 'product_url']
    ].head(10)
)

Invalid URL Format Count: 0

Sample Invalid URLs:
Empty DataFrame
Columns: [unique_id, product_name, product_url]
Index: []

In [42]:
# ----------------------------
# URLs without http/https
# ----------------------------
missing_protocol = df2[
    df2['product_url'].notnull() &
    ~df2['product_url'].astype(str).str.startswith(('http://', 'https://'))
]

print("\nURLs missing protocol (http/https):", len(missing_protocol))

print(
    missing_protocol[
        ['unique_id', 'product_name', 'product_url']
    ].head()
)

URLs missing protocol (http/https): 0
Empty DataFrame
Columns: [unique_id, product_name, product_url]
Index: []

***Insights***
___________
* Format and pattern of urls are correct
* But 1210545 duplicate urls present on the dataset.
* However these duplcates have different store location and different price range.

**12) City, Store, Pincode Analysis**

In [38]:
# Missing percentage by city

missing_by_city = (
    df2.groupby('city')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by city

df2['out_of_stock_flag_num'] = (
    df2['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_city = (
    df2.groupby('city')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by city

discount_by_city = (
    df2.groupby('city')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by city

products_by_city = (
    df2.groupby('city')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
city_analysis = (
    missing_by_city
    .merge(stockout_by_city, on='city', how='outer')
    .merge(discount_by_city, on='city', how='outer')
    .merge(products_by_city, on='city', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nCITY ANALYSIS SUMMARY")
print("--------------------------------")
print(city_analysis)

/tmp/ipykernel_12288/382486877.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

CITY ANALYSIS SUMMARY
--------------------------------
                       city  missing_perc  stockout_perc  avg_discount_perc  \
34                 Porvorim     16.130512      39.524858          15.052559
16                   Jaipur     16.130086      52.270005          15.350898
2                  Amravati     16.129876      31.275074          15.268882
42              Vasai Virar     16.129846      30.440267          15.401791
15                   Indore     16.129774      49.649143          14.517083
12                  Gurgaon     16.129762      42.317694          15.086037
9                 Faridabad     16.129653      45.748365          15.343305
36                     Pune     16.129646      44.943012          15.061238
39                    Surat     16.129590      43.042463          15.481968
32                   Ongole     16.129551      25.856247          15.514123
24                   Mumbai     16.129543      42.841525          14.981383
3                 Bangalore     16.129468      34.026954          14.711649
20                Kozhikode     16.129467      49.703184          14.584458
28                   Nashik     16.129388      45.019833          14.545064
22                  Lucknow     16.129383      40.570247          15.775819
37                 Rudrapur     16.129376      43.465273          15.394217
13                 Guwahati     16.129342      31.014695          16.285512
29                 New Town     16.129341      34.020125          15.372209
38                  Silchar     16.129330      61.916621          15.412839
21                    Latur     16.129329      36.637575          15.362150
0                 Ahmedabad     16.129311      46.467791          15.471077
5                   Chennai     16.129308      38.561533          14.727358
11                   Guntur     16.129297      37.004188          15.116367
27  Nandivaram Guduvancheri     16.129290      22.847311          15.231434
10                Ghaziabad     16.129247      37.933555          14.991296
14                Hyderabad     16.129242      32.770273          15.068060
18                  Kolkata     16.129237      43.786047          14.891349
40               Trivandrum     16.129221      51.868995          15.280584
8                     Delhi     16.129198      30.331316          15.323931
31                    Noida     16.129103      25.789009          15.746038
45             Vizianagaram     16.129032      29.896708          15.535283
35               Puducherry     16.129032      48.706552          15.263579
43                  Vellore     16.129032      54.634754          14.772136
44               Vijayawada     16.129032      32.197220          15.944739
41                 Varanasi     16.129032      51.148175          16.485255
23                   Mapusa     16.129032      28.668204          15.887504
33                    Patna     16.129032      26.248203          16.192969
30                Nizamabad     16.129032      57.662549          13.037193
26                   Mysuru     16.129032      49.092379          15.499890
25              Muzaffarpur     16.129032      44.827202          12.323634
1                     Ajmer     16.129032      29.389166          15.857184
19                   Kollam     16.129032      58.387287          15.103296
17                    Kochi     16.129032      44.298425          15.801404
7                   Danapur     16.129032      20.645921          15.578844
6                Coimbatore     16.129032      48.226640          16.059637
4               Bhubaneswar     16.129032      47.919118          15.752132
46                 Warangal     16.129032      18.114739          15.778546

    product_count
34           8753
16           7385
2            9303
42           6328
15           6922
12           7128
9            8331
36          38269
39           9386
32          14998
24          51085
3          138439
20           5850
28           7189
22           7414
37           7612
13          33734
29           8211
38           8849
21           8707
0            9360
5           85703
11           9882
27           9960
10          12438
14          86377
18          76176
40          13617
8           15559
31          36463
45           8383
35           8926
43           5475
44           9963
41           6609
23          11426
33          15953
30           5999
26          11016
25           7194
1            8404
19           8206
17           9991
7            6052
6            9070
4           11155
46           8657

In [39]:
# Missing percentage by store

missing_by_store = (
    df2.groupby('store_name_location')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by store

df2['out_of_stock_flag_num'] = (
    df2['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_store = (
    df2.groupby('store_name_location')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by store

discount_by_store = (
    df2.groupby('store_name_location')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by store

products_by_store = (
    df2.groupby('store_name_location')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
store_analysis = (
    missing_by_store
    .merge(stockout_by_store, on='store_name_location', how='outer')
    .merge(discount_by_store, on='store_name_location', how='outer')
    .merge(products_by_store, on='store_name_location', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nSTORE ANALYSIS SUMMARY")
print("--------------------------------")
print(store_analysis)

/tmp/ipykernel_12288/2116988899.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

STORE ANALYSIS SUMMARY
--------------------------------
                                                                                                                                                        store_name_location  \
63                          Punjab & Maharashtra CoOperative Bank ATM, Options Performance Shop, Nh66, Lima Vaddo, Socorro, Sangolda, Bardez, North Goa, Goa, 403501, India
49                                                                          Man Opus, Western Express Hwy, MIDC, Mira Road East, Mira Bhayandar, Maharashtra, 401104, India
86          Studio Chhavi, Bellandur, Studio Chhavi, B-1202, Mantri Espana, Near Sakra World Hospital, Kariyammana Agrahara, Bellandur, Bengaluru, Karnataka, 560103, India
14                            Astra The Shooter's Hub (air Rifle & Pistol Shooting Range), C 82a, Star Mansion, Shyam Marg, Shastri Nagar, Jaipur, Rajasthan, 302016, India
21                         Bren Avalon, Chinnapanahalli Main Rd, Near BigBasket Warehouse, Ferns Paradise, Doddanekundi, Doddanekkundi, Bengaluru, Karnataka, 560048, India
..                                                                                                                                                                      ...
38  Hellokids, 3M-213, 3rd Floor, Govind Narayani Tower, East Of NGEF, Service Road, Outer Ring Rd, East Of NGEF Layout, Kasturi Nagar, Bengaluru, Karnataka, 560043, India
73                                                                      Sai Jharokha, Sant Gadge Maharaj Marg, Ashok Van, Borivali East, Mumbai, Maharashtra, 400066, India
32                                                          Garg Enclave, 238, Rd Number 7, Sri Shyam Nagar, Telecom Nagar, Gachibowli, Hyderabad, Telangana, 500032, India
31                                         Gajas Sammand Apartment, 542a, VO Chidambaranaar St, M.K Chavadi, Indira Nagar, Thoraipakkam, Chennai, Tamil Nadu, 600096, India
0                                                                                          1-12-50/14/A, Vinayak Nagar, Pragathi Nagar, Nizamabad, Telangana, 503001, India

    missing_perc  stockout_perc  avg_discount_perc  product_count
63     15.626433      39.524858          15.052559           8753
49     15.626267      34.873541          15.396158           9858
86     15.626198      40.279163          14.290053          10568
14     15.626021      52.270005          15.350898           7385
21     15.625967      45.962252          14.252553          10516
..           ...            ...                ...            ...
38     15.625000      34.848217          14.850424           9090
73     15.625000      47.404444          15.312000           9063
32     15.625000      34.796693          15.607195           9372
31     15.625000      32.424399          15.152623          12611
0      15.625000      57.662549          13.037193           5999

[100 rows x 5 columns]

In [40]:
# Missing percentage by pincode

missing_by_pincode = (
    df2.groupby('pin_code')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by pincode

df2['out_of_stock_flag_num'] = (
    df2['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_pincode = (
    df2.groupby('pin_code')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by pincode

discount_by_pincode = (
    df2.groupby('pin_code')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by pincode

products_by_pincode = (
    df2.groupby('pin_code')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
pincode_analysis = (
    missing_by_pincode
    .merge(stockout_by_pincode, on='pin_code', how='outer')
    .merge(discount_by_pincode, on='pin_code', how='outer')
    .merge(products_by_pincode, on='pin_code', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nPINCODE ANALYSIS SUMMARY")
print("--------------------------------")
print(pincode_analysis)

/tmp/ipykernel_12288/1523724332.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

PINCODE ANALYSIS SUMMARY
--------------------------------
    pin_code  missing_perc  stockout_perc  avg_discount_perc  product_count
21    403501     15.626433      39.524858          15.052559           8753
19    401104     15.626267      34.873541          15.396158           9858
55    560103     15.626198      40.279163          14.290053          10568
11    302016     15.626021      52.270005          15.350898           7385
49    560048     15.625967      45.962252          14.252553          10516
..       ...           ...            ...                ...            ...
1     110086     15.625000      18.578413          15.080293           8470
57    562123     15.625000      19.609424          15.359043           8851
58    570030     15.625000      49.092379          15.499890          11016
62    600096     15.625000      32.424399          15.152623          12611
95    842002     15.625000      44.827202          12.323634           7194

[96 rows x 5 columns]

***Insights :***
__________________

    * missing percentage is almost equally distributed over all dimensions
    * stockout percentage and product count has significant hike based on some cities, stores, pincodes etc.
    * However discount_percentage is also have almost equal distribution over different dimensions

**13) High Price Variations**

In [41]:
# Price Variation Analysis
price_variation = (
    df2.groupby('product_id_upc_ean')
      .agg(
          product_name=('product_name', 'first'),
          min_price=('item_selling_price', 'min'),
          max_price=('item_selling_price', 'max'),
          mean_price=('item_selling_price', 'mean'),
          num_locations=('city', 'nunique')
      )
      .reset_index()
)

# Calculate percentage variation
price_variation['price_variation_pct'] = (
    (price_variation['max_price'] - price_variation['min_price'])
    / price_variation['min_price'] * 100
).round(2)

# Flag products having >30% variation
high_variation = price_variation[
    price_variation['price_variation_pct'] > 30
].sort_values('price_variation_pct', ascending=False)

print(high_variation.head(20))

      product_id_upc_ean  \
2204          2IEBCYP5KL
12001         E03H65CYWL
11967         DYU1NS9OBF
26246         V5U7GYM8HO
16967         JUIGCVJ7BM
27745         X1UP6TZ2CH
5291          63FRSPU0EC
17641         KPJOSOMTRR
12658         ESWAQTN109
14473         GY12SME90J
11054         CWA1JGHGHP
21785         PKGH8JLDJ3
23596         RUR8E3DZ69
18969         M9QXZYJMLV
21073         OOELHN2B5V
14604         H3O2WU1A10
18852         M4QUUOVVI2
28083         XGTV05YZDN
1345          1J9EXQ3KN5
20556         O3NFOG8UCY

                                                   product_name  min_price  \
2204                                   TGF Whipped Cream Powder         60
12001          Delfrez Suguna Nourish - Vitamins & Minerals Egg          2
11967                                        Nutella B ready T1          1
26246              RENEE Pink False Stick On Nails (Pack of 24)         11
16967                         True Elements Panchmeva Trail Mix         20
27745          CLEAR Premium Drinking Water with Added Minerals          5
5291             NOICE Natural Coconut Water (No Preservatives)         31
17641                     Aashirvaad Atta Sugar Release Control         40
12658                    Himalayan Natural Mineral Water Bottle         18
14473  NOICE Coconut Water With Malai Chunks (No Preservatives)         45
11054            Red Bull The Yellow Edition Energy Drink 250ml        124
21785                Red Bull Energy Drink - Sugar Free, 250 ml        120
23596                             Red Bull Energy Drink, 250 ml        125
18969            Red Bull Energy Drink - The Red Edition 250 ml        125
21073                              Bisleri Mineral Water Bottle          5
14604                                          POLO Breath Mint         10
18852                        Kwality Wall's Aamras Sorbet Stick         21
28083              Kitchen Gems HMT Kolam Standard Rice (Steam)         58
1345                                 Havmor Dark Chocolate Cone         28
20556                           Grameen Stick Kulfi Kesar Pista         54

       max_price   mean_price  num_locations  price_variation_pct
2204       24861  1016.192308             21             41335.00
12001        176    94.740741              7              8700.00
11967         78    41.931034             14              7700.00
26246        615   593.428571             20              5490.91
16967       1050  1029.803922             32              5150.00
27745        176    24.716418             30              3420.00
5291         984   187.901554             44              3074.19
17641       1080   628.112676             33              2600.00
12658        480   428.516129             12              2566.67
14473       1080   198.106509             36              2300.00
11054       2799   845.446809             44              2157.26
21785       2640   551.910000             47              2100.00
23596       2700   525.990000             47              2060.00
18969       2700   630.250000             47              2060.00
21073        100    38.637931             28              1900.00
14604        200    39.759036             23              1900.00
18852        420    47.569767             43              1900.00
28083       1080   302.388889             34              1762.07
1345         500    95.010989             45              1685.71
20556        960   136.886598             46              1677.78

In [42]:
# check if any product has more than one selling price with same grammage across different stores
price_variation = (
    df2.groupby(['product_name', 'product_grammage'])['item_selling_price']
      .nunique()
      .reset_index(name='price_count')
)

# Keep only products having more than one selling price
price_variation = price_variation[
    price_variation['price_count'] > 1
]

print(price_variation)

                                                                          product_name  \
1                                                                    10X Classic Besan
2                                                        10X Classic Chakki Fresh Atta
3                                                        10X Classic Chakki Fresh Atta
4                                                                    10X Classic Dalia
5                                                                    10X Classic Maida
...                                                                                ...
36977  plum coconut milk & peptides strength & shine shampoo, conditioner & hair serum
36978                        plum green tea alcohol free toner and cleansing face wash
36979         plum green tea oil free moisturiser and free toner & cleansing face wash
36982                                              sofy Antibacteria XL+ Sanitary Pads
36992                                                             uncle john Pistachio

      product_grammage  price_count
1                 1 kg            4
2                10 kg            6
3                 5 kg            4
4                500 g            4
5                500 g            2
...                ...          ...
36977          1 combo            3
36978          1 combo            4
36979          1 combo            4
36982        44 pieces            2
36992           450 ml            2

[17092 rows x 3 columns]

In [43]:
# Group by product_name and product_grammage and find price varation statistics
price_analysis = (
    df2.groupby(['product_name', 'product_grammage'])['item_selling_price']
      .agg(['count', 'min', 'max', 'mean', 'std'])
      .reset_index()
)

# Calculate price difference and percentage variation
price_analysis['price_diff'] = (
    price_analysis['max'] - price_analysis['min']
)

price_analysis['pct_variation'] = (
    (price_analysis['price_diff'] / price_analysis['mean']) * 100
).round(2)

# Flag products with >20% variation
high_variation = price_analysis[
    price_analysis['pct_variation'] > 20
].sort_values('pct_variation', ascending=False)

print(high_variation)

                                                                           product_name  \
32534                                                          TGF Whipped Cream Powder
21319                                      Mother Sparsh Milky Soft Baby Lotion - 400ml
1957                                                             Amul Shrikhand Elaichi
3875                                                Berry Fusion - Multi-Fruit Fun Pack
25117                                                              Paper Boat Aam Papad
...                                                                                 ...
17906                              Loacker Quadratini Chocolate Bite Size Wafer Cookies
31215                                                            Stayfree Secure Nights
6032                        Cakezone Choco Fudge Brownie- Zero Palm Oil (Freshly Baked)
25017  Pampers Taped Diaper (S, 3-8 Kg, 92 Pieces, Cottony Softness, 100% Wetness Lock)
28494         Rishta Multigrain Idli Dosa Batter & Rishta Delicious All Porpose Chutney

      product_grammage  count   min    max         mean          std  \
32534             50 g     25    60  24861  1052.040000  4960.200000
21319           400 ml     95   341   3457   374.200000   319.677151
1957             500 g     65   102   1024   122.000000   113.707822
3875              42 g     32    30    305    38.593750    48.613591
25117             90 g     31    80    833   107.096774   134.723013
...                ...    ...   ...    ...          ...          ...
17906            125 g    192   224    269   224.703125     5.595472
31215    40 pieces x 2     27   354    441   434.444444    20.370290
6032              40 g     92    19     23    19.978261     1.504413
25017        92 Pieces     95  1255   1524  1343.536842    49.714250
28494          1 Combo     25   225    273   239.840000    15.134618

       price_diff  pct_variation
32534       24801        2357.42
21319        3116         832.71
1957          922         755.74
3875          275         712.55
25117         753         703.10
...           ...            ...
17906          45          20.03
31215          87          20.03
6032            4          20.02
25017         269          20.02
28494          48          20.01

[4607 rows x 9 columns]

In [44]:
# check if any product has more than one selling price with same grammage on same store
price_variation = (
    df2.groupby(['store_id', 'product_name', 'product_grammage'])['item_selling_price']
      .agg(['min', 'max', 'nunique', 'count'])
      .reset_index()
)

# Keep only products having more than one unique selling price
price_variation = price_variation[
    price_variation['nunique'] > 1
]

# Calculate price difference
price_variation['price_difference'] = (
    price_variation['max'] - price_variation['min']
)

print(price_variation.sort_values('price_difference', ascending=False))

        store_id  \
242470   1402771
306958   1402782
290291   1402780
155511   1388451
135314   1386449
...          ...
761505   1404856
761506   1404856
811123   1404868
243784   1402771
846112   1404877

                                                                                                               product_name  \
242470                                          Matrix Mega Smooth Anti-Frizz Combo with Shea butter - 4-Days Frizz Control
306958                                          Matrix Mega Smooth Anti-Frizz Combo with Shea butter - 4-Days Frizz Control
290291                                          Matrix Mega Smooth Anti-Frizz Combo with Shea butter - 4-Days Frizz Control
155511                                          Matrix Mega Smooth Anti-Frizz Combo with Shea butter - 4-Days Frizz Control
135314                                          Matrix Mega Smooth Anti-Frizz Combo with Shea butter - 4-Days Frizz Control
...                                                                                                                     ...
761505                                                             plum 10% niacinamide face serum and 3% niacinamide toner
761506                                            plum 10% niacinamide face serum and 3% niacinamide toner & face sunscreen
811123                                                             plum 10% niacinamide face serum and 3% niacinamide toner
243784  Paper Boat Zero Calorie Indian Tonic Water, Sugar Free Cocktail Mixer & Paper Boat Swing Tender Coconut Water Drink
846112                                                             plum 10% niacinamide face serum and 3% niacinamide toner

       product_grammage   min   max  nunique  count  price_difference
242470          1 combo   706  1261        2      4               555
306958          1 combo   706  1261        2      4               555
290291          1 combo   706  1261        2      4               555
155511          1 combo   706  1247        2      4               541
135314          1 combo   721  1261        2      4               540
...                 ...   ...   ...      ...    ...               ...
761505          1 combo   960   961        2      3                 1
761506          1 combo  1319  1320        2      3                 1
811123          1 combo   960   961        2      3                 1
243784          1 Combo   130   131        2      2                 1
846112          1 combo   960   961        2      3                 1

[581 rows x 8 columns]

***Insights :***
_________________

    * Found price anomalies with high variation of price for the same product with the same grammage unit.
    * Multiple products are there with the same product_name, grammage, store_name, and different offer price.
    * The product_url of such products are too same and not accessible.

In [45]:
categories1 = set(df1['category'].dropna().unique())
categories2 = set(df2['category'].dropna().unique())

print("Categories only in df1:")
print(sorted(categories1 - categories2))

print("\nCategories only in df2:")
print(sorted(categories2 - categories1))

print("\nCommon categories:")
print(sorted(categories1 & categories2))

print("\nAre the category values identical?")
print(categories1 == categories2)

Categories only in df1:
[]

Categories only in df2:
[]

Common categories:
['Atta, Rice and Dal', 'Baby Care', 'Bath and Body', 'Biscuits and Cakes', 'Cereals and Breakfast', 'Chips and Namkeens', 'Chocolates', 'Cold Drinks and Juices', 'Dairy, Bread and Eggs', 'Feminine Hygiene', 'Hair Care', 'Ice Creams and Frozen Desserts', 'Makeup', 'Paan Corner', 'Skincare', 'Sweet Corner']

Are the category values identical?
True

In [46]:
subcategories1 = set(df1['sub_category'].dropna().unique())
subcategories2 = set(df2['sub_category'].dropna().unique())

print("Subcategories only in df1:")
print(sorted(subcategories1 - subcategories2))

print("\nSubcategories only in df2:")
print(sorted(subcategories2 - subcategories1))

print("\nCommon subcategories:")
print(sorted(subcategories1 & subcategories2))

print("\nAre the subcategory values identical?")
print(subcategories1 == subcategories2)

Subcategories only in df1:
[]

Subcategories only in df2:
[]

Common subcategories:
['Atta', 'Baby Bathing', 'Baby Cream & Lotions', 'Baby Diapers', 'Baby Food and Formula', 'Baby Hygiene', 'Baby Oil and Talc', 'Baby Oral Care', 'Baby Pharma', 'Baby Wipes', 'Baking Ingredients', 'Bath & Beauty gifts', 'Bath Accessories', 'Batters', 'Beauty Supplements', 'Besan, Sooji and Maida', 'Bhujia and Namkeens', 'Body Lotion & Oils', 'Body Lotions', 'Books and Toys', 'Bread and Buns', 'Butter', 'Cakes & Pies', 'Cakes & Sandwiches', 'Cakes and Pies', 'Candies & More', 'Cheese', 'Chikki', 'Chips and Crisps', 'Chocofills', 'Clothes & Accessories', 'Coconut Water', 'Cold Coffee', 'Combs & Brushes', 'Conditioners & Masks', 'Cones', 'Cookies', 'Cream Biscuits', 'Cream and Condensed Milk', 'Creams & Moisturizers', 'Cups', 'Curd and Yogurts', 'Dark Chocolates', 'Dessert Mixes', 'Disposal Bags and Cramp Relief', 'Dry Fruit Sweets', 'Eggs', 'Energy Bars', 'Energy Drinks', 'Eye lens', 'Eyes', 'Face', 'Face Care', 'Face wash and scrubs', 'Feeding and Teething Needs', 'Flakes', 'Fragrance & Talc', 'Fresh Bakery', 'Fresh Juices', 'Gift Boxes', 'Gift Hampers', 'Gifts & More', 'Gourmet', 'Gourmet collection', 'Guiltfree', 'Gulab Jamun', 'Gulkand & Paan', 'Gum and Mint', 'Gums & Mint', 'Hair Colour', 'Hair Dryers and Stylers', 'Hair Oils and Serums', 'Hair Removal', 'Hair Styling Gels & Creams', 'Hair Supplements', 'Handwash', 'Healthy Snacking', 'Ice Tea & Kombucha', 'Intimate Wipes and Wash', 'Juices and Fruit Drinks', 'Kaju Katli & Barfi', 'Kids Cereals', 'Kulfi', 'Kunafa Chocolate', 'Ladoos', 'Lassi and Buttermilk', 'Lip care', 'Lips', 'Makhana & Dry Fruits', 'Mango Drinks', 'Marie & Digestive', 'Masks & Cleansers', 'Mens Perfume', 'Menstrual Cups and Tampons', 'Milk', 'Milk Based Drinks', 'Milk Chocolates', 'Milkshakes and More', 'Millets & Daliya', 'Mom Care', 'Muesli & Granola', 'Multi groomers', 'Mysore Pak', 'Nachos', 'Nails', 'Oats', 'Oral care', 'Other Flours', 'Paan and Mouth Fresheners', 'Pancake Mixes', 'Paneer and Tofu', 'Peanut Butters', 'Pedhas', 'Period Panties and Liners', 'Poha & Puffed Rice', 'Popcorn', 'Premium', 'Premium Brands', 'Rajma, Chola and Others', 'Rare Finds', 'Rasgulla', 'Rasmalai', 'Ready Mixes', 'Real Fruit', 'Regional Favorites', 'Rice', 'Roll on', 'Rusk', 'Salted & Plain', 'Sanitary Pads', 'Seeds and trail Mixes', 'Serums, Toners', 'Shampoo', 'Shared Packs', 'Shower gel', 'Soaps', 'Soda and Mixers', 'Soft Drinks', 'Sticks', 'Sunscreen', 'Syrups', 'Tools & Brushes', 'Toor, Moong and Urad', 'Travel Needs & Baby Gears', 'Tubs & Party Packs', 'Wafers', 'Water and Ice Cubes', 'Womens Perfume']

Are the subcategory values identical?
True

In [47]:
dep1 = set(df1['department'].dropna().unique())
dep2 = set(df2['department'].dropna().unique())

print("Departments only in df1:")
print(sorted(dep1 - dep2))

print("\nDepartments only in df2:")
print(sorted(dep2 - dep1))

print("\nCommon departments:")
print(sorted(dep1 & dep2))

print("\nAre the department values identical?")
print(dep1 == dep2)

Departments only in df1:
[]

Departments only in df2:
[]

Common departments:
['Atta, Rice & Dal', 'Baby Care', 'Bakery & Biscuits', 'Beauty & Cosmetics', 'Cold Drinks & Juices', 'Dairy & Breakfast', 'Munchies', 'Personal Care', 'Sweet Tooth']

Are the department values identical?
True

In [48]:
brand1 = set(df1['brand_name'].dropna().unique())
brand2 = set(df2['brand_name'].dropna().unique())

print("Brands only in df1:")
print(sorted(brand1 - brand2))

print("\nBrands only in df2:")
print(sorted(brand2 - brand1))

print("\nCommon brands:")
print(sorted(brand1 & brand2))

print("\nAre the brand values identical?")
print(brand1 == brand2)

Brands only in df1:
['& Stirred', '100 PLUS', '4Mation Skins', 'ACM', 'AI', 'ALPEN', 'APOTEKARNES', 'ARNOTTS TIM TAM', 'ASF ANJAN SRI FOODS', 'ASMITA ORGANIC FARMS', 'Aaa', 'Aadvik', 'Afnan', 'After Eight', 'Aladdin Dates', "Alan's", 'Alfez', 'Alokam Sattvam', 'Ambrolite Cold', 'Ancer Lm', 'Ancient Root', 'Anthon Berg', 'Aplus', 'Arjun', "Arnott's", 'Ascodex', "Ashdeep's Insta Bytes Easy Cook", 'Aura Divine', 'Aurganic Foods', 'Auricchio', 'BAMBOO', 'BATTERY', 'BEGUM VICTORIA', 'BONCAFE', 'BY WISHTREND', 'Babique', 'Baby Bel', 'Barbie', 'Barebells', 'Batter Chatter', 'Bauli India Bakes & Sweets Pvt Ltd', 'Be Brawn', 'Becel', "Ben & Jerry's", 'Benadryl', 'Benbits', 'Bentasils', 'Bergamot Beaute', 'Bharat', 'Bharat Vedica', 'Big Tom', 'Bilasure M Kid', 'Bioré', 'Blue Dragon', 'Blue Elephant', "Bob's Red Mill", 'Bon Fiction', 'Boots', 'Botanical Luxuriate', 'Bottle Green', 'Boursin', 'Brain Blasterz', 'Brain Licker', 'Bregano', 'Brets', 'Britannia Come Alive', 'Bro Zedex', 'Brown Baking Company', 'C4', 'CAMAY', 'CAMEO', 'CANTU', 'CARNATION', 'CERE VE', 'CHILL OUT', 'CQK', 'CREMYO', 'Canara Farms', 'Canari Star', 'Carmans', 'Carrs', 'Casillo', 'Cathy Doll', 'Catwalk Botanics', 'Cavandish & Harvey', 'Celsius', 'Ceriz', 'Chalet', 'Childhood', 'Childs Farm', 'ChocolateX', 'Chocomel', 'Chokhi Dhani', 'Cinnamon Toast Crunch', 'Claret', 'Clean & Dry', 'Cocao Springs', 'Cocomelon', 'Coke', 'Colman', 'Cone End Toe', 'Conscious Food', 'Creme Castle', 'Curio', 'DECOY', 'DEDOX', 'DESEO', 'DOTS', 'DRAGON KING', 'Daelmans', 'Daily Life Forever52', 'Dakshyn', 'Devon', 'Digennaro', 'Dodoni', 'Doowee Donut', 'Dotshot', 'Dr Sour', 'Dr.Dento', 'EARTHEN POT', 'ECLIPSE', 'ELEFTHERIA', 'Earth Fresh', 'Eat Millet', 'Eddie and Holly', 'Eggnest', 'Electrorush', 'Elle & Vire', 'Elvis', 'Embarouge', 'Emmi', 'Epicure', 'Eru', 'Esterrium', 'Everteen', 'FARM TRAILS', 'FIT BARS', 'FRUIT OF THE EARTH', 'Falcone', 'Farmside', 'Farmveda', 'Febrex Plus', 'Fevicreate', 'Flawsome', 'Food Square', 'Fox', 'FreshtoHome', 'Friends', 'Frix', 'From Granny', 'GLICO', 'GPR', 'GRAN', 'GSB', 'GUINNESS', 'Gem', 'Gentilini', 'Getkrrackin', 'Ghasitaram gifts', 'Glinter', 'Godrej Bloq', 'Gud Grain', 'Gujjubhai', 'HACHI WITH LOVE', 'HAIR FOOD', 'HEALTH 1ST', 'HEALTHAID', 'HEEVA', 'HI LIFE', 'HOSTESS', 'Hachi', 'Hachi Premium Snack', 'Hair Resq', 'Handful Of Health', 'Hangout Cakes', 'Health 1st', 'Healthy Choice', 'Heidi', 'Hello', 'Hello Kitty', 'Hello Mallows', 'Hhlevo', 'Hhlevo M', 'Highland', 'Home Delight', 'Hubdha', 'Hullo', 'IGP', 'ILE DE FRANCE', 'IRISH SPRING', 'Illy', 'Impact', 'Inaco', 'Innovitoy', 'Jairaj', 'Jinkies', 'John Mccambridge', 'Jules Destrooper', 'KALFANY', 'KIBI KIBI', 'KITTY', 'KOKOLA', 'KRISHIVAL', 'KRISHNAVENI PREMIUM SORTED RICE', 'KT Professional', 'KUBRA', 'Kanjer', 'Kiddy Head', 'King Uncle', 'Kingfisher', 'Kings Kulfi', 'Kiri', 'Kitoko', 'Klg', 'Kool Aid', 'Krisims', 'Krizvo', 'Ktein', 'Kundal', "L'oreal", 'LANEIGE', 'La Folie', 'Lasma', 'Laughing Cow', 'Lcf', 'Le Pure Chocolatier', 'Levosiz M', 'Lip Smacker', 'Lu', 'Lutti', 'M&S', 'MARS Cosmetics', 'MATHIEU TEISSEIRE', 'MEDICUBE', 'MELKUNIE', 'MIKE & IKE', 'MOTHER NURTURE', 'MY ARMOR', 'Madam', 'Made Of Milk', 'Maiva Frappe', 'Malloz Pops', 'Masking', 'Mason & Co', 'Maxvita', 'Medha', 'Meiji', 'Melted Joy', 'Merba', 'MiHeSo Mind Health Soul', 'Milk Station', 'Milky Way', 'Miraj', 'Mistine Top', 'Mizuberg', "Mohun's", 'Molino', 'MomsMade', 'Monde', 'Monetta', 'Monginis', 'Monkey Bar', 'Montecip', 'Montewok Lc', 'Montina', 'Montina L', 'Montral', 'Mother Nature', 'Mulberry', 'Must be Nuts', 'NAWON', 'NERAH SKIN', 'NJOY', 'NYGARDA', "Nahoum's", 'Nailjoy', 'Nano Basmati Rice', "Naran's", 'Naraya', 'Nasta', 'Natible', 'Naturoz', 'Nauti Nati', 'Neude', 'No Cheat', 'Nueats', 'Nutramino', 'Nutricos', 'OLDGOA', 'Oaken Glow', 'Ob', 'Odimont', 'Odimont Lc', 'OhG snack', 'Old Amsterdam', 'Ollefud', 'Omay Foods', 'Omayln', 'Ombre Bliss', 'Omji', 'One Little Farm', 'Oral', 'Organix Mantra', 'Orgran', 'Oriental', 'P.Calm', 'PAYSAN BRETON', 'PEARL', 'PEARLVILLE', 'PETAL FRESH PURE', 'PITTAS', 'PLANTQFIT', 'PURE & SURE', "Pai's Bakery", 'Palm Era', 'Pam', 'Paneangeli', 'Patang', 'Paul & Mike', 'Pep Nails', 'Philadelphia', 'Pigeon By Stovekraft', 'Pigeon India', 'Pop Rocks', 'Popular Fit Eats', 'Prorush', 'Puck', 'Pure', 'QUICK MILK', 'Quick Click Goods', 'RANDOM HARVEST', 'REDONDO', 'RESPECT', 'RUBERA', 'RYVITA', 'Red Band', 'Regulus Agro Organic', 'Relow', 'Rhine Valley', 'Rice Up', 'Runts', 'Rylan', 'SARGAM', 'SFT', 'SISO', 'SKYNLAB+', 'SLUSH', 'SP', 'STAR WARS', 'STARBUCKS', 'SUAVE KIDS', 'SWEET BANDIT', 'Saboo', 'SaleOn', 'Sana Health First', 'Saratoga', 'Saucery', 'Scotti', 'Selpak', "Selvi's", 'Sensur', 'Serapheena', 'Shakuntlam', 'Sheese', "Shiva's", 'Shree Ram Papad', 'Sindhi Dry Fruits', 'Skin Cottage', 'Skulz Energy', 'Smint', 'Snackians', 'Sober Monkey', 'Southside Habits', 'Soventus', 'Soyaagri', 'Sportlife', 'Spotted Cow', 'Squid Game', 'Sri Anmol', 'Sri Gomatruka', 'St Ives', 'Stan Farms', 'Steenland', 'Stergic', 'Sterilgarda', 'Storck', 'Sumo L Plus', 'Sunsweet', 'Svaras', 'Swiss Miss', 'THE JELLY BEAN FACTORY', 'THE NIBBLE BOX COM COM', 'TIPPGRAL', 'TOP NUT', 'TWO BROTHERS', 'Tabu', 'Tajin', 'Tarami', 'Tartufi Jimmy', 'Tastee', 'Tec Tavakkal', 'Teegetrank', 'Terry', 'Testo', 'The Better J', 'The Doughman', 'The Fine Cheese Co', 'The Honest Basket', 'The Mad Nose', 'The Nibble Box', 'Tictac', 'Tim Tam', 'Tokimeki', 'Toska Chocolates', 'Toytales', 'Trapa', 'Treet', 'Triple Elephant', 'TurtleBee', 'Tweek', 'Twiddles by Yuvraj Singh', "USTAD BANNE NAWAB'S", 'Unify', 'Urbani', 'Uttam Sugar', 'VENZ', 'VI-JOHN', 'VICKS', 'Vandys', 'Vantej', 'Vegan Sheese', 'Verka', 'Verkade', 'Vilda', 'Violife', 'Vitalogy', 'Vithit', 'Voiish', 'Vyndo', 'WHOLESOME DELIGHT', 'Wasa', 'Weetabix', "Well's", 'Whyfryy', 'WickedGud', 'Wilhelmina', 'Wonder toys', 'YOGADENT', 'Yoko', 'Yoogutty', 'Yuri Woori', 'Zama', 'Zapz Snacks', 'Zazzy', 'Zest', 'Ziaho', 'adityaa milk', 'cocaodo', 'entisi', 'tit bits']

Brands only in df2:
['A One Fresh', "AB'S", 'ARLA', 'Aaha', 'Artiste', 'Aswins', 'Auric', 'BabyChakra', 'Bajaj Sk', 'Baken Brown', 'Bakers Bunch', 'Bakers World', 'Biore Men', 'Boba Bhai Ice Creams', 'Bobs Red Mill', 'Bonvie', 'CHIZZPA', 'Calbee', 'Chak Now', 'Chhaswala', 'Chirania', 'Clamy', 'Daintys', 'Dasani', 'Davat', 'Depiwhite', 'Double Deer', 'Fiesta', 'Firangi Mithai Bakery', 'Fresh Choice', 'Fruit Treat', 'GOPAL WAFERS', 'Go Grub', 'Gone Mad', 'HOT CAKES', 'Happy Jars', 'KALYAN BHEL', 'Lemme Be', 'Maharaja', 'Mango Sip', 'Milky Moo', 'Millimo', 'Mr Puff', 'Muncherri', 'Nativenuts', 'OMFED', 'PADDYS', 'PETPHOOL', 'PRAGATI', 'Panash Wellness', 'Paris Bakery', 'Ponlait', 'Raja Bhujia', 'Rajnigandha', 'Real Namkeen', 'Safal', 'Saravana', "Shri Jain Jl's", 'Smoodies', 'Sober', 'Sober and Co', 'Subam', 'Subko', 'Sumul', 'The Achaar Library', 'The Khao Project', 'Toy max', 'VIPUL DUDHIYA SWEETS (NEHRUNAGARWALA)', 'Vikas', 'Yolkemi']

Common brands:

In [49]:
city1 = set(df1['city'].dropna().unique())
city2 = set(df2['city'].dropna().unique())

print("Cities only in df1:")
print(sorted(city1 - city2))
print(len(city1 - city2))

print("\nCities only in df2:")
print(sorted(city2 - city1))
print(len(city2 - city1))

print("\nCommon cities:")
print(sorted(city1 & city2))
print(len(city1 & city2))

print("\nAre the city values identical?")
print(city1 == city2)

Cities only in df1:
['Anantapur', 'Belagavi', 'Dehradun', 'Hubballi', 'Jalandhar', 'Jodhpur', 'Kalamassery', 'Kalyan', 'Kancheepuram', 'Kanpur', 'Khammam', 'Ludhiana', 'Margao', 'Meerut', 'Navi Mumbai', 'Perumbavoor', 'Prayagraj', 'Rajkot', 'Ranchi', 'Siliguri', 'Tenali', 'Udupi', 'Vadodra', 'Visakhapatnam']
24

Cities only in df2:
['Ahmedabad', 'Ajmer', 'Amravati', 'Bhubaneswar', 'Coimbatore', 'Danapur', 'Delhi', 'Faridabad', 'Guntur', 'Kollam', 'Kozhikode', 'Latur', 'Mapusa', 'Muzaffarpur', 'Mysuru', 'Nandivaram Guduvancheri', 'Nashik', 'New Town', 'Nizamabad', 'Ongole', 'Patna', 'Porvorim', 'Puducherry', 'Rudrapur', 'Silchar', 'Surat', 'Trivandrum', 'Vellore', 'Vizianagaram', 'Warangal']
30

Common cities:
['Bangalore', 'Chennai', 'Ghaziabad', 'Gurgaon', 'Guwahati', 'Hyderabad', 'Indore', 'Jaipur', 'Kochi', 'Kolkata', 'Lucknow', 'Mumbai', 'Noida', 'Pune', 'Varanasi', 'Vasai Virar', 'Vijayawada']
17

Are the city values identical?
False

In [50]:
df2['brand_name'].isnull().sum()

106

In [51]:
# Convert to numeric (if they are stored as strings)
df2['promo_offer_price'] = pd.to_numeric(df2['promo_offer_price'], errors='coerce')
df2['product_price'] = pd.to_numeric(df2['product_price'], errors='coerce')

# Find records where promo_offer_price > product_price
invalid_records = df2[
    (df2['promo_offer_price'].notna()) &
    (df2['product_price'].notna()) &
    (df2['promo_offer_price'] > df2['product_price'])
]

print(invalid_records[['unique_id', 'product_name', 'product_price', 'promo_offer_price']])
print(f"\nNumber of violating records: {len(invalid_records)}")

Empty DataFrame
Columns: [unique_id, product_name, product_price, promo_offer_price]
Index: []

Number of violating records: 0

In [52]:
# Treat NaN and empty strings as empty
price_exists = (
    df2['promo_offer_price'].notna() &
    (df2['promo_offer_price'].astype(str).str.strip() != '')
)

desc_exists = (
    df2['promo_offer_description'].notna() &
    (df2['promo_offer_description'].astype(str).str.strip() != '')
)

# One exists, the other doesn't (XOR)
invalid_records = df2[
    price_exists ^ desc_exists
]

print(invalid_records[
    ['unique_id', 'promo_offer_price', 'promo_offer_description']
])

Empty DataFrame
Columns: [unique_id, promo_offer_price, promo_offer_description]
Index: []

In [53]:
invalid = df2[
    df2['product_image_urls'].isna() |
    (df2['product_image_urls'].astype(str).str.strip() == '')
]

print(invalid[['unique_id', 'product_image_urls']])

Empty DataFrame
Columns: [unique_id, product_image_urls]
Index: []

In [59]:
# Length of product names (excluding leading/trailing spaces)
name_length = df2['promo_offer_description'].fillna('').str.strip().str.len()

# Define thresholds
MIN_LENGTH = 5
MAX_LENGTH = 10

# Find invalid product names
invalid_promo = df2[
    (name_length < MIN_LENGTH) |
    (name_length > MAX_LENGTH)
]

print(f"Number of invalid promo descriptions: {len(invalid_promo)}")

print(
    invalid_promo[
        ['unique_id', 'promo_offer_description', 'product_url']
    ].assign(name_length=name_length.loc[invalid_promo.index])
)

Number of invalid promo descriptions: 0
Empty DataFrame
Columns: [unique_id, promo_offer_description, product_url, name_length]
Index: []