**Swiggy Data Analysis**

**1) Business Objective**

To assess and improve the quality, consistency, and completeness of the grocery product listing data by identifying anomalies, inconsistencies, missing information, duplicates, and pricing irregularities across products, categories, stores, and locations, thereby ensuring accurate product information and enhancing the customer shopping experience.

**2) Import Libraries**

In [1]:
import pandas as pd        # For data manipulation
import numpy as np      # For numerical computations
import seaborn as sns  # For advanced visualization
import matplotlib.pyplot as plt # For plotting
import re # For regular expressions

pd.set_option('display.max_colwidth', None)

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

**3) Import Dataset**

In [73]:
df1 = pd.read_csv("/home/user/Downloads/2026-07-31/swiggy_instamart_2026_07_30.csv") 
df2 = pd.read_csv("/home/user/Downloads/2026-07-31/swiggy_instamart_2026_07_31.csv")
# df3 = pd.read_csv("/home/user/Downloads/2026-07-27/swiggy_instamart_2026_07_27.csv")
 #Reading Dataset from csv file

**4) Data Insights**

In [74]:
print("INFORMATION ABOUT DATASET 1")
print("--------------------------------")
df1.info()

INFORMATION ABOUT DATASET 1
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1207644 entries, 0 to 1207643
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1207644 non-null  object
 1   platform_name            1207644 non-null  object
 2   store_id                 1207644 non-null  int64
 3   store_name_location      1207644 non-null  object
 4   city                     1207644 non-null  object
 5   pin_code                 1207644 non-null  int64
 6   unique_id                1207644 non-null  object
 7   product_id_upc_ean       1207644 non-null  object
 8   department               1207644 non-null  object
 9   category                 1207644 non-null  object
 10  sub_category             1207644 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1207441 non-null  object
 13  product_name             1207644 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         1207644 non-null  object
 16  package_type             0 non-null        float64
 17  net_quantity             0 non-null        float64
 18  variants                 1207644 non-null  object
 19  item_mrp                 1207644 non-null  int64
 20  item_selling_price       1207644 non-null  int64
 21  out_of_stock_flag        1207644 non-null  object
 22  discount_flag            1207644 non-null  object
 23  product_price            1207644 non-null  int64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1207644 non-null  object
 26  promo_offer_price        1207644 non-null  int64
 27  discount_in_percent      1207644 non-null  int64
 28  stock_count              1207644 non-null  int64
 29  product_url              1207644 non-null  object
 30  product_image_urls       1207644 non-null  object
dtypes: float64(5), int64(8), object(18)
memory usage: 285.6+ MB

In [75]:
print("INFORMATION ABOUT DATASET 2")
print("--------------------------------")
df2.info()

INFORMATION ABOUT DATASET 2
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005334 entries, 0 to 1005333
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1005334 non-null  object
 1   platform_name            1005334 non-null  object
 2   store_id                 1005334 non-null  int64
 3   store_name_location      1005334 non-null  object
 4   city                     1005334 non-null  object
 5   pin_code                 1005334 non-null  int64
 6   unique_id                1005334 non-null  object
 7   product_id_upc_ean       1005334 non-null  object
 8   department               1005334 non-null  object
 9   category                 1005334 non-null  object
 10  sub_category             1005334 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1005274 non-null  object
 13  product_name             1005334 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         1005334 non-null  object
 16  package_type             0 non-null        float64
 17  net_quantity             0 non-null        float64
 18  variants                 1005334 non-null  object
 19  item_mrp                 1005334 non-null  int64
 20  item_selling_price       1005334 non-null  int64
 21  out_of_stock_flag        1005334 non-null  object
 22  discount_flag            1005334 non-null  object
 23  product_price            1005334 non-null  int64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1005334 non-null  object
 26  promo_offer_price        1005334 non-null  int64
 27  discount_in_percent      1005334 non-null  int64
 28  stock_count              1005334 non-null  int64
 29  product_url              1005334 non-null  object
 30  product_image_urls       1005334 non-null  object
dtypes: float64(5), int64(8), object(18)
memory usage: 237.8+ MB

In [6]:
print("INFORMATION ABOUT DATASET 3")
print("--------------------------------")
df3.info()

INFORMATION ABOUT DATASET 3
--------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182481 entries, 0 to 1182480
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1182481 non-null  object
 1   platform_name            1182481 non-null  object
 2   store_id                 1182481 non-null  int64
 3   store_name_location      1182481 non-null  object
 4   city                     1182481 non-null  object
 5   pin_code                 1182481 non-null  int64
 6   unique_id                1182481 non-null  object
 7   product_id_upc_ean       1182481 non-null  object
 8   department               1182481 non-null  object
 9   category                 1182481 non-null  object
 10  sub_category             1182481 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1182285 non-null  object
 13  product_name             1182481 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         1182481 non-null  object
 16  package_type             0 non-null        float64
 17  net_quantity             0 non-null        float64
 18  variants                 1182481 non-null  object
 19  item_mrp                 1182481 non-null  int64
 20  item_selling_price       1182481 non-null  int64
 21  out_of_stock_flag        1182481 non-null  object
 22  discount_flag            1182481 non-null  object
 23  product_price            1182481 non-null  int64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1182481 non-null  object
 26  promo_offer_price        1182481 non-null  int64
 27  discount_in_percent      1182481 non-null  int64
 28  stock_count              1182481 non-null  int64
 29  product_url              1182481 non-null  object
 30  product_image_urls       1182481 non-null  object
dtypes: float64(5), int64(8), object(18)
memory usage: 279.7+ MB

In [5]:
print("\nDESCRIPTIVE STATISTICS OF DATASET 1")
print("--------------------------------")
df1.describe().T.round(2)

DESCRIPTIVE STATISTICS OF DATASET 1
--------------------------------

,count,mean,std,min,25%,50%,75%,max
store_id,1182481.0,1.339760e+06,1.695088e+05,406774.0,1384513.0,1400547.0,1403179.0,1.405027e+06
pin_code,1182481.0,1.137931e+05,5.553740e+03,110005.0,110042.0,110080.0,122003.0,1.225050e+05
product_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
package_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
net_quantity,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
item_mrp,1182481.0,7.155048e+08,7.982343e+10,4.0,109.0,220.0,426.0,8.906005e+12
item_selling_price,1182481.0,7.155048e+08,7.982343e+10,4.0,92.0,182.0,360.0,8.906005e+12
product_price,1182481.0,7.155048e+08,7.982343e+10,4.0,92.0,182.0,360.0,8.906005e+12
unit_price,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_offer_price,1182481.0,7.155048e+08,7.982343e+10,4.0,92.0,182.0,360.0,8.906005e+12
discount_in_percent,1182481.0,1.438000e+01,1.510000e+01,0.0,0.0,10.0,21.0,9.200000e+01
stock_count,1182481.0,1.530000e+00,2.320000e+00,0.0,0.0,1.0,2.0,5.000000e+01

In [6]:
print("\nDESCRIPTIVE STATISTICS OF DATASET 2")
print("--------------------------------")
df2.describe().T.round(2)

DESCRIPTIVE STATISTICS OF DATASET 2
--------------------------------

,count,mean,std,min,25%,50%,75%,max
store_id,1207644.0,1.341523e+06,1.669346e+05,406774.0,1386271.0,1400547.0,1403184.0,1.405027e+06
pin_code,1207644.0,1.136372e+05,5.495920e+03,110005.0,110042.0,110075.0,122003.0,1.225050e+05
product_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
package_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
net_quantity,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
item_mrp,1207644.0,6.563481e+08,7.645267e+10,4.0,110.0,220.0,430.0,8.906005e+12
item_selling_price,1207644.0,6.563481e+08,7.645267e+10,4.0,91.0,184.0,360.0,8.906005e+12
product_price,1207644.0,6.563481e+08,7.645267e+10,4.0,91.0,184.0,360.0,8.906005e+12
unit_price,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_offer_price,1207644.0,6.563481e+08,7.645267e+10,4.0,91.0,184.0,360.0,8.906005e+12
discount_in_percent,1207644.0,1.482000e+01,1.548000e+01,0.0,0.0,10.0,23.0,9.500000e+01
stock_count,1207644.0,1.580000e+00,2.450000e+00,0.0,0.0,1.0,2.0,5.500000e+01

In [76]:
print("\nDATASET1 SHAPE")
print("--------------------------------")
print("The shape =", df1.shape)
num_rows, num_cols = df1.shape
num_features = num_cols - 1
num_data = num_rows * num_cols

# Print the information about the dataset
print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_cols}")
print(f"Number of Features: {num_features}")
print(f"Number of All Data: {num_data}")

DATASET1 SHAPE
--------------------------------
The shape = (1207644, 31)
Number of Rows: 1207644
Number of Columns: 31
Number of Features: 30
Number of All Data: 37436964

In [77]:
print("\nDATASET 2 SHAPE")
print("--------------------------------")
print("The shape =", df2.shape)
num_rows, num_cols = df2.shape
num_features = num_cols - 1
num_data = num_rows * num_cols

# Print the information about the dataset
print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_cols}")
print(f"Number of Features: {num_features}")
print(f"Number of All Data: {num_data}")

DATASET 2 SHAPE
--------------------------------
The shape = (1005334, 31)
Number of Rows: 1005334
Number of Columns: 31
Number of Features: 30
Number of All Data: 31165354

In [78]:
print("COLUMNWISE DATA1 PROFILING")
print("--------------------------------")
summary = []

for col in df1.columns:
    null_count = df1[col].isnull().sum()
    null_percent = round((null_count / len(df1)) * 100, 2)
    distinct_count = df1[col].nunique(dropna=True)

    # Check if all non-null values are unique
    is_unique = "Yes" if df1[col].is_unique and null_count == 0 else "No"


    summary.append({
        'column_name': col,
        'null_count': null_count,
        #'null_percent': null_percent,
        'distinct_count': distinct_count,
        'is_unique': is_unique
    })

summary_df = pd.DataFrame(summary)

# Display the summary
print(summary_df)

COLUMNWISE DATA1 PROFILING
--------------------------------
                column_name  null_count  distinct_count is_unique
0       crawl_date_and_time           0            5847        No
1             platform_name           0               1        No
2                  store_id           0             101        No
3       store_name_location           0              99        No
4                      city           0               2        No
5                  pin_code           0              58        No
6                 unique_id           0          983739        No
7        product_id_upc_ean           0           25620        No
8                department           0               9        No
9                  category           0              16        No
10             sub_category           0             147        No
11             product_type     1207644               0        No
12               brand_name         203            2270        No
13             product_name           0           26096        No
14      product_description     1207644               0        No
15         product_grammage           0            1902        No
16             package_type     1207644               0        No
17             net_quantity     1207644               0        No
18                 variants           0            7114        No
19                 item_mrp           0            1602        No
20       item_selling_price           0            1831        No
21        out_of_stock_flag           0               2        No
22            discount_flag           0               2        No
23            product_price           0            1831        No
24               unit_price     1207644               0        No
25  promo_offer_description           0              94        No
26        promo_offer_price           0            1831        No
27      discount_in_percent           0              94        No
28              stock_count           0              52        No
29              product_url           0           25620        No
30       product_image_urls           0           27761        No

In [79]:
print("COLUMNWISE DATA2 PROFILING")
print("--------------------------------")
summary = []

for col in df2.columns:
    null_count = df2[col].isnull().sum()
    null_percent = round((null_count / len(df2)) * 100, 2)
    distinct_count = df2[col].nunique(dropna=True)

    # Check if all non-null values are unique
    is_unique = "Yes" if df2[col].is_unique and null_count == 0 else "No"


    summary.append({
        'column_name': col,
        'null_count': null_count,
        #'null_percent': null_percent,
        'distinct_count': distinct_count,
        'is_unique': is_unique
    })

summary_df = pd.DataFrame(summary)

# Display the summary
print(summary_df)

COLUMNWISE DATA2 PROFILING
--------------------------------
                column_name  null_count  distinct_count is_unique
0       crawl_date_and_time           0            6070        No
1             platform_name           0               1        No
2                  store_id           0             118        No
3       store_name_location           0             100        No
4                      city           0              47        No
5                  pin_code           0              97        No
6                 unique_id           0          810817        No
7        product_id_upc_ean           0           31395        No
8                department           0               9        No
9                  category           0              16        No
10             sub_category           0             148        No
11             product_type     1005334               0        No
12               brand_name          60            3137        No
13             product_name           0           31775        No
14      product_description     1005334               0        No
15         product_grammage           0            2029        No
16             package_type     1005334               0        No
17             net_quantity     1005334               0        No
18                 variants           0            7395        No
19                 item_mrp           0            1693        No
20       item_selling_price           0            2083        No
21        out_of_stock_flag           0               2        No
22            discount_flag           0               2        No
23            product_price           0            2083        No
24               unit_price     1005334               0        No
25  promo_offer_description           0              91        No
26        promo_offer_price           0            2083        No
27      discount_in_percent           0              91        No
28              stock_count           0              52        No
29              product_url           0           31395        No
30       product_image_urls           0           34360        No

In [8]:
print("COLUMNWISE DATA3 PROFILING")
print("--------------------------------")
summary = []

for col in df3.columns:
    null_count = df3[col].isnull().sum()
    null_percent = round((null_count / len(df3)) * 100, 2)
    distinct_count = df3[col].nunique(dropna=True)

    # Check if all non-null values are unique
    is_unique = "Yes" if df3[col].is_unique and null_count == 0 else "No"


    summary.append({
        'column_name': col,
        'null_count': null_count,
        #'null_percent': null_percent,
        'distinct_count': distinct_count,
        'is_unique': is_unique
    })

summary_df = pd.DataFrame(summary)

# Display the summary
print(summary_df)

COLUMNWISE DATA3 PROFILING
--------------------------------
                column_name  null_count  distinct_count is_unique
0       crawl_date_and_time           0            5492        No
1             platform_name           0               1        No
2                  store_id           0             100        No
3       store_name_location           0              98        No
4                      city           0               2        No
5                  pin_code           0              56        No
6                 unique_id           0          958339        No
7        product_id_upc_ean           0           23461        No
8                department           0               9        No
9                  category           0              16        No
10             sub_category           0             147        No
11             product_type     1182481               0        No
12               brand_name         196            1973        No
13             product_name           0           24031        No
14      product_description     1182481               0        No
15         product_grammage           0            1858        No
16             package_type     1182481               0        No
17             net_quantity     1182481               0        No
18                 variants           0            7052        No
19                 item_mrp           0            1547        No
20       item_selling_price           0            1842        No
21        out_of_stock_flag           0               2        No
22            discount_flag           0               2        No
23            product_price           0            1842        No
24               unit_price     1182481               0        No
25  promo_offer_description           0              91        No
26        promo_offer_price           0            1842        No
27      discount_in_percent           0              91        No
28              stock_count           0              51        No
29              product_url           0           23461        No
30       product_image_urls           0           25735        No

In [80]:
store_list1 = set(df1['store_id'].unique())
store_list2 = set(df2['store_id'].unique())

print("Stores in first list, not in second list:")
print(list(store_list1 - store_list2))
print(len(list(store_list1 - store_list2)))

print("\nStores in second list, not in first list:")
print(list(store_list2 - store_list1))
print(len(list(store_list2 - store_list1)))

print("\nStores common in both lists:")
print(list(store_list1 & store_list2))
print(len(list(store_list1 & store_list2)))

Stores in first list, not in second list:
[1062419, 1062420, 1404450, 1230886, 1386535, 1386536, 1387568, 1384511, 1405012, 1402457, 1400924, 1382494, 1405027, 649841, 1389689, 1389690, 649851, 1239163, 1401469, 1062023, 1400967, 1388689, 1404576, 1404584, 1229997, 1404592, 1404596, 762550, 1398454, 1387704, 1387705, 762551, 1404604, 1099457, 1404610, 1099459, 1099458, 1402053, 1404613, 1402052, 1402055, 1404620, 1267917, 1384143, 1278169, 1386719, 1400547, 1400548, 1395428, 1400549, 1402607, 1402608, 1402609, 406774, 1404675, 1382659, 1404165, 1380623, 1394450, 1261842, 1394451, 1386271, 1397028, 1403179, 1403184, 1401649, 1401654, 1380671, 1403206, 1403207, 1403208, 1403213, 1404755, 1404770, 1382258, 810368, 1402248, 1402249, 1402253, 1399699, 1399700, 1383827, 1402777, 1401254, 1404841, 1383851, 1403311, 1386943, 1386948, 1381835, 1389005, 1389006, 1404879, 1392083, 1382871, 1404888, 1383383, 1385945, 1404891, 1398755, 1398757]
101

Stores in second list, not in first list:
[1404928, 1404929, 1404930, 1404931, 1404932, 1404933, 1404934, 1404935, 1404936, 1399809, 1395722, 1404941, 1404942, 1404943, 1404944, 1404945, 1392660, 1404951, 1404953, 1404958, 1404960, 1404961, 1404963, 1404964, 1404965, 1404966, 1404967, 1404968, 1404970, 1404984, 1404987, 1396284, 1404988, 1404990, 1404991, 1404992, 1384513, 1403457, 1404995, 1404993, 1404997, 1396293, 1396288, 1405001, 1405002, 1403468, 1405004, 1405005, 1405006, 1155153, 1405010, 1405009, 1405011, 1405013, 1405014, 1405015, 1405017, 1400922, 1400923, 1400925, 1400926, 1380447, 1400927, 1400929, 1400930, 1405028, 1405029, 1405030, 1405031, 1405032, 1405033, 1405034, 1405037, 1405046, 929911, 1405048, 1405049, 1405050, 1400955, 1400957, 1400958, 1400959, 1400960, 1400961, 1405058, 1400963, 1405060, 1400965, 1400966, 1400964, 1405061, 1388681, 1388682, 1403019, 1400970, 1403021, 1400974, 1400973, 1400975, 1388685, 1405071, 1400976, 1405076, 1388684, 1388686, 1400983, 1400984, 1400985, 1400977, 1389251, 1391892, 1401651, 1403191, 1403723, 1385836, 1402264, 1396660, 1398760]
118

Stores common in both lists:
[]
0

In [10]:
store_list2 = set(df2['store_id'].unique())
store_list3 = set(df3['store_id'].unique())

print("Stores in first list, not in second list:")
print(list(store_list2 - store_list3))
print(len(list(store_list2 - store_list3)))

print("\nStores in second list, not in first list:")
print(list(store_list3 - store_list2))
print(len(list(store_list3 - store_list2)))

print("\nStores common in both lists:")
print(list(store_list2 & store_list3))
print(len(list(store_list2 & store_list3)))

Stores in first list, not in second list:
[]
0

Stores in second list, not in first list:
[]
0

Stores common in both lists:
[1062419, 1062420, 1404450, 1230886, 1386535, 1386536, 1384511, 1389633, 1384513, 1405012, 1402457, 1400924, 1382494, 1405027, 649841, 1389689, 1389690, 649851, 1239163, 1401469, 1062023, 1400967, 1388689, 1404576, 1404584, 1229997, 1404592, 1404596, 762550, 1398454, 1387704, 1387705, 762551, 1404604, 1099457, 1099458, 1099459, 1404610, 1402053, 1402052, 1404613, 1402055, 1402056, 1404620, 1267917, 1384143, 1278169, 1386719, 1400547, 1400548, 1395428, 1400549, 1402607, 1402608, 1402609, 406774, 1404675, 1382659, 1404165, 1380623, 1394450, 1261842, 1394451, 1386271, 1397028, 1403179, 1403184, 1401649, 1401654, 1380671, 1403206, 1403207, 1403208, 1403213, 1404755, 1404770, 1382258, 810368, 1402248, 1402249, 1402253, 1399699, 1399700, 1383827, 1402777, 1401254, 1383851, 1403311, 1386943, 1386948, 1381835, 1389006, 1404879, 1392083, 1382871, 1404888, 1383383, 1385945, 1398755, 1398757]
100

In [81]:
df1.store_id.unique()
print(len(df1.store_id.unique()))
print(len(df1.store_name_location.unique()))

101
99

In [82]:
df2.store_id.unique()
print(len(df2.store_id.unique()))
print(len(df2.store_name_location.unique()))

118
100

In [11]:
df3.store_id.unique()
print(len(df3.store_id.unique()))
print(len(df3.store_name_location.unique()))

100
98

In [83]:
store_mapping = (
    df2.groupby('store_name_location')['store_id']
      .nunique()
      .reset_index(name='unique_store_ids')
      .sort_values('unique_store_ids', ascending=False)
)

multi_store = store_mapping[store_mapping['unique_store_ids'] > 1]

print(multi_store)
print("\nNumber of store_name_location with multiple store_ids:", len(multi_store))

                                                                                                                                                                                                                                                            store_name_location  \
0                                                                                                                                                                                             102, Champa LN, Green Glen Layout, Bellandur, Bengaluru, Karnataka, 560103, India
20                                                                                                                                   Blinkit Kannamangla Main Road, Unit-7, WayCool Foods Bangalore DC, Kannamangala Main Rd, Ardendale, Kannamangala, Karnataka, 560115, India
32  Harsh Tutorial At Kalachowki - FYJC SYJC CMA BAF BCOM BMS Commerce Classes, Shop No 33/2286 Abhyudaya Nagar Manorath S.G.S Ltd, Building No 33, Police Station, Opposite Kalachowki, Jijamata Nagar, Kalachowki, Abhyudaya Nagar, Parel, Mumbai, Maharashtra, 400033, India
34                                                                                                                                                                                             Hometech Shrishti, LBS Nagar, Kaggadasapura, Bengaluru, Karnataka, 560017, India
35                                                                              Hunger Free World - (A Mission By Malabar Group), Bulilding No A-5(B) NGEF Ancillary Industrial Estate, Whitefield Main Rd, Garudachar Palya, Mahadevapura, Bengaluru, Karnataka, 560048, India
36                                                                                                                                                                            Idax Head Office, Plotno-A/9, IDCO Industrial Estate, Patia, Bhubaneswar, Odisha 7, 751027, India
46                                                                                                                                King Mens Wear, Shop No 5 Jijamata Nagar, Kamgar Hospital Rd, Ramachandra Nagar, Waghle Estate, Thane West, Thane, Maharashtra, 400604, India
53                                                                                                                                                                    Narsinigi Methodist Church, Narsingi - Puppalaguda Main Rd, Narsingi, Hyderabad, Telangana, 500089, India
54                                                                                                                                                                                     Nest Craft, Semmancheri, Arasankalani, Sithalapakkam, Chennai, Tamil Nadu, 600130, India
55                                                                                                                                                                         New Saki Naka Police Station, Sangharsh Nagar, Chandivali, Powai, Mumbai, Maharashtra, 400076, India
56                                                                                                                                                                           OYO Home KC Arcade, 1, Thuthiyoor Rd, Padamughal, Kakkanad, Kochi, Kakkanad, Kerala, 682021, India
58                                                                                                                                                  PPPL Pharma, 569, KLR Complex, Cross Cut Rd, Varuthiangara Palayam, Ranganathapuram, Gandhipuram, Tamil Nadu, 641009, India
61                                                                                                                                                                                  Prabhavathi Elegant, Kumbena Agrahara, Krishnarajapura, Bengaluru, Karnataka, 560067, India
64                                                                                                                                                                                              Raja SC Mullick Rd, Bapuji Nagar, Jadavpur, Kolkata, West Bengal, 700032, India
71                                                                                                                                                               Sheeba Store, No 9, Nikoo Homes 2, Devin Paradise Enclave, RK Hegde Nagar, Bengaluru, Karnataka, 560077, India
75                                                                                                                                                                 Sinopia, # 89/2, BTS Layout, R.T.O Office, Arekere V Illage, Bannerughatta Road, Bengaluru, Karnataka 560076
82                                                                                                                                                                                                              Sun Royal Residency, Bejai, Mangaluru, Karnataka, 575004, India
94                                                                                                                                      VSR Sports Academy II, No.44/1, Gandhi Nagar, 1st Street, Old Perungalathur, Gandhi Nagar, Tambaram, Chennai, Tamil Nadu, 600063, India
95                                                                                                         Vital Fitness, 4th Floor Gowrichandra Arcade, No. 3/3, 2nd Main Road, 1st Cross Rd, Near Madiwala Park, Madiwala, 1st Stage, BTM Layout, Bengaluru, Karnataka 560068
29                                                                                                                                                                              Foyer Infinity, 43, ECC Rd, Pattandur Agrahara, Whitefield, Bengaluru, Karnataka, 560066, India
50                                                                                                                                                                                       Medicover Hospitals Gate, Cidco, Chhatrapati Sambhajinagar, Maharashtra, 431003, India

    unique_store_ids
0                  2
20                 2
32                 2
34                 2
35                 2
36                 2
46                 2
53                 2
54                 2
55                 2
56                 2
58                 2
61                 2
64                 2
71                 2
75                 2
82                 2
94                 2
95                 2
29                 2
50                 2

Number of store_name_location with multiple store_ids: 21

***Insights :***
_______________
    * Shape of the dataset is 12,42,276 X 31
    * None of the columns is having unique values.
    * 'product_type', 'product_description', 'package_type', 'net_quantity', 'unit_price' are completely null columns.
    * 'brand_name' is a partialy null column with 170 null values.
    * Distinct store_id and store_name_location count are 125 and 100 respectively. While ivestigating, we found that 28 store_name_locations have exactly two store_ids each.

**5) Primary key Analysis**

As per the above informations, no column can be choose as primary key.

In [84]:
# Check if the combination is unique
is_unique = not df2.duplicated(subset=['unique_id', 'store_id','product_id_upc_ean', 'product_name']).any()

print("Is (unique_id, store_id, product_id_upc_ean, product_name) combination unique?", is_unique)

Is (unique_id, store_id, product_id_upc_ean, product_name) combination unique? False

Checked several combinations, but couldn't fix a unique combination

**6) Duplicate Analysis**

In [85]:
print("EXACT DUPLICATE ROWS")
print("--------------------------------")
exact_duplicate_count = df2.duplicated().sum()
print("Exact duplicate rows:", exact_duplicate_count)


print("\nDUPLICATE PRODUCTS IN THE SAME STORE")
print("--------------------------------")
product_duplicate_count = df2.duplicated(
    subset=['store_id', 'product_name']
).sum()

print(f"\nNumber of duplicate products (store_id + product_name): {product_duplicate_count}")


print("\n========== DUPLICATE ANALYSIS SUMMARY ==========")
print(f"Total Rows                  : {len(df2)}")
print(f"Exact Duplicate Rows        : {exact_duplicate_count}")
print(f"Product Duplicate Rows      : {product_duplicate_count}")
print("================================================")

EXACT DUPLICATE ROWS
--------------------------------
Exact duplicate rows: 0

DUPLICATE PRODUCTS IN THE SAME STORE
--------------------------------

Number of duplicate products (store_id + product_name): 245354

========== DUPLICATE ANALYSIS SUMMARY ==========
Total Rows                  : 1005334
Exact Duplicate Rows        : 0
Product Duplicate Rows      : 245354
================================================

In [86]:
# checking for duplicate combinations of store_name_location, product_name, product_grammage, item_selling_price and package_type
dup_products = (
    df2.groupby([
        'store_name_location',
        'product_name',
        'product_grammage',
        'item_selling_price',
        'package_type'
    ])
    .size()
    .reset_index(name='count')
)

dup_products = dup_products[dup_products['count'] > 1]\
                    .sort_values('count', ascending=False)

print("Duplicate combinations:", len(dup_products))
print(dup_products.head(20))

Duplicate combinations: 0
Empty DataFrame
Columns: [store_name_location, product_name, product_grammage, item_selling_price, package_type, count]
Index: []

In [87]:
# Check for products mapped to multiple categories
product_category_check = (
    df2.groupby(['store_name_location', 'product_name','product_grammage', 'product_url','package_type'])['category']
      .nunique()
      .reset_index(name='category_count')
)

# Products mapped to more than one category
inconsistent_products = product_category_check[
    product_category_check['category_count'] > 1
].sort_values('category_count', ascending=False)

print("Number of inconsistent products:",
      len(inconsistent_products))

print(inconsistent_products.head())
print("\nNumber of inconsistent products:", len(inconsistent_products))

Number of inconsistent products: 0
Empty DataFrame
Columns: [store_name_location, product_name, product_grammage, product_url, package_type, category_count]
Index: []

Number of inconsistent products: 0

In [88]:
# Check for products mapped to multiple sub_categories
product_category_check = (
    df2.groupby(['store_name_location', 'product_name','product_grammage', 'product_url','package_type'])['sub_category']
      .nunique()
      .reset_index(name='sub_category_count')
)

# Products mapped to more than one category
inconsistent_products = product_category_check[
    product_category_check['sub_category_count'] > 1
].sort_values('sub_category_count', ascending=False)

print("Number of inconsistent products:",
      len(inconsistent_products))

print(inconsistent_products.head())
print("\nNumber of inconsistent products:", len(inconsistent_products))

Number of inconsistent products: 0
Empty DataFrame
Columns: [store_name_location, product_name, product_grammage, product_url, package_type, sub_category_count]
Index: []

Number of inconsistent products: 0

In [89]:
# Count distinct product names for each unique_id
product_name_counts = (
    df2.groupby("unique_id")["product_name"]
      .nunique(dropna=False)
)

# unique_id values having more than one product_name
duplicate_unique_ids = product_name_counts[product_name_counts > 1].index

print(f"Number of unique_id values with different product_name: {len(duplicate_unique_ids)}")
print(duplicate_unique_ids.tolist())

Number of unique_id values with different product_name: 0
[]

***Insights :***
___________________

    * No exact duplicate columns exists on the dataset, but products duplicates on same stores
    * While deeply investigating, these duplicate products differ by grammage, price or package_type.
    * Also confirmed no products duplicates on same store under different categories.
    * In overall, the dataset is not containing duplicate products visibly.

7) MISSING VALUE ANALYSIS

As mentioned some columns are completely null, that not need to be evaluated. brand_name column is partially null with 170 null values. Lets evaluate that.

In [90]:
# Missing summary by store
print("\nMISSING SUMMARY BY STORE")
print("--------------------------------")
missing_by_store = df2.groupby('store_name_location')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_store)

MISSING SUMMARY BY STORE
--------------------------------
                                                                                                                                                     store_name_location  \
0                                                                                      102, Champa LN, Green Glen Layout, Bellandur, Bengaluru, Karnataka, 560103, India
1                                                                                                      164-132, Hill Rd, Bandra West, Mumbai, Maharashtra, 400050, India
2                                                                                         2nd Main Road, 2nd Main Rd, Seshadripuram, Bengaluru, Karnataka, 560003, India
3                                                                         37, 17, Meanee Ave Rd, Sindhi Colony, Sivanchetti Gardens, Bengaluru, Karnataka, 560005, India
4                                                                               39, Badripur Rd, Deepnagar Village, Defence Colony, Dehradun, Uttarakhand, 248012, India
..                                                                                                                                                                   ...
95  Vital Fitness, 4th Floor Gowrichandra Arcade, No. 3/3, 2nd Main Road, 1st Cross Rd, Near Madiwala Park, Madiwala, 1st Stage, BTM Layout, Bengaluru, Karnataka 560068
96       Xplode Gym 'N' Spa - Best Gym | Fitness Club | Weight Loss Center In Sonipat, SD Tower, Near, Maharana Pratap Chowk, Sector 12, Sonipat, Haryana, 131001, India
97                  YD Homes, Gopala Reddy Layout, YD Homes, 2nd Main Rd, Gopal Reddy Layout, Annaiah Reddy Layout, Dodda Banaswadi, Bengaluru, Karnataka, 560043, India
98                                                            Yousuf Cycle Store, 9-1-46/3, Hasmatpet Rd, Hasmathpet, Bowenpally, Secunderabad, Telangana, 500011, India
99                                                                                       Zepto HSR 02, ITI Layout, Somasundarapalya, Bengaluru, Karnataka, 560102, India

    brand_name
0     0.000000
1     0.000000
2     0.032178
3     0.000000
4     0.013970
..         ...
95    0.000000
96    0.000000
97    0.028543
98    0.039872
99    0.000000

[100 rows x 2 columns]

In [91]:
# Missing summary by category
print("\nMISSING SUMMARY BY CATEGORY")
print("--------------------------------")
missing_by_category = df2.groupby('category')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_category)

MISSING SUMMARY BY CATEGORY
--------------------------------
                          category  brand_name
0               Atta, Rice and Dal    0.053485
1                        Baby Care    0.001920
2                    Bath and Body    0.000000
3               Biscuits and Cakes    0.000000
4            Cereals and Breakfast    0.000000
5               Chips and Namkeens    0.000000
6                       Chocolates    0.000000
7           Cold Drinks and Juices    0.000000
8            Dairy, Bread and Eggs    0.000000
9                 Feminine Hygiene    0.000000
10                       Hair Care    0.000000
11  Ice Creams and Frozen Desserts    0.022669
12                          Makeup    0.017579
13                     Paan Corner    0.000000
14                        Skincare    0.000000
15                    Sweet Corner    0.000000

In [92]:
print("\nMISSING SUMMARY BY CITY")
print("--------------------------------")

missing_by_city = df2.groupby('city')['brand_name'].apply(
    lambda x: x.isnull().mean() * 100
).reset_index()

print(missing_by_city)

MISSING SUMMARY BY CITY
--------------------------------
                           city  brand_name
0             Adavi Takkelapadu    0.000000
1                     Ahmedabad    0.003933
2                       Aligarh    0.022622
3                     Bangalore    0.007554
4                      Bareilly    0.012019
5                     Bengaluru    0.000000
6                      Bhimaram    0.000000
7                   Bhubaneswar    0.007882
8                       Chennai    0.004725
9     Chhatrapati Sambhajinagar    0.000000
10                   Coimbatore    0.002773
11                   Davanagere    0.009144
12                     Dehradun    0.013970
13                        Delhi    0.000000
14                    Ernakulam    0.000000
15                    Gorakhpur    0.020313
16                      Gurgaon    0.031656
17                        Hosur    0.000000
18                    Hyderabad    0.008778
19                       Jaipur    0.016614
20                      Khammam    0.000000
21                        Kochi    0.009066
22                      Kolkata    0.000000
23                    Kozhikode    0.000000
24                      Lucknow    0.005631
25                      Madurai    0.022320
26                    Mangaluru    0.000000
27                       Mumbai    0.004608
28                  Navi Mumbai    0.012737
29                        Noida    0.000000
30                       Paipad    0.000000
31                     Panihati    0.000000
32                        Patna    0.000000
33                         Pune    0.005444
34            Ramanayakanahalli    0.000000
35                   Shivamogga    0.000000
36                      Sonipat    0.000000
37  St. Thomas Mount Cantonment    0.000000
38                        Surat    0.000000
39           Thiruvananthapuram    0.000000
40                   Trivandrum    0.000000
41                        Ullal    0.000000
42                  Vaddeswaram    0.000000
43                     Vadodara    0.000000
44                     Varanasi    0.000000
45                   Vazhakkala    0.000000
46                Visakhapatnam    0.000000

***Insights :***
_______________

    * In store-wise, missing values are almost equally distributed.
    * In category-wise also mising percentage is below 0.2, which is negliglible.
    * In city-wise too, the missing percentage has no hike at any particular city.
    * So in overall missing% doesn't have any direct impact form store/category/city.

**8) Category Hierarchy Consistency**

In [97]:
print("\n DEPARTMENT - CATEGORY CONSISTENCY")
print("--------------------------------")

dept_category_map = df2.groupby('department')['category'].unique()

for dept, cats in dept_category_map.items():
    print("\nDEPARTMENT:", dept)
    print(list(cats))

 DEPARTMENT - CATEGORY CONSISTENCY
--------------------------------

DEPARTMENT: Atta, Rice & Dal
['Atta, Rice and Dal']

DEPARTMENT: Baby Care
['Baby Care']

DEPARTMENT: Bakery & Biscuits
['Biscuits and Cakes']

DEPARTMENT: Beauty & Cosmetics
['Makeup', 'Bath and Body', 'Hair Care']

DEPARTMENT: Cold Drinks & Juices
['Cold Drinks and Juices']

DEPARTMENT: Dairy & Breakfast
['Dairy, Bread and Eggs', 'Cereals and Breakfast']

DEPARTMENT: Munchies
['Chips and Namkeens', 'Cereals and Breakfast']

DEPARTMENT: Personal Care
['Bath and Body', 'Skincare', 'Feminine Hygiene', 'Hair Care', 'Makeup']

DEPARTMENT: Sweet Tooth
['Sweet Corner', 'Chocolates', 'Ice Creams and Frozen Desserts', 'Paan Corner']

In [98]:
print("\n CATEGORY - SUBCATEGORY CONSISTENCY")
print("--------------------------------")

cat_subcat_map = df2.groupby('category')['sub_category'].unique()

for cat, subcats in cat_subcat_map.items():
    print("\nCATEGORY:", cat)
    print(list(subcats))

 CATEGORY - SUBCATEGORY CONSISTENCY
--------------------------------

CATEGORY: Atta, Rice and Dal
['Atta', 'Other Flours', 'Besan, Sooji and Maida', 'Millets & Daliya', 'Poha & Puffed Rice', 'Toor, Moong and Urad', 'Rajma, Chola and Others', 'Rice']

CATEGORY: Baby Care
['Clothes & Accessories', 'Travel Needs & Baby Gears', 'Gifts & More', 'Books and Toys', 'Baby Wipes', 'Baby Bathing', 'Baby Food and Formula', 'Baby Diapers', 'Feeding and Teething Needs', 'Baby Pharma', 'Baby Hygiene', 'Mom Care', 'Baby Oil and Talc', 'Baby Oral Care', 'Baby Cream & Lotions']

CATEGORY: Bath and Body
['Face Care', 'Fragrance & Talc', 'Body Lotion & Oils', 'Mens Perfume', 'Womens Perfume', 'Bath & Beauty gifts', 'Lip care', 'Soaps', 'Roll on', 'Shower gel', 'Bath Accessories', 'Oral care', 'Handwash', 'Multi groomers']

CATEGORY: Biscuits and Cakes
['Baking Ingredients', 'Cream Biscuits', 'Gourmet collection', 'Wafers', 'Salted & Plain', 'Cookies', 'Marie & Digestive', 'Cakes & Pies', 'Healthy Snacking', 'Rusk', 'Gift Boxes', 'Fresh Bakery']

CATEGORY: Cereals and Breakfast
['Batters', 'Ready Mixes', 'Pancake Mixes', 'Seeds and trail Mixes', 'Kids Cereals', 'Muesli & Granola', 'Oats', 'Peanut Butters', 'Energy Bars', 'Flakes']

CATEGORY: Chips and Namkeens
['Bhujia and Namkeens', 'Chips and Crisps', 'Makhana & Dry Fruits', 'Gift Hampers', 'Nachos', 'Popcorn']

CATEGORY: Chocolates
['Shared Packs', 'Milk Chocolates', 'Dark Chocolates', 'Gift Boxes', 'Premium', 'Wafers', 'Kunafa Chocolate', 'Gourmet collection', 'Candies & More', 'Gums & Mint']

CATEGORY: Cold Drinks and Juices
['Coconut Water', 'Ice Tea & Kombucha', 'Soda and Mixers', 'Mango Drinks', 'Milk Based Drinks', 'Soft Drinks', 'Water and Ice Cubes', 'Energy Drinks', 'Juices and Fruit Drinks', 'Fresh Juices', 'Cold Coffee']

CATEGORY: Dairy, Bread and Eggs
['Bread and Buns', 'Cheese', 'Cream and Condensed Milk', 'Curd and Yogurts', 'Milkshakes and More', 'Lassi and Buttermilk', 'Milk', 'Butter', 'Paneer and Tofu', 'Eggs']

CATEGORY: Feminine Hygiene
['Sanitary Pads', 'Period Panties and Liners', 'Disposal Bags and Cramp Relief', 'Hair Removal', 'Menstrual Cups and Tampons', 'Intimate Wipes and Wash']

CATEGORY: Hair Care
['Hair Oils and Serums', 'Conditioners & Masks', 'Hair Colour', 'Hair Dryers and Stylers', 'Hair Styling Gels & Creams', 'Shampoo', 'Premium Brands', 'Combs & Brushes', 'Hair Supplements']

CATEGORY: Ice Creams and Frozen Desserts
['Tubs & Party Packs', 'Cones', 'Sticks', 'Cups', 'Guiltfree', 'Real Fruit', 'Gourmet', 'Kulfi', 'Cakes & Sandwiches', 'Rare Finds', 'Regional Favorites', 'Syrups', 'Premium']

CATEGORY: Makeup
['Eyes', 'Face', 'Tools & Brushes', 'Eye lens', 'Lips', 'Nails']

CATEGORY: Paan Corner
['Paan and Mouth Fresheners', 'Gum and Mint']

CATEGORY: Skincare
['Creams & Moisturizers', 'Masks & Cleansers', 'Face wash and scrubs', 'Sunscreen', 'Body Lotions', 'Beauty Supplements', 'Serums, Toners']

CATEGORY: Sweet Corner
['Cakes and Pies', 'Gulab Jamun', 'Mysore Pak', 'Ladoos', 'Rasgulla', 'Rasmalai', 'Kaju Katli & Barfi', 'Chocofills', 'Dry Fruit Sweets', 'Gulkand & Paan', 'Chikki', 'Dessert Mixes', 'Cream Biscuits', 'Pedhas']

***Insights :***
___________________

    * No specific inconsistencies noticed accross department-category or category-subcategory combinations

**9) Suspicious Value Checking**

In [99]:
def find_suspicious_values(df, column_name):
    suspicious_values = [
        'null', 'none', 'n/a', 'na', 'nil', 'not available',
        'not applicable', '-', '--', '0', ''
    ]
    
    mask = (
        df2[column_name].isna() |
        df2[column_name].astype(str).str.strip().str.lower().isin(suspicious_values) |
        df2[column_name].str.fullmatch(r'\d+') |   # numeric only
        (df2[column_name].str.len() < 3)    # too short
        )
    
    df_suspicious = df2[mask]
    print(f"Number of suspicious values in '{column_name}': {len(df_suspicious)}")
    return df_suspicious[column_name].unique()

print(find_suspicious_values(df2, 'product_name'))
print(find_suspicious_values(df2, 'brand_name'))
print(find_suspicious_values(df2, 'store_name_location'))
print(find_suspicious_values(df2, 'department'))
print(find_suspicious_values(df2, 'category'))
print(find_suspicious_values(df2, 'sub_category'))

Number of suspicious values in 'product_name': 0
[]
Number of suspicious values in 'brand_name': 2615
['921' 'SS' 'Yu' nan 'P' 'Go' 'RG' 'He' 'Jo' 'C4' 'SP' 'Ob' 'Lu']
Number of suspicious values in 'store_name_location': 0
[]
Number of suspicious values in 'department': 0
[]
Number of suspicious values in 'category': 0
[]
Number of suspicious values in 'sub_category': 0
[]

In [100]:
def find_suspicious_values(df, column_name):
    suspicious_values = [
        'null', 'none', 'n/a', 'na', 'nil', 'not available',
        'not applicable', '-', '--', '0', ''
    ]
    
    mask = (
        df1[column_name].isna() |
        df1[column_name].astype(str).str.strip().str.lower().isin(suspicious_values) |
        df1[column_name].str.fullmatch(r'\d+') |   # numeric only
        (df1[column_name].str.len() < 3)    # too short
        )
    
    df_suspicious = df1[mask]
    print(f"Number of suspicious values in '{column_name}': {len(df_suspicious)}")
    return df_suspicious[column_name].unique()

print(find_suspicious_values(df1, 'product_name'))
print(find_suspicious_values(df1, 'brand_name'))
print(find_suspicious_values(df1, 'store_name_location'))
print(find_suspicious_values(df1, 'department'))
print(find_suspicious_values(df1, 'category'))
print(find_suspicious_values(df1, 'sub_category'))

Number of suspicious values in 'product_name': 0
[]
Number of suspicious values in 'brand_name': 3547
['921' nan 'Yu' 'Go' 'Jo' 'P' 'SP' 'He' 'Ob']
Number of suspicious values in 'store_name_location': 0
[]
Number of suspicious values in 'department': 0
[]
Number of suspicious values in 'category': 0
[]
Number of suspicious values in 'sub_category': 0
[]

In [102]:
 #Check for numeric columns that should not have negative values or zero

numeric_columns = ['store_id','pin_code','unique_id','product_grammage','net_quantity', 'item_mrp','item_selling_price', 'product_price','promo_offer_price','discount_in_percent','stock_count']

print("Checking price field separators (should use dot '.' not comma ','):\n")

for col in numeric_columns:
    if col in df2.columns:
        # Find rows with comma in price field
        comma_values = df2[df2[col].astype(str).str.contains(',', na=False)]
        invalid_values = df2[pd.to_numeric(df2[col], errors='coerce') <= 0]
        
        if len(comma_values) > 0:
            print(f"❌ {col}: Found {len(comma_values)} values with COMMA separator")
            print(f"   Sample: {comma_values[col].head(3).tolist()}")
        else:
            print(f"✓ {col}: All values use dot (.) or are numeric")
        if len(invalid_values) > 0:
            print(f"❌ {col}: Found {len(invalid_values)} values that are <= 0")
            print(f"   Sample: {invalid_values[col].head(3).tolist()}")
        else:
            print(f"✓ {col}: All values are greater than 0")
    else:
        print(f"⚠ {col}: Column not found in data")
    print()

Checking price field separators (should use dot '.' not comma ','):

✓ store_id: All values use dot (.) or are numeric
✓ store_id: All values are greater than 0

✓ pin_code: All values use dot (.) or are numeric
✓ pin_code: All values are greater than 0

✓ unique_id: All values use dot (.) or are numeric
✓ unique_id: All values are greater than 0

✓ product_grammage: All values use dot (.) or are numeric
✓ product_grammage: All values are greater than 0

✓ net_quantity: All values use dot (.) or are numeric
✓ net_quantity: All values are greater than 0

✓ item_mrp: All values use dot (.) or are numeric
✓ item_mrp: All values are greater than 0

✓ item_selling_price: All values use dot (.) or are numeric
✓ item_selling_price: All values are greater than 0

✓ product_price: All values use dot (.) or are numeric
✓ product_price: All values are greater than 0

✓ promo_offer_price: All values use dot (.) or are numeric
✓ promo_offer_price: All values are greater than 0

✓ discount_in_percent: All values use dot (.) or are numeric
❌ discount_in_percent: Found 287593 values that are <= 0
   Sample: [0, 0, 0]

✓ stock_count: All values use dot (.) or are numeric
❌ stock_count: Found 384561 values that are <= 0
   Sample: [0, 0, 0]

In [32]:
# Check for numeric columns that should not have negative values or zero

numeric_columns = ['store_id','pin_code','unique_id','product_grammage','net_quantity', 'item_mrp','item_selling_price', 'product_price','promo_offer_price','discount_in_percent','stock_count']

print("Checking price field separators (should use dot '.' not comma ','):\n")

for col in numeric_columns:
    if col in df2.columns:
        # Find rows with comma in price field
        comma_values = df2[df2[col].astype(str).str.contains(',', na=False)]
        invalid_values = df2[pd.to_numeric(df2[col], errors='coerce') <= 0]
        
        if len(comma_values) > 0:
            print(f"❌ {col}: Found {len(comma_values)} values with COMMA separator")
            print(f"   Sample: {comma_values[col].head(3).tolist()}")
        else:
            print(f"✓ {col}: All values use dot (.) or are numeric")
        if len(invalid_values) > 0:
            print(f"❌ {col}: Found {len(invalid_values)} values that are <= 0")
            print(f"   Sample: {invalid_values[col].head(3).tolist()}")
        else:
            print(f"✓ {col}: All values are greater than 0")
    else:
        print(f"⚠ {col}: Column not found in data")
    print()

Checking price field separators (should use dot '.' not comma ','):

✓ store_id: All values use dot (.) or are numeric
✓ store_id: All values are greater than 0

✓ pin_code: All values use dot (.) or are numeric
✓ pin_code: All values are greater than 0

✓ unique_id: All values use dot (.) or are numeric
✓ unique_id: All values are greater than 0

✓ product_grammage: All values use dot (.) or are numeric
✓ product_grammage: All values are greater than 0

✓ net_quantity: All values use dot (.) or are numeric
✓ net_quantity: All values are greater than 0

✓ item_mrp: All values use dot (.) or are numeric
✓ item_mrp: All values are greater than 0

✓ item_selling_price: All values use dot (.) or are numeric
✓ item_selling_price: All values are greater than 0

✓ product_price: All values use dot (.) or are numeric
✓ product_price: All values are greater than 0

✓ promo_offer_price: All values use dot (.) or are numeric
✓ promo_offer_price: All values are greater than 0

✓ discount_in_percent: All values use dot (.) or are numeric
❌ discount_in_percent: Found 315363 values that are <= 0
   Sample: [0, 0, 0]

✓ stock_count: All values use dot (.) or are numeric
❌ stock_count: Found 495207 values that are <= 0
   Sample: [0, 0, 0]

In [34]:
# check for stock_count and out_of_stock_flag consistency
# Convert stock_count to numeric if needed
df2['stock_count'] = pd.to_numeric(
    df2['stock_count'], errors='coerce'
)

# Find rows violating the rule
invalid_rows = df2[
    (
        (df2['stock_count'] == 0) &
        (df2['out_of_stock_flag'].str.strip().str.lower() != 'yes')
    )
    # |
    # (
    #     (df2['stock_count'] > 0) &
    #     (df2['out_of_stock_flag'].str.strip().str.lower() != 'no')
    # )
]

print(f"Number of violating rows: {len(invalid_rows)}")
print(invalid_rows)

Number of violating rows: 0
Empty DataFrame
Columns: [crawl_date_and_time, platform_name, store_id, store_name_location, city, pin_code, unique_id, product_id_upc_ean, department, category, sub_category, product_type, brand_name, product_name, product_description, product_grammage, package_type, net_quantity, variants, item_mrp, item_selling_price, out_of_stock_flag, discount_flag, product_price, unit_price, promo_offer_description, promo_offer_price, discount_in_percent, stock_count, product_url, product_image_urls]
Index: []

[0 rows x 31 columns]

***Insights :***
____________

    * Suspicious values noticed on brand_name column.
    * Checked website to confirm whether these brand_names really exists or not.
    * Most of them really exists, but urls of some brands are not able to access.
    * Complete urls on brand_name 'RG' and 'C4' and some urls on other brands are not accessible, which is a critical issue.

**10) Price Anomalies**

In [35]:
def check_negative_and_zero(df, column):
    """
    Returns rows where the given column has:
    - negative values (< 0)
    - zero values (== 0)
    """

    # Ensure numeric (safe for real-world messy data)
    df2[column] = pd.to_numeric(df2[column], errors='coerce')

    negative_values = df2[df2[column] < 0]
    zero_values = df2[df2[column] == 0]

    return {
        "negative_values": negative_values[['unique_id', column]],
        "zero_values": zero_values[['unique_id', column]]
    }

print("\nItem MRP:")
print(check_negative_and_zero(df2, 'item_mrp'))
print("\nItem Selling Price:")
print(check_negative_and_zero(df2, 'item_selling_price'))
print("\nProduct Price:")
print(check_negative_and_zero(df2, 'product_price'))
print("\nPromo Offer Price:")
print(check_negative_and_zero(df2, 'promo_offer_price'))

Item MRP:
{'negative_values': Empty DataFrame
Columns: [unique_id, item_mrp]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, item_mrp]
Index: []}

Item Selling Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, item_selling_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, item_selling_price]
Index: []}

Product Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, product_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, product_price]
Index: []}

Promo Offer Price:
{'negative_values': Empty DataFrame
Columns: [unique_id, promo_offer_price]
Index: [], 'zero_values': Empty DataFrame
Columns: [unique_id, promo_offer_price]
Index: []}

In [36]:
# check if item_selling_price is greater than item_mrp
df2[df2['item_selling_price'] > df2['item_mrp']][['unique_id', 'item_selling_price', 'item_mrp']]

Empty DataFrame
Columns: [unique_id, item_selling_price, item_mrp]
Index: []

In [38]:
# check if discount_in_percent is greater than 0 and item_selling_price is greater than or equal to item_mrp
df2[
    (df2['discount_in_percent'] > 0) &
    (df2['item_selling_price'] >= df2['item_mrp'])
][['unique_id', 'item_selling_price', 'item_mrp', 'discount_in_percent']]

Empty DataFrame
Columns: [unique_id, item_selling_price, item_mrp, discount_in_percent]
Index: []

In [39]:
# check if promo_offer_description is not null and promo_offer_price is null
df2[
    (df2['promo_offer_description'].notnull()) &

    (df2['promo_offer_price'].isnull())][['unique_id', 'promo_offer_description', 'promo_offer_price']]

Empty DataFrame
Columns: [unique_id, promo_offer_description, promo_offer_price]
Index: []

In [41]:
# check if promo_offer_price is not null and promo_offer_price is not equal to item_selling_price
df2[
    (df2['promo_offer_price'].notnull()) &
    (df2['promo_offer_price'] != df2['item_selling_price'])
][['unique_id', 'promo_offer_description', 'promo_offer_price', 'item_selling_price']]

Empty DataFrame
Columns: [unique_id, promo_offer_description, promo_offer_price, item_selling_price]
Index: []

In [42]:
# check if out_of_stock_flag is True and stock_count is greater than 0
df2[
    (df2['out_of_stock_flag'] == True) &
    (df2['stock_count'] > 0)
][['unique_id', 'store_id', 'product_id_upc_ean']]

Empty DataFrame
Columns: [unique_id, store_id, product_id_upc_ean]
Index: []

***Insights :***
____________

    * No specific anomalies found on price related columns
    * All such columns are greater than 0.
    * selling price and mrp are equal.
    * selling price is always less than mrp if discount percentage exists.
    * if promo offer description exists, promo offer price also exists.
    * If out of stock flag true, stock count is zero.

**11) URL Checking**

In [43]:
total_records = len(df2)
missing_urls = df2['product_url'].isnull().sum()
unique_urls = df2['product_url'].nunique(dropna=True)
duplicate_urls = df2['product_url'].duplicated().sum()

print("URL ANALYSIS SUMMARY")
print("-" * 40)
print(f"Total records           : {total_records}")
print(f"Missing URLs            : {missing_urls}")
print(f"Unique URLs             : {unique_urls}")
print(f"Duplicate URLs          : {duplicate_urls}")
print(f"Uniqueness %            : {(unique_urls/total_records)*100:.2f}%")

URL ANALYSIS SUMMARY
----------------------------------------
Total records           : 1207644
Missing URLs            : 0
Unique URLs             : 25620
Duplicate URLs          : 1182024
Uniqueness %            : 2.12%

In [45]:
# Duplicate URL Records
# ----------------------------
duplicate_url_df = df1[
    df1['product_url'].duplicated(keep=False)
].sort_values('product_url')

print("\nDuplicate URL Records:")
print(duplicate_url_df[['unique_id', 'product_name', 'product_url']].head())

Duplicate URL Records:
          unique_id  \
479771   1LXU4DWKTR
1099208  4F3BY2RVMI
155890   TBDNCNO3QF
280693   LFOUSF1715
1074448  JG9PC3SQQD

                                                                                   product_name  \
479771   FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
1099208  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
155890   FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
280693   FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
1074448  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying

                                              product_url
479771   https://www.swiggy.com/instamart/item/0009OYBIMZ
1099208  https://www.swiggy.com/instamart/item/0009OYBIMZ
155890   https://www.swiggy.com/instamart/item/0009OYBIMZ
280693   https://www.swiggy.com/instamart/item/0009OYBIMZ
1074448  https://www.swiggy.com/instamart/item/0009OYBIMZ

In [44]:
# Duplicate URL Records
# ----------------------------
duplicate_url_df = df2[
    df2['product_url'].duplicated(keep=False)
].sort_values('product_url')

print("\nDuplicate URL Records:")
print(duplicate_url_df[['unique_id', 'product_name', 'product_url']].head())

Duplicate URL Records:
         unique_id  \
231738  9BLMI0XJR9
80583   TJU8UPYVBX
392295  MZWQTDH5KD
800665  F8JXFB266R
535836  1LVN1UXC2F

                                                                                  product_name  \
231738  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
80583   FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
392295  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
800665  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying
535836  FACES CANADA Ultime Pro Splash Nail Enamel - Pink Rouge 103 (8ml)Glossy | Quick Drying

                                             product_url
231738  https://www.swiggy.com/instamart/item/0009OYBIMZ
80583   https://www.swiggy.com/instamart/item/0009OYBIMZ
392295  https://www.swiggy.com/instamart/item/0009OYBIMZ
800665  https://www.swiggy.com/instamart/item/0009OYBIMZ
535836  https://www.swiggy.com/instamart/item/0009OYBIMZ

In [47]:
# ----------------------------
# URL Format Validation
# ----------------------------

# Regex for HTTP/HTTPS URLs
url_pattern = re.compile(
    r'^(https?://)'               # http:// or https://
    r'([\w.-]+)'                  # domain
    r'(\.[a-zA-Z]{2,})'           # TLD
    r'([/\w .?%&=+-]*)?$'         # path/query
)

invalid_urls = df2[
    df2['product_url'].notnull() &
    ~df2['product_url'].astype(str).str.match(url_pattern)
]

print("\nInvalid URL Format Count:", len(invalid_urls))

print("\nSample Invalid URLs:")
print(
    invalid_urls[
        ['unique_id', 'product_name', 'product_url']
    ].head(10)
)

Invalid URL Format Count: 0

Sample Invalid URLs:
Empty DataFrame
Columns: [unique_id, product_name, product_url]
Index: []

In [48]:
# ----------------------------
# URLs without http/https
# ----------------------------
missing_protocol = df2[
    df2['product_url'].notnull() &
    ~df2['product_url'].astype(str).str.startswith(('http://', 'https://'))
]

print("\nURLs missing protocol (http/https):", len(missing_protocol))

print(
    missing_protocol[
        ['unique_id', 'product_name', 'product_url']
    ].head()
)

URLs missing protocol (http/https): 0
Empty DataFrame
Columns: [unique_id, product_name, product_url]
Index: []

***Insights***
___________
* Format and pattern of urls are correct
* But 1210545 duplicate urls present on the dataset.
* However these duplcates have different store location and different price range.

**12) City, Store, Pincode Analysis**

In [49]:
# Missing percentage by city

missing_by_city = (
    df2.groupby('city')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by city

df2['out_of_stock_flag_num'] = (
    df2['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_city = (
    df2.groupby('city')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by city

discount_by_city = (
    df2.groupby('city')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by city

products_by_city = (
    df2.groupby('city')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
city_analysis = (
    missing_by_city
    .merge(stockout_by_city, on='city', how='outer')
    .merge(discount_by_city, on='city', how='outer')
    .merge(products_by_city, on='city', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nCITY ANALYSIS SUMMARY")
print("--------------------------------")
print(city_analysis)

/tmp/ipykernel_6156/382486877.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

CITY ANALYSIS SUMMARY
--------------------------------
      city  missing_perc  stockout_perc  avg_discount_perc  product_count
0    Delhi     16.129584      42.925439          14.538826         689955
1  Gurgaon     16.129551      36.495427          15.484797         293784

In [50]:
# Missing percentage by store

missing_by_store = (
    df2.groupby('store_name_location')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by store

df2['out_of_stock_flag_num'] = (
    df2['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_store = (
    df2.groupby('store_name_location')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by store

discount_by_store = (
    df2.groupby('store_name_location')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by store

products_by_store = (
    df2.groupby('store_name_location')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
store_analysis = (
    missing_by_store
    .merge(stockout_by_store, on='store_name_location', how='outer')
    .merge(discount_by_store, on='store_name_location', how='outer')
    .merge(products_by_store, on='store_name_location', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nSTORE ANALYSIS SUMMARY")
print("--------------------------------")
print(store_analysis)

/tmp/ipykernel_6156/2116988899.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

STORE ANALYSIS SUMMARY
--------------------------------
                                                                                                                                             store_name_location  \
81                                                                                                Sector 12, Rama Krishna Puram, New Delhi, Delhi, 110022, India
26                                                                       B-304, Gharoli Rd, GD Colony, Phase 3, Gharoli Dairy Farm, Kondli, Delhi, 110096, India
84                                                                          Seohara Bijnor, Khizarabad Bhagol, New Friends Colony, Seohara, Delhi, 110065, India
92                                                       Ultra Dry Cleaners, Railway Road, Jhilmil Indl Area, Vivek Vihar Tehsil, Shahdara, Delhi, 110095, India
0                                                                              1, Asaf Ali Rd, Near DDA Complex, Kalyanpura, Chandni Chowk, Delhi, 110006, India
..                                                                                                                                                           ...
86                                                      South Indian Restaurant - Sangam, Shop No.:28A115, Jia Sarai, Hauz Khas, New Delhi, Delhi, 110016, India
68                                                          Parking Area, Jwalaheri Market, Rd Number 30, Jwalaheri Village, Paschim Vihar, Delhi, 110063, India
91                                                     The Royal Biryani House, R-Extn 90, Block N 2, Mohan Garden, Uttam Nagar, New Delhi, Delhi, 110059, India
31                                                                       Boom Plaza, Mall, Block C, Sushant Lok III, Sector 57, Gurugram, Haryana, 122011, India
97  Wow Gym, A-245 Upper Ground Floor Thokar No 6, Shaheen Bagh, Jamia Nagar, Okhla, Abul Fazal Enclave Part 2, Jamia Nagar, 2J, New Delhi, Delhi, 110025, India

    missing_perc  stockout_perc  avg_discount_perc  product_count
81     15.626107      50.235336          14.117719          15873
26     15.626085      44.422587          14.688498           6944
84     15.626077      43.410853          14.588458           9377
92     15.626065      53.640804          14.056799           7123
0      15.626059      65.692751          14.474848           9584
..           ...            ...                ...            ...
86     15.625000      36.887608          15.574152           7182
68     15.625000      30.277578          15.678826           9956
91     15.625000      54.374963          14.164684          14249
31     15.625000      36.317914          15.595460          12421
97     15.625000      24.328845          15.403697           9518

[99 rows x 5 columns]

In [51]:
# Missing percentage by pincode

missing_by_pincode = (
    df2.groupby('pin_code')
      .apply(lambda x: x.isnull().mean().mean() * 100)
      .reset_index(name='missing_perc')
      .sort_values('missing_perc', ascending=False)
)

# Stockout percentage by pincode

df2['out_of_stock_flag_num'] = (
    df2['out_of_stock_flag']
    .astype(str)
    .str.lower()
    .isin(['true', 'yes', '1', 'y'])
    .astype(int)
)

stockout_by_pincode = (
    df2.groupby('pin_code')['out_of_stock_flag_num']
      .mean()
      .mul(100)
      .reset_index(name='stockout_perc')
      .sort_values('stockout_perc', ascending=False)
)

# Discount percentage by pincode

discount_by_pincode = (
    df2.groupby('pin_code')['discount_in_percent']
      .mean()
      .reset_index(name='avg_discount_perc')
      .sort_values('avg_discount_perc', ascending=False)
) 

# Number of unique products by pincode

products_by_pincode = (
    df2.groupby('pin_code')['unique_id']
      .nunique()
      .reset_index(name='product_count')
      .sort_values('product_count', ascending=False)
)

# Combine all metrics
pincode_analysis = (
    missing_by_pincode
    .merge(stockout_by_pincode, on='pin_code', how='outer')
    .merge(discount_by_pincode, on='pin_code', how='outer')
    .merge(products_by_pincode, on='pin_code', how='outer')
    .sort_values('missing_perc', ascending=False)
)

print("\nPINCODE ANALYSIS SUMMARY")
print("--------------------------------")
print(pincode_analysis)

/tmp/ipykernel_6156/1523724332.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.isnull().mean().mean() * 100)

PINCODE ANALYSIS SUMMARY
--------------------------------
    pin_code  missing_perc  stockout_perc  avg_discount_perc  product_count
10    110022     15.626107      50.235336          14.117719          15873
44    110096     15.626085      44.422587          14.688498           6944
1     110006     15.626059      65.692751          14.474848           9584
30    110070     15.626045      41.090392          14.272347           9646
29    110065     15.625923      45.721741          14.354963          16420
43    110095     15.625866      47.695546          14.110348          14583
9     110019     15.625836      38.047606          14.663118          15015
40    110092     15.625829      50.122003          14.243741          15372
51    122017     15.625814      41.928485          15.552942          28175
5     110015     15.625806      38.594908          14.362681          25100
55    122052     15.625803      33.721528          15.585888           9395
31    110074     15.625766      36.916002          14.746229          13446
54    122051     15.625752      30.155548          15.596376           9919
47    122005     15.625747      36.215958          15.521500          10600
25    110052     15.625737      35.146608          14.737678          10206
48    122006     15.625730      57.738142          15.953813          10581
11    110024     15.625727      47.283421          14.267172          24179
7     110017     15.625717      48.909500          14.404702          17561
53    122022     15.625714      35.324122          15.290929          21395
0     110005     15.625703      57.867518          14.467149          18359
26    110053     15.625687      55.758442          14.039600           7313
24    110051     15.625672      45.999140          14.271671          15068
35    110085     15.625616      42.138461          14.450273          36984
39    110091     15.625568      39.930972          14.694532          22317
3     110008     15.625533      48.690608          14.650943           9547
18    110043     15.625523      36.807300          14.799598           9671
46    122003     15.625523      37.481811          15.051096          49679
2     110007     15.625522      32.545713          14.853386          10133
19    110044     15.625512      38.378378          15.987715           9932
22    110047     15.625492      28.742326          15.697151          10172
15    110037     15.625490      31.568021          14.986133          20986
38    110088     15.625470      45.438121          14.463114          16163
34    110084     15.625469      37.158921          14.797451          10695
41    110093     15.625454      46.475942          14.008132          17602
42    110094     15.625443      28.854063          15.138278          11412
56    122102     15.625442      31.858353          15.710700          40398
8     110018     15.625433      47.203362          14.300263          17609
20    110045     15.625428      50.417379          13.874273          24437
45    122001     15.625420      37.663136          15.350222          42319
32    110075     15.625413      45.786758          14.146537          25364
13    110027     15.625356      48.906606          14.118223           7064
57    122505     15.625350      26.906582          15.868842          21961
4     110009     15.625331      55.199408          14.369301           7570
17    110042     15.625324      40.012439          14.737017           7776
27    110059     15.625316      41.444334          14.577849          56252
33    110080     15.625305      50.239024          14.065707          17437
37    110087     15.625296      27.560398          15.193937           8511
36    110086     15.625283      22.783664          15.543240           8786
49    122009     15.625269      37.440901          15.555532          18964
52    122018     15.625264      37.873150          15.562114          19798
16    110041     15.625239      34.062237          15.187629          10570
21    110046     15.625232      34.122449          14.632950          10872
14    110028     15.625158      48.474576          14.146016          16836
23    110049     15.625150      59.158986          13.864055          17707
28    110063     15.625145      31.781038          15.325471          17210
12    110025     15.625000      24.328845          15.403697           9518
50    122011     15.625000      36.317914          15.595460          12421
6     110016     15.625000      36.887608          15.574152           7182

***Insights :***
__________________

    * missing percentage is almost equally distributed over all dimensions
    * stockout percentage and product count has significant hike based on some cities, stores, pincodes etc.
    * However discount_percentage is also have almost equal distribution over different dimensions

**13) High Price Variations**

In [52]:
# Price Variation Analysis
price_variation = (
    df2.groupby('product_id_upc_ean')
      .agg(
          product_name=('product_name', 'first'),
          min_price=('item_selling_price', 'min'),
          max_price=('item_selling_price', 'max'),
          mean_price=('item_selling_price', 'mean'),
          num_locations=('city', 'nunique')
      )
      .reset_index()
)

# Calculate percentage variation
price_variation['price_variation_pct'] = (
    (price_variation['max_price'] - price_variation['min_price'])
    / price_variation['min_price'] * 100
).round(2)

# Flag products having >30% variation
high_variation = price_variation[
    price_variation['price_variation_pct'] > 30
].sort_values('price_variation_pct', ascending=False)

print(high_variation.head(20))

      product_id_upc_ean  \
1335          1UTQYINACZ
18885         QGC0H72GHL
23509         X1UP6TZ2CH
4345          63FRSPU0EC
13501         IWYG3OXTEA
7365          ACD1E7H9RX
2098          2VUFV953WU
10567         ESWAQTN109
12099         GY12SME90J
9171          CWA1JGHGHP
17465         OED2LYHABR
15862         M9QXZYJMLV
18279         PKGH8JLDJ3
12203         H3O2WU1A10
15414         LM3GFB266O
5072          72LBIS8S50
23294         WR36KX1BPP
24161         XZEKYCTJGF
2180          30EEACLT1J
16999         NRRQJ4R2XW

                                                                                     product_name  \
1335                                                    The Health Factory Berry Blast Mini Cakes
18885                                                              Bikano Panjeeri Laddu Spl B1G1
23509                                            CLEAR Premium Drinking Water with Added Minerals
4345                                               NOICE Natural Coconut Water (No Preservatives)
13501                                    Peping Digestive Shot - Orange, Spearmint and Probiotics
7365                                                   Tropicana Guava Delight Juice (Tetra Pack)
2098         Eat better co - millet namkeen - mango achari - roasted healthy snacks - no palm oil
10567                                                      Himalayan Natural Mineral Water Bottle
12099                                    NOICE Coconut Water With Malai Chunks (No Preservatives)
9171                                               Red Bull The Yellow Edition Energy Drink 250ml
17465                                   NOICE Homestyle Janthikalu (No Palm Oil Namkeen & Snacks)
15862                                      Red Bull Energy Drink Watermelon The Red Edition 250ml
18279                                                  Red Bull Energy Drink - Sugar Free, 250 ml
12203                                                                            POLO Breath Mint
15414                                                                      Chokhi Dhani Pav Bhaji
5072   SOFTSENS Kids Teddy Bear Soap|Hypoallergenic|Dermatologist Tested|Shea Butter & Milk Cream
23294                                                                           Milky Mist Paneer
24161                                                  The Baker's Dozen Zero Maida Banana Muffin
2180                                                              Himalayan Natural Mineral Water
16999                                            The Baker's Dozen Zero Maida Donut Cake, Eggless

       min_price  max_price  mean_price  num_locations  price_variation_pct
1335          50      10034  188.612245              2             19968.00
18885         10        600  510.909091              2              5900.00
23509          5        216   27.141414              2              4220.00
4345          29        936  269.738693              2              3127.59
13501         14        450  114.833333              2              3114.29
7365           5        160   79.304348              2              3100.00
2098           5        144   93.411111              2              2780.00
10567         18        480  399.953488              2              2566.67
12099         45       1080  264.798995              2              2300.00
9171         125       2799  861.660000              2              2139.20
17465         10        220  106.082353              2              2100.00
15862        125       2700  806.313131              2              2060.00
18279        125       2520  608.010000              2              1916.00
12203         10        200   33.030303              2              1900.00
15414          9        179  150.666667              1              1888.89
5072          57       1094  116.050000              2              1819.30
23294         35        602  528.865169              2              1620.00
24161         10        160   60.454237              2              1500.00
2180          44        701  245.070000              2              1493.18
16999          7        109   39.931646              2              1457.14

In [53]:
# check if any product has more than one selling price with same grammage across different stores
price_variation = (
    df2.groupby(['product_name', 'product_grammage'])['item_selling_price']
      .nunique()
      .reset_index(name='price_count')
)

# Keep only products having more than one selling price
price_variation = price_variation[
    price_variation['price_count'] > 1
]

print(price_variation)

                                                                                                                                product_name  \
0      100% Whole Wheat Bread 400GM & Pintola All Natural Peanut Butter Crunchy, Unsweetened, Protein, Gluten Free, Vegan, Cholesterol Free)
2                                                                                                                          10X Classic Besan
3                                                                                                                          10X Classic Besan
4                                                                                                              10X Classic Chakki Fresh Atta
5                                                                                                              10X Classic Chakki Fresh Atta
...                                                                                                                                      ...
30738                                                         plum bodylovin shower gel - hawaiian rumba and deodorant roll-on and body mist
30739                                                                                     plum coconut milk & peptides shampoo & conditioner
30740                                                        plum coconut milk & peptides strength & shine shampoo, conditioner & hair serum
30741                                                                              plum green tea alcohol free toner and cleansing face wash
30742                                                               plum green tea oil free moisturiser and free toner & cleansing face wash

      product_grammage  price_count
0              1 Combo            2
2                 1 kg            3
3                500 g            2
4                10 kg            2
5                 5 kg            2
...                ...          ...
30738          1 combo            2
30739          1 combo            3
30740          1 combo            3
30741          1 combo            3
30742          1 combo            3

[11862 rows x 3 columns]

In [54]:
# Group by product_name and product_grammage and find price varation statistics
price_analysis = (
    df2.groupby(['product_name', 'product_grammage'])['item_selling_price']
      .agg(['count', 'min', 'max', 'mean', 'std'])
      .reset_index()
)

# Calculate price difference and percentage variation
price_analysis['price_diff'] = (
    price_analysis['max'] - price_analysis['min']
)

price_analysis['pct_variation'] = (
    (price_analysis['price_diff'] / price_analysis['mean']) * 100
).round(2)

# Flag products with >20% variation
high_variation = price_analysis[
    price_analysis['pct_variation'] > 20
].sort_values('pct_variation', ascending=False)

print(high_variation)

                                                                                                                                                    product_name  \
27686                                                                                                              The Health Factory Berry Blast Mini Cakes 70g
24070                                                                 SOFTSENS Kids Teddy Bear Soap|Hypoallergenic|Dermatologist Tested|Shea Butter & Milk Cream
9384                                                                                                                                     Frubon Premium Dahi Cup
22713                                                                                                   RAS Luxory Skincare Kashmiri Lavender Pure Essential Oil
11894                                                                                                              Imli Blast - Sweet Chilli Fruit Bars Fun Pack
...                                                                                                                                                          ...
19006                                                                            Nature's Essence Professional Facialist Daily Bright Face Wash, with 2% Arbutin
2946   BeeBaby Ease Wide Neck Colour Baby Feeding Bottle. Fast Flow Anti-Colic Silicone Nipple for infants, and newborns. 100% BPA Free. 4 months+ (150ml, Blue)
9524                                                                                                                        GUBB Glass Powder Pumice Stone White
19544                                                                                                 Nua 360° Comfort Disposable Period Panties (S-M, 5 Pieces)
5738                                                                                                   Coca-Cola Zero Soft Drink Can 300ml, Sprite Zero Can300ml

      product_grammage  count   min    max         mean          std  \
27686         70 g x 2     25   100  10034   497.360000  1986.800000
24070             75 g     20    57   1094   116.050000   230.192477
9384             400 g     56    47    545    55.892857    66.548049
22713            10 ml    204  1100  11000  1245.803922  1194.597032
11894             42 g     77    30    288    33.350649    29.401829
...                ...    ...   ...    ...          ...          ...
19006            100 g     16   212    255   214.687500    10.750000
2946           1 Piece      6   129    160   154.833333    12.655697
9524           1 Piece      8   112    135   114.875000     8.131728
19544         5 pieces     81   169    203   169.839506     5.309088
5738           1 Combo     95    74     90    79.957895     5.402749

       price_diff  pct_variation
27686        9934        1997.35
24070        1037         893.58
9384          498         890.99
22713        9900         794.67
11894         258         773.60
...           ...            ...
19006          43          20.03
2946           31          20.02
9524           23          20.02
19544          34          20.02
5738           16          20.01

[3589 rows x 9 columns]

In [55]:
# check if any product has more than one selling price with same grammage on same store
price_variation = (
    df2.groupby(['store_id', 'product_name', 'product_grammage','product_url'])['item_selling_price']
      .agg(['min', 'max', 'nunique', 'count'])
      .reset_index()
)

# Keep only products having more than one unique selling price
price_variation = price_variation[
    price_variation['nunique'] > 1
]

# Calculate price difference
price_variation['price_difference'] = (
    price_variation['max'] - price_variation['min']
)

print(price_variation.sort_values('price_difference', ascending=False))

        store_id  \
83751    1099458
720474   1403179
568635   1401649
412457   1397028
425518   1398454
...          ...
808522   1404165
808520   1404165
153178   1380671
856480   1404596
494950   1400547

                                                                                                                                                                                   product_name  \
83751                                                                                                                  Yogabar 26g Protein Shake Cold Coffee, No Added Sugar, Protein Milkshake
720474                                                                                                                                                           Geisha Chocolate Heart Tin Box
568635                                                                                                                                                   RITTER SPORT Hazelnuts, Milk Chocolate
412457                                         Beardo Activated Charcoal Face Wash for men | For Deep Pore Cleaning and Removes Dirt | face wash for acne and pimples | face wash for oily skin
425518                                         Beardo Activated Charcoal Face Wash for men | For Deep Pore Cleaning and Removes Dirt | face wash for acne and pimples | face wash for oily skin
...                                                                                                                                                                                         ...
808522  Livon Hair Serum for Women & Men for Dry and Rough Hair Bottle 50ml & Parachute Advansed Gold Coconut Hair Oil, With Pure Coconut Oil, Vitamin E for long, Strong & Gorgeous Hai 100mlr
808520                                     Livon Anti-Frizz Hair Serum 50ml & Parachute Advansed Gold Coconut Hair Oil, With Pure Coconut Oil, Vitamin E for long, Strong & Gorgeous Hair 100ml
153178                                                                                          Britannia Milk Bikis Sandwich Biscuits & Britannia Treat Rich Creme Strawberry Flavoured Wafers
856480                                 Coco Charge 100% TENDER COCONUT WATER| NOT MADE FROM CONCENTRATE | NO CHEMICALS | NARIYAL PANI 200ml and Snackible Peri Peri Ragi Chips - High Fibre 55g
494950                                                                                                                                            The Baker's Dozen Choco Chip Muffins, Eggless

       product_grammage                                       product_url  \
83751         24 Pieces  https://www.swiggy.com/instamart/item/51YDVLNEZN
720474            158 g  https://www.swiggy.com/instamart/item/MRHLAI6LWQ
568635            100 g  https://www.swiggy.com/instamart/item/FJ8RDO7Y1J
412457           200 ml  https://www.swiggy.com/instamart/item/YPZE8DDUFW
425518           200 ml  https://www.swiggy.com/instamart/item/YPZE8DDUFW
...                 ...                                               ...
808522          1 combo  https://www.swiggy.com/instamart/item/U65WC8BSKO
808520          1 combo  https://www.swiggy.com/instamart/item/WHTBKTNYVJ
153178          1 Combo  https://www.swiggy.com/instamart/item/UOYH20UEJ0
856480          1 Combo  https://www.swiggy.com/instamart/item/CR82O2Z99O
494950            180 g  https://www.swiggy.com/instamart/item/41GJ5FDU91

         min   max  nunique  count  price_difference
83751   1509  2075        2      2               566
720474   798  1199        2      2               401
568635   198   450        2      2               252
412457   319   499        2      2               180
425518   319   499        2      2               180
...      ...   ...      ...    ...               ...
808522   187   190        2      2                 3
808520   183   186        2      2                 3
153178    81    84        2      2                 3
856480    95    97        2      2                 2
494950   156   157        2      4                 1

[143 rows x 9 columns]

***Insights :***
_________________

    * Found price anomalies with high variation of price for the same product with the same grammage unit.
    * Multiple products are there with the same product_name, grammage, store_name, and different offer price.
    * The product_url of such products are too same and not accessible.

In [56]:
categories1 = set(df1['category'].dropna().unique())
categories2 = set(df2['category'].dropna().unique())

print("Categories only in df1:")
print(sorted(categories1 - categories2))

print("\nCategories only in df2:")
print(sorted(categories2 - categories1))

print("\nCommon categories:")
print(sorted(categories1 & categories2))

print("\nAre the category values identical?")
print(categories1 == categories2)

Categories only in df1:
[]

Categories only in df2:
[]

Common categories:
['Atta, Rice and Dal', 'Baby Care', 'Bath and Body', 'Biscuits and Cakes', 'Cereals and Breakfast', 'Chips and Namkeens', 'Chocolates', 'Cold Drinks and Juices', 'Dairy, Bread and Eggs', 'Feminine Hygiene', 'Hair Care', 'Ice Creams and Frozen Desserts', 'Makeup', 'Paan Corner', 'Skincare', 'Sweet Corner']

Are the category values identical?
True

In [57]:
subcategories1 = set(df1['sub_category'].dropna().unique())
subcategories2 = set(df2['sub_category'].dropna().unique())

print("Subcategories only in df1:")
print(sorted(subcategories1 - subcategories2))

print("\nSubcategories only in df2:")
print(sorted(subcategories2 - subcategories1))

print("\nCommon subcategories:")
print(sorted(subcategories1 & subcategories2))

print("\nAre the subcategory values identical?")
print(subcategories1 == subcategories2)

Subcategories only in df1:
[]

Subcategories only in df2:
[]

Common subcategories:
['Atta', 'Baby Bathing', 'Baby Cream & Lotions', 'Baby Diapers', 'Baby Food and Formula', 'Baby Hygiene', 'Baby Oil and Talc', 'Baby Oral Care', 'Baby Pharma', 'Baby Wipes', 'Baking Ingredients', 'Bath & Beauty gifts', 'Bath Accessories', 'Batters', 'Beauty Supplements', 'Besan, Sooji and Maida', 'Bhujia and Namkeens', 'Body Lotion & Oils', 'Body Lotions', 'Books and Toys', 'Bread and Buns', 'Butter', 'Cakes & Pies', 'Cakes & Sandwiches', 'Cakes and Pies', 'Candies & More', 'Cheese', 'Chikki', 'Chips and Crisps', 'Chocofills', 'Clothes & Accessories', 'Coconut Water', 'Cold Coffee', 'Combs & Brushes', 'Conditioners & Masks', 'Cones', 'Cookies', 'Cream Biscuits', 'Cream and Condensed Milk', 'Creams & Moisturizers', 'Cups', 'Curd and Yogurts', 'Dark Chocolates', 'Dessert Mixes', 'Disposal Bags and Cramp Relief', 'Dry Fruit Sweets', 'Eggs', 'Energy Bars', 'Energy Drinks', 'Eye lens', 'Eyes', 'Face', 'Face Care', 'Face wash and scrubs', 'Feeding and Teething Needs', 'Flakes', 'Fragrance & Talc', 'Fresh Juices', 'Gift Boxes', 'Gift Hampers', 'Gifts & More', 'Gourmet', 'Gourmet collection', 'Guiltfree', 'Gulab Jamun', 'Gulkand & Paan', 'Gum and Mint', 'Gums & Mint', 'Hair Colour', 'Hair Dryers and Stylers', 'Hair Oils and Serums', 'Hair Removal', 'Hair Styling Gels & Creams', 'Hair Supplements', 'Handwash', 'Healthy Snacking', 'Ice Tea & Kombucha', 'Intimate Wipes and Wash', 'Juices and Fruit Drinks', 'Kaju Katli & Barfi', 'Kids Cereals', 'Kulfi', 'Kunafa Chocolate', 'Ladoos', 'Lassi and Buttermilk', 'Lip care', 'Lips', 'Makhana & Dry Fruits', 'Mango Drinks', 'Marie & Digestive', 'Masks & Cleansers', 'Mens Perfume', 'Menstrual Cups and Tampons', 'Milk', 'Milk Based Drinks', 'Milk Chocolates', 'Milkshakes and More', 'Millets & Daliya', 'Mom Care', 'Muesli & Granola', 'Multi groomers', 'Mysore Pak', 'Nachos', 'Nails', 'Oats', 'Oral care', 'Other Flours', 'Paan and Mouth Fresheners', 'Pancake Mixes', 'Paneer and Tofu', 'Peanut Butters', 'Pedhas', 'Period Panties and Liners', 'Poha & Puffed Rice', 'Popcorn', 'Premium', 'Premium Brands', 'Rajma, Chola and Others', 'Rare Finds', 'Rasgulla', 'Rasmalai', 'Ready Mixes', 'Real Fruit', 'Regional Favorites', 'Rice', 'Roll on', 'Rusk', 'Salted & Plain', 'Sanitary Pads', 'Seeds and trail Mixes', 'Serums, Toners', 'Shampoo', 'Shared Packs', 'Shower gel', 'Soaps', 'Soda and Mixers', 'Soft Drinks', 'Sticks', 'Sunscreen', 'Syrups', 'Tools & Brushes', 'Toor, Moong and Urad', 'Travel Needs & Baby Gears', 'Tubs & Party Packs', 'Wafers', 'Water and Ice Cubes', 'Womens Perfume']

Are the subcategory values identical?
True

In [58]:
dep1 = set(df1['department'].dropna().unique())
dep2 = set(df2['department'].dropna().unique())

print("Departments only in df1:")
print(sorted(dep1 - dep2))

print("\nDepartments only in df2:")
print(sorted(dep2 - dep1))

print("\nCommon departments:")
print(sorted(dep1 & dep2))

print("\nAre the department values identical?")
print(dep1 == dep2)

Departments only in df1:
[]

Departments only in df2:
[]

Common departments:
['Atta, Rice & Dal', 'Baby Care', 'Bakery & Biscuits', 'Beauty & Cosmetics', 'Cold Drinks & Juices', 'Dairy & Breakfast', 'Munchies', 'Personal Care', 'Sweet Tooth']

Are the department values identical?
True

In [59]:
brand1 = set(df2['brand_name'].dropna().unique())
brand2 = set(df2['brand_name'].dropna().unique())

print("Brands only in df1:")
print(sorted(brand1 - brand2))

print("\nBrands only in df2:")
print(sorted(brand2 - brand1))

print("\nCommon brands:")
print(sorted(brand1 & brand2))

print("\nAre the brand values identical?")
print(brand1 == brand2)

Brands only in df1:
[]

Brands only in df2:
[]

Common brands:

In [60]:
city1 = set(df1['city'].dropna().unique())
city2 = set(df2['city'].dropna().unique())

print("Cities only in df1:")
print(sorted(city1 - city2))
print(len(city1 - city2))

print("\nCities only in df2:")
print(sorted(city2 - city1))
print(len(city2 - city1))

print("\nCommon cities:")
print(sorted(city1 & city2))
print(len(city1 & city2))

print("\nAre the city values identical?")
print(city1 == city2)

Cities only in df1:
[]
0

Cities only in df2:
[]
0

Common cities:
['Delhi', 'Gurgaon']
2

Are the city values identical?
True

In [62]:
df2['brand_name'].isnull().sum()

203

In [63]:
# Convert to numeric (if they are stored as strings)
df2['promo_offer_price'] = pd.to_numeric(df2['promo_offer_price'], errors='coerce')
df2['product_price'] = pd.to_numeric(df2['product_price'], errors='coerce')

# Find records where promo_offer_price > product_price
invalid_records = df2[
    (df2['promo_offer_price'].notna()) &
    (df2['product_price'].notna()) &
    (df2['promo_offer_price'] > df2['product_price'])
]

print(invalid_records[['unique_id', 'product_name', 'product_price', 'promo_offer_price']])
print(f"\nNumber of violating records: {len(invalid_records)}")

Empty DataFrame
Columns: [unique_id, product_name, product_price, promo_offer_price]
Index: []

Number of violating records: 0

In [64]:
# Treat NaN and empty strings as empty
price_exists = (
    df2['promo_offer_price'].notna() &
    (df2['promo_offer_price'].astype(str).str.strip() != '')
)

desc_exists = (
    df2['promo_offer_description'].notna() &
    (df2['promo_offer_description'].astype(str).str.strip() != '')
)

# One exists, the other doesn't (XOR)
invalid_records = df2[
    price_exists ^ desc_exists
]

print(invalid_records[
    ['unique_id', 'promo_offer_price', 'promo_offer_description']
])

Empty DataFrame
Columns: [unique_id, promo_offer_price, promo_offer_description]
Index: []

In [65]:
invalid = df2[
    df2['product_image_urls'].isna() |
    (df2['product_image_urls'].astype(str).str.strip() == '')
]

print(invalid[['unique_id', 'product_image_urls']])

Empty DataFrame
Columns: [unique_id, product_image_urls]
Index: []

In [66]:
# Length of product names (excluding leading/trailing spaces)
name_length = df2['promo_offer_description'].fillna('').str.strip().str.len()

# Define thresholds
MIN_LENGTH = 5
MAX_LENGTH = 10

# Find invalid product names
invalid_promo = df2[
    (name_length < MIN_LENGTH) |
    (name_length > MAX_LENGTH)
]

print(f"Number of invalid promo descriptions: {len(invalid_promo)}")

print(
    invalid_promo[
        ['unique_id', 'promo_offer_description', 'product_url']
    ].assign(name_length=name_length.loc[invalid_promo.index])
)

Number of invalid promo descriptions: 0
Empty DataFrame
Columns: [unique_id, promo_offer_description, product_url, name_length]
Index: []

In [67]:
field = 'promo_offer_price'  # Replace with the field you want to check
empty_field_records = df2[
    # df3[field].isna() 
    # |
    # (df3[field].astype(str).str.strip() == '')
    (df2[field]) == 0 
   
]

# Print unique_id and pdp_url
print(empty_field_records[[ 'item_mrp', 'item_selling_price', 'product_price', 'promo_offer_price', 'unique_id', 'product_url']])

Empty DataFrame
Columns: [item_mrp, item_selling_price, product_price, promo_offer_price, unique_id, product_url]
Index: []

In [72]:
# white space checking
column = 'product_grammage'   # Replace with your column name

# Find rows with leading/trailing spaces or multiple spaces between words
invalid_rows = df2[
    df2[column].fillna('').astype(str).str.contains(
        r'(^\s)|(\s$)|(\s{2,})',
        regex=True
    )
]

print("Number of invalid rows:", len(invalid_rows))
print(invalid_rows[['product_url', column]])
print(len(invalid_rows))

/tmp/ipykernel_6156/1661558706.py:6: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2[column].fillna('').astype(str).str.contains(

Number of invalid rows: 0
Empty DataFrame
Columns: [product_url, product_grammage]
Index: []
0